feat(Airdrop): Some `HoldingsDropdown` improvements / adjustments
status-im/status-desktop pull request #10006
Opened 2023-03-23 19:30 UTC by noeliaSD

Closes #9938

### What does the PR do

- Added `isCollectiblesOnly` option in `HoldingsDropdown`.
- Hidden assets tab in airdrop `HoldingsDropdown`.
- No data message added in `HoldingsDropdown`.
- Enabled navigation to mint tokens settings section from `HoldingsDropdown`.
- `storybook` updated accordingly.

### Affected areas

Community Settings / Airdrop / Permissions holdings dropdown

### Screenshot of functionality

https://user-images.githubusercontent.com/97019400/227328116-e61ca05a-dd09-45c8-bd99-4b529d29d78f.mov

https://user-images.githubusercontent.com/97019400/227328157-576ba7f3-79f3-4215-951f-60e8e4b142d1.mov

2023-03-23 19:37 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | fa8953b8 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-10006/1/) | 2023-03-23 19:37:11 | ~6 min | `tests-nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-10006/1//consoleText) |

2023-03-24 08:31 UTC, caybro approved these changes
LGTM

2023-03-24 11:51 UTC, micieslak requested changes
LGTM, but one problem found causing that label is not displayed

2023-03-24 12:19 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/controls/community/ExtendedDropdownContent.qml
> +    property string noDataText: {
No. It can be modified outside!

2023-03-24 12:24 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
> +            noDataText: root.noDataText
Yes, going to fix!

2023-03-24 12:32 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
> +            noDataText: root.noDataText
![Screenshot 2023-03-24 at 13 30 28](https://user-images.githubusercontent.com/97019400/227521918-aa9a92bb-88aa-44c7-84dd-0d4ac0b10678.png)

![Screenshot 2023-03-24 at 13 30 21](https://user-images.githubusercontent.com/97019400/227521930-d14689da-c875-4666-87bd-8d0db97086dd.png)

2023-03-24 12:38 UTC, micieslak approved these changes

2023-03-24 13:22 UTC, merged