fix(images): fix second pasted image replaces the first one
status-im/status-desktop pull request #10042
Opened 2023-03-27 17:53 UTC by jrainville

Fixes #9966

Uses the validate function to paste images so that it concatenates the previous images.

Fixes the validate function to also accept data images.

Moves the size validation function to Utils to reuse the data path prefix constant and fix the possible crash when we try to get the size of a data image.

2023-03-27 18:00 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 83b43b73 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-10042/1/) | 2023-03-27 18:00:00 | ~5 min | `tests-nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-10042/1//consoleText) |

2023-03-28 16:25 UTC, caybro commented on ui/imports/utils/Utils.qml
>          return Constants.acceptedDragNDropImageExtensions.some(ext => url.toLowerCase().includes(ext))
wdyt @jrainville ? I'd rather see this split into: `endsWith(ext) || startsWith(dataImagePrefix)`; imagine searching through the entire image blob for these things

2023-03-28 17:11 UTC, jrainville commented on ui/imports/utils/Utils.qml
>          return Constants.acceptedDragNDropImageExtensions.some(ext => url.toLowerCase().includes(ext))
Fixed

2023-03-28 17:20 UTC, caybro requested changes

2023-03-28 17:22 UTC, jrainville commented on ui/imports/shared/status/StatusChatInput.qml
> +        const validImages = validateImages(imagePaths)
It's an already existing function. Line 869

2023-03-28 17:43 UTC, caybro commented on ui/imports/shared/status/StatusChatInput.qml
> +        const validImages = validateImages(imagePaths)
Ah oops, my bad

2023-03-28 17:43 UTC, caybro approved these changes
LGTM, thanks!

2023-03-28 17:48 UTC, merged