test(suite_settings): mayfail tag remover for pass tests
status-im/status-desktop pull request #10265
Opened 2023-04-11 21:03 UTC by StateOf-Vlado

#9284

### What does the PR do

### Affected areas

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2023-04-11 21:10 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | c4285663 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-nim/job/PR-10265/1/) | 2023-04-11 21:10:09 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-nim/job/PR-10265/1//consoleText) |

2023-04-11 21:23 UTC, StateOf-Vlado commented
Test results: https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-e2e/job/PR-10260/6/

2023-04-13 14:51 UTC, anastasiyaig approved these changes

2023-04-13 18:12 UTC, saledjenic approved these changes

2023-04-14 07:52 UTC, noeliaSD requested changes
The test `The user add a contact with a chat key` works locally for me but the ones from `tst_mainSettinsSection`  that switches state from offline/online don't. 

The behavior is a bit random, sometimes one passes sometimes fails.. There are no tests runtime errors neither lookup errors it is just that the verification fails bc the expected status is wrong. So the tests seem to be ok, but the app behavior no. It should be online/offline but it isn't. 

Here one example of failure:

![Screenshot 2023-04-14 at 09 48 28](https://user-images.githubusercontent.com/97019400/231979600-07632f35-7aff-4abb-b3e7-89045c70d8b4.png)

- Screenshot when it should be offline:
![failed_1](https://user-images.githubusercontent.com/97019400/231979923-30b8a1a9-9318-4107-923b-f53b3e0547dc.png)

- Screenshot when it should be online:
![failed_2](https://user-images.githubusercontent.com/97019400/231979941-58a46f5c-1c20-467e-9ef9-ec113b6541c0.png)

I'm wondering at this point that maybe the app has a bugs on this functionality. I suggest to test some times manually to see if it is only reproducible with automation.

2023-04-19 20:30 UTC, StateOf-Vlado commented
> The test `The user add a contact with a chat key` works locally for me but the ones from `tst_mainSettinsSection` that switches state from offline/online don't.
> 
> The behavior is a bit random, sometimes one passes sometimes fails.. There are no tests runtime errors neither lookup errors it is just that the verification fails bc the expected status is wrong. So the tests seem to be ok, but the app behavior no. It should be online/offline but it isn't.
> 
> Here one example of failure:
> 
> ![Screenshot 2023-04-14 at 09 48 28](https://user-images.githubusercontent.com/97019400/231979600-07632f35-7aff-4abb-b3e7-89045c70d8b4.png)
> 
> * Screenshot when it should be offline:
>   ![failed_1](https://user-images.githubusercontent.com/97019400/231979923-30b8a1a9-9318-4107-923b-f53b3e0547dc.png)
> * Screenshot when it should be online:
>   ![failed_2](https://user-images.githubusercontent.com/97019400/231979941-58a46f5c-1c20-467e-9ef9-ec113b6541c0.png)
> 
> I'm wondering at this point that maybe the app has a bugs on this functionality. I suggest to test some times manually to see if it is only reproducible with automation.

@noeliaSD , fixed. could you please test on your local machine?

2023-04-20 13:10 UTC, StateOf-Vlado commented
test runs:
https://ci.infra.status.im/job/status-desktop/job/manual/11/
https://ci.infra.status.im/job/status-desktop/job/manual/9/
https://ci.infra.status.im/job/status-desktop/job/manual/8/

2023-04-20 16:34 UTC, noeliaSD commented
> > The test `The user add a contact with a chat key` works locally for me but the ones from `tst_mainSettinsSection` that switches state from offline/online don't.
> > The behavior is a bit random, sometimes one passes sometimes fails.. There are no tests runtime errors neither lookup errors it is just that the verification fails bc the expected status is wrong. So the tests seem to be ok, but the app behavior no. It should be online/offline but it isn't.
> > Here one example of failure:
> > ![Screenshot 2023-04-14 at 09 48 28](https://user-images.githubusercontent.com/97019400/231979600-07632f35-7aff-4abb-b3e7-89045c70d8b4.png)
> > 
> > * Screenshot when it should be offline:
> >   ![failed_1](https://user-images.githubusercontent.com/97019400/231979923-30b8a1a9-9318-4107-923b-f53b3e0547dc.png)
> > * Screenshot when it should be online:
> >   ![failed_2](https://user-images.githubusercontent.com/97019400/231979941-58a46f5c-1c20-467e-9ef9-ec113b6541c0.png)
> > 
> > I'm wondering at this point that maybe the app has a bugs on this functionality. I suggest to test some times manually to see if it is only reproducible with automation.
> 
> @noeliaSD , fixed. could you please test on your local machine?

I still have the same issues randomly happening locally and screenshots really say that the state is not the correct one.. Again, maybe it is a real issue in the app.. ?!

And regarding the test that changes the password, I also have some random failures but I think this case is due to timeouts, bc when restarting, or when changing the password, or when login again, it takes several time and I think the test sometimes doesn't wait enough time!

2023-04-20 18:56 UTC, StateOf-Vlado commented
> > > The test `The user add a contact with a chat key` works locally for me but the ones from `tst_mainSettinsSection` that switches state from offline/online don't.
> > > The behavior is a bit random, sometimes one passes sometimes fails.. There are no tests runtime errors neither lookup errors it is just that the verification fails bc the expected status is wrong. So the tests seem to be ok, but the app behavior no. It should be online/offline but it isn't.
> > > Here one example of failure:
> > > ![Screenshot 2023-04-14 at 09 48 28](https://user-images.githubusercontent.com/97019400/231979600-07632f35-7aff-4abb-b3e7-89045c70d8b4.png)
> > > 
> > > * Screenshot when it should be offline:
> > >   ![failed_1](https://user-images.githubusercontent.com/97019400/231979923-30b8a1a9-9318-4107-923b-f53b3e0547dc.png)
> > > * Screenshot when it should be online:
> > >   ![failed_2](https://user-images.githubusercontent.com/97019400/231979941-58a46f5c-1c20-467e-9ef9-ec113b6541c0.png)
> > > 
> > > I'm wondering at this point that maybe the app has a bugs on this functionality. I suggest to test some times manually to see if it is only reproducible with automation.
> > 
> > 
> > @noeliaSD , fixed. could you please test on your local machine?
> 
> I still have the same issues randomly happening locally and screenshots really say that the state is not the correct one.. Again, maybe it is a real issue in the app.. ?!
> 
> And regarding the test that changes the password, I also have some random failures but I think this case is due to timeouts, bc when restarting, or when changing the password, or when login again, it takes several time and I think the test sometimes doesn't wait enough time!

It should work, it is not a bug, because it works on my machine, so I increased waitFor to 5 sec, please rerun the test

2023-04-25 21:30 UTC, StateOf-Vlado commented on test/ui-test/src/screens/components/cahange_password_popup.py
> +        self._quit_button.wait_until_appears(15000).click()
Waiting for popup

2023-04-25 22:12 UTC, glitchminer requested changes
@StateOf-Vlado, I've sent you an export of the results. I had failures in the following:

**TestCase tst_mainSettingsSection**
- Scenario The user can backup seed phrase
- Scenario The user can switch state to online
- Scenario The user can change the password and login with new password 

**TestCase tst_userIdentity**
- ScenarioOutline The user sets display name, bio and social links 

**TestCase tst_contactsFlow** 
- Scenario The user can add a contact from the chat

2023-05-03 14:49 UTC, noeliaSD approved these changes
Last tries on my local machine passed!

2023-05-03 14:57 UTC, StateOf-Vlado commented
> @StateOf-Vlado, I've sent you an export of the results. I had failures in the following:
> 
> **TestCase tst_mainSettingsSection**
> 
> * Scenario The user can backup seed phrase
> * Scenario The user can switch state to online
> * Scenario The user can change the password and login with new password
> 
> **TestCase tst_userIdentity**
> 
> * ScenarioOutline The user sets display name, bio and social links
> 
> **TestCase tst_contactsFlow**
> 
> * Scenario The user can add a contact from the chat

fixed

2023-05-03 15:00 UTC, StateOf-Vlado commented
> @StateOf-Vlado, I've sent you an export of the results. I had failures in the following:
> 
> **TestCase tst_mainSettingsSection**
> 
> * Scenario The user can backup seed phrase
> * Scenario The user can switch state to online
> * Scenario The user can change the password and login with new password
> 
> **TestCase tst_userIdentity**
> 
> * ScenarioOutline The user sets display name, bio and social links
> 
> **TestCase tst_contactsFlow**
> 
> * Scenario The user can add a contact from the chat



> 

@glitchminer test the current solution, is it reproduced now?

2023-05-03 16:22 UTC, glitchminer approved these changes
@StateOf-Vlado , for a while I got a similar intermittent result like @noeliaSD, but running 1 at a time seems OK.

2023-05-03 16:23 UTC, merged