test/start application with custom data folder added
status-im/status-desktop pull request #10721
Opened 2023-05-16 19:05 UTC by StateOf-Vlado

#10293

- default user data folder was set up in the tests folder
- Application under tests (Aut) class added, will be used for attaching/detaching several clients in tests
- squish folder added in drivers folder (just for review, how we can import squish in test steps):
after import:
from drivers import squish
1) all squish methods of squish available
2) AUT methods available to start app
3) context methods available to detach all AUTs

So we can move all methods from SquishDriver, SquishDriverVerification in squish

2023-05-16 19:10 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | ea7cb944 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-10721/1/) | 2023-05-16 19:10:52 | ~5 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-10721/1//consoleText) |

2023-05-16 20:00 UTC, jrainville approved these changes

2023-05-16 20:00 UTC, jrainville commented on test/ui-test/__init__.py
You have some empty files

2023-05-17 10:00 UTC, StateOf-Vlado commented on test/ui-test/__init__.py
thanks, deleted

2023-05-18 12:08 UTC, noeliaSD requested changes
In general,  LGTM. However there are some specific cases (not default status folder used) where there are execution errors. Could you review them? Thanks!

2023-05-18 12:08 UTC, noeliaSD commented on test/ui-test/src/drivers/squish/aut.py
> +    if clear and data_dir.exists():
Maybe you can use here `filesMngr.erase_directory`

2023-05-18 12:08 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
>  def a_user_starts_the_application_with_a_specific_data_folder(context, data_folder_path):
There is something wrong with the scenarios that uses this statement (particular status folder). 

I.e: Check `suite_messaging/tst_groupChat` to reproduce:

![Screenshot 2023-05-18 at 14 04 12](https://github.com/status-im/status-desktop/assets/97019400/fc2c19cf-5a75-4159-8fb1-42504d6372a3)

**NOTE**: This scenario can fail bc it is marked as `relyon-mailserver` but should fail in another verification step, like when trying to check the other user chat, not in this first step where the app is still pending to be launched.

2023-05-23 11:42 UTC, iurimatias approved these changes

2023-05-23 11:42 UTC, merged

2023-05-24 07:28 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/commonInitSteps.py
>  def a_user_starts_the_application_with_a_specific_data_folder(context, data_folder_path):
> There is something wrong with the scenarios that uses this statement (particular status folder).
> 
> I.e: Check `suite_messaging/tst_groupChat` to reproduce:
> 
> ![Screenshot 2023-05-18 at 14 04 12](https://user-images.githubusercontent.com/97019400/239228603-fc2c19cf-5a75-4159-8fb1-42504d6372a3.png)
> 
> **NOTE**: This scenario can fail bc it is marked as `relyon-mailserver` but should fail in another verification step, like when trying to check the other user chat, not in this first step where the app is still pending to be launched.

Tested and, at least, the folder interaction works fine. However it seems the `suite_messaging` is not up to date with new app changes, so I've created a new task for that: https://github.com/status-im/status-desktop/issues/10781