fix(CodeScanner): fix QrCode Scanner not working on Linux
status-im/status-desktop pull request #11021
Opened 2023-06-09 18:29 UTC by jrainville

Fixes #10101

The problem was quite weird. The camera worked, but only when not **directly** in a Loader.

So I fixed by moving the Loader outside of StatusQrCodeScanner and into its parent SyncDeviceFromMobile.

The bahaviour is the same. We get a button asking to enable the camera, then we load the Scanner component. Before the Loader contained only the Camera component.

This PR needs to be tested in Mac and Windows too, but mostly Mac, because Igor told me the Loader was for Mac first of all.

I also need to test if this works in the AppImage. I only tested in dev (before it didn't even for in dev).

[camera.webm](https://github.com/status-im/status-desktop/assets/11926403/4da455ed-8746-43fb-ba2a-7600665ecd8f)

2023-06-09 18:34 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 37155a7b | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11021/1/) | 2023-06-09 18:34:32 | ~4 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11021/1//consoleText) |

2023-06-09 19:08 UTC, jrainville commented
I tested a locally build AppImage and it works :tada:

2023-06-10 09:01 UTC, igor-sirotin requested changes
@jrainville thanks for this ❤️ 

TLDR; do you think we could keep `Enable camera access` button in `StatusQrCodeScanner`?

_____

### 1. Tested on MacOS (not a blocker, just thoughts)

Works fine, the behaviour of status-desktop is the same: camera access system popup opens after clicking `Enable camera access`.
https://github.com/status-im/status-desktop/assets/25482501/f520e4f0-2967-46c2-8eab-4daa5a5fa1bc

But there's something that has changed, what can be easily seen with Sandbox. The system popup will open as soon as you go to the `QR Scanner` page:
https://github.com/status-im/status-desktop/assets/25482501/24c2083b-edf2-4f3e-a6e2-3655bb5e65d0

There's no `Enable camera access` button anymore, as it's out of the `StatusQrCodeScanner` component. This is totally fine in sandbox. And it's definitely better then opening this popup on application launch.
But I wonder if we will need same behaviour in https://github.com/status-im/status-desktop/issues/5070, for example?

I don't think this will work, but maybe: 
```qml
Loader {
    sourceComponent: Item {
        Camera {
        }
    }
}
```

Probably the problem is not that the `Camera` is created directly in `Loader`, but that it should be created together with smth like `VideoOutput` and these kind of things 🤔 

### 2. Minor UI bugs (this one's a blocker)

* There was a blue rectangle behind the button.

| before | now |
|-|-|
|  <img width="1312" alt="Screenshot 2023-06-10 at 11 54 31" src="https://github.com/status-im/status-desktop/assets/25482501/0c33a4d4-b2bb-4134-bcbd-c34d3dc16ba2"> | <img width="1312" alt="Screenshot 2023-06-10 at 11 42 35" src="https://github.com/status-im/status-desktop/assets/25482501/26abae6a-9b9a-4299-8bc0-6fa997a83a59"> | 

* Camera viewport was square, now it's rectangular and bigger:

| before | now |
|-|-|
| <img width="1312" alt="Screenshot 2023-06-10 at 11 56 36" src="https://github.com/status-im/status-desktop/assets/25482501/fac80dc4-3544-42a6-9f6f-960559305b94"> |  <img width="1312" alt="Screenshot 2023-06-10 at 11 53 19" src="https://github.com/status-im/status-desktop/assets/25482501/127a3cca-3d44-49bf-9ba3-b321f5c66d49"> |


_____
NOTE:
To reset Camera privacy settings on MacOS (worked only once for me):
```bash
tccutil reset Camera "im.Status.NimStatusClientDev"
```
or reset for all apps (works better):
```bash
tccutil reset Camera
```

2023-06-12 15:00 UTC, jrainville commented
Thanks for the tests @igor-sirotin 

> I don't think this will work, but maybe: (putting Item in the Loader)

I did try and it didn't work. I'm not sure why using Item doesn't work but the whole StatusQrCodeScanner works. 

My intuition is that the `VideoOutput` needs to be initialized at the same time?

> There's no Enable camera access button anymore, as it's out of the StatusQrCodeScanner component. This is totally fine in sandbox. 

I agree with you that it's fine for the sandbox. Firstly, we aren't really supporting the sandbox for real anymore. Great if it still works, but too bad if it's not perfect anymore.
Secondly, it doesn't really matter if the permission is asked at the start instead of having a button, because it's the sandbox, which is only for devs (devs don't deserve good UX :smiling_imp: :joy: )

> But I wonder if we will need same behaviour in https://github.com/status-im/status-desktop/issues/5070, for example?

Yeah, we'll probably need something similar for that ticket. I think it should be simple to make it work, instead of using a "page", we'll need a popup. In that case, we can put the button in the popup. If we want to reduce duplication, I guess we move the button in a separate component, or even better, we could wrap the button + StatusQrCodeScanner in another component and use that in both.

> 2. Minor UI bugs

Good find, I'll fix those

2023-06-12 17:36 UTC, jrainville commented
Updated:

![image](https://github.com/status-im/status-desktop/assets/11926403/794c5084-6f1f-4c2e-98d6-ea0ac06f839d)

![image](https://github.com/status-im/status-desktop/assets/11926403/30d4ebe0-ed35-4430-b391-b13b1f8fe156)

2023-06-13 15:12 UTC, jrainville commented
> Just got a minor warning in console:

Fixed

2023-06-13 16:39 UTC, caybro approved these changes
LGTM

2023-06-13 16:49 UTC, merged