feat(@desktop/wallet): Update activity feed sections date markers
status-im/status-desktop pull request #11332
Opened 2023-06-29 13:49 UTC by Cuteivist

closes #11306 

### What does the PR do

* Uses new time markers for sections
* Fixed timestamp in activity delegate

### Affected areas

Activity UI

### Screenshot of functionality (including design for comparison)

Design: https://www.figma.com/file/FkFClTCYKf83RJWoifWgoX/Wallet-v2?type=design&node-id=13138-409539&mode=design&t=O5H6uMt7DdkObklq-4

https://github.com/status-im/status-desktop/assets/11396062/f870c1e5-9c2e-4a40-b3ee-9bb34ab0f8be

2023-06-29 13:57 UTC, alaibe approved these changes

2023-06-29 13:58 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 297cf74d | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/aarch64/job/package/job/PR-11332/1/) | 2023-06-29 13:58:30 | ~8 min | `macos/aarch64` | [:apple:`dmg`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-230629-135016-297cf7-pr11332-aarch64.dmg) |

2023-06-29 14:56 UTC, caybro requested changes

2023-06-29 14:56 UTC, caybro commented on ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
>      function daysBetween(firstDate, secondDate) {
You're changing the semantics of an existing function... don't like that :)

Better keep this one intact and create a new one instead

2023-06-29 14:56 UTC, caybro commented on ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
> +    function getFirstDayOfTheWeek() {
Some docu would be nice, it's not clear from the function name what it does

2023-06-29 14:56 UTC, caybro commented on ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
> +        const dayOffset = loc.firstDayOfWeek === Qt.Monday ? 1 : 0
This is wrong, what if the first day of week is Tuesday?

2023-06-29 14:56 UTC, caybro commented on ui/StatusQ/src/StatusQ/Core/LocaleUtils.qml
> +        const dayOffset = loc.firstDayOfWeek === Qt.Monday ? 1 : 0
See `Qt.locale().firstDayOfWeek`

2023-06-29 14:56 UTC, caybro commented on ui/imports/shared/views/HistoryView.qml
> +                            return qsTr("Last month")
We already have very similar `LocaleUtils.formatRelativeTimestamp()`

2023-06-30 12:54 UTC, caybro approved these changes
LGTM

thanks for the fixes!

2023-06-30 12:55 UTC, merged