feat(wallet): use new status-go collectibles backend
status-im/status-desktop pull request #11559
Opened 2023-07-18 00:04 UTC by dlipicar

Fixes #11558
status-go part: https://github.com/status-im/status-go/pull/3734

Collectibles are now fetched in the background by status-go.

This PR makes use of the new Async endpoints in status-desktop. A lot of pieces are missing (listed in the epic), but the following basic functionality is implemented here:
- Use new async endpoints
- Filter by account and chainID lists
- React to collectibles list change reported by status-go
- Transmit only collectible headers for the list. Tramit full collectible details only when one is clicked. This should completely fix crashes due to large chunks of data being sent by the backend.

https://github.com/status-im/status-desktop/assets/11161531/3518de1e-6e09-42a8-a5c4-dc2db866f0d3

2023-07-18 00:09 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f854c294 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11559/1/) | 2023-07-18 00:09:49 | ~5 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11559/1//consoleText) |

2023-07-18 13:40 UTC, caybro requested changes
Massive work but...

pls check all the profile and showcase things still work as expected (I'm almost sure it will get broken with this PR)

2023-07-18 13:42 UTC, dlipicar commented
@caybro agh sorry, raised this late yesterday and intended it to be a Draft PR, but messed up. This is still not ready for review. Will fix all that before publishing this.

2023-07-18 14:07 UTC, dlipicar commented on ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
> +            baseModel: root.walletStore.collectibles
There's actually one thing I need to discuss with you guys about `MyProfileSettingsView` and `ProfileShowcaseView`...
This is supposed to show all collectibles owned by some account (ours or some contact's) we're checking the profile of, right? The `flatCollectibles` model we were using before contained whatever we were showing in the collectibles tab, which is basically the assets owned by all/any derivated/watch-only accounts we've added in the wallet (from whatever chains we've selected). 
We probably need a dedicated controller to get the list of collectibles we're actually interested in for these two screens. For example, for a contact we want to check whatever address they're exposing, and for our own profile we probably don't want to include watch-only accounts, is that correct?

2023-07-21 18:13 UTC, dlipicar commented on ui/app/AppLayouts/Profile/views/profile/MyProfileSettingsView.qml
> +            baseModel: root.walletStore.collectibles
The Wallet module gets its collectibles from the `Wallet/CollectiblesStore`
The Profile module gets its collectibles from the `Profile/WalletStore` instance. There, the collectibles model was renamed to `collectibles`. It points to the same one used by the wallet (which is wrong, the list of collectibles we show in the wallet and the one used for profile showcase are different, it needs to fetch them from the backend separately).

2023-07-21 18:14 UTC, dlipicar commented on ui/imports/shared/stores/NetworkConnectionStore.qml
> +    readonly property bool collectiblesCache: false
Added issue #

2023-07-21 18:14 UTC, dlipicar commented on storybook/pages/ProfileDialogViewPage.qml
> +                            readonly property var collectibles: ListModel {
See previous comment

2023-07-21 18:14 UTC, dlipicar commented on ui/imports/shared/views/profile/ProfileShowcaseView.qml
> +                model: root.isCurrentUser ? root.walletStore.ownedCollectibles : null // TODO get dedicated list of collectibles
See previous comment

2023-07-21 18:14 UTC, dlipicar commented
@caybro cleanup done, please re-check

2023-07-25 07:40 UTC, caybro commented
@dlipicar pls rebase; it doesn't even compile for me:
```
/home/ltinkl/git/status/status-desktop/src/backend/accounts.nim(389, 46) Error: type mismatch: got <string, string, string>
but expected one of:
proc loginWithKeycard(accountData: string; password: string; keyHex: string;
                      confNode: string): string
  first type mismatch at position: 4
  missing parameter: confNode

expression: status_go.loginWithKeycard($account, password, chatKey)
```

2023-07-25 07:57 UTC, caybro approved these changes
Code LGTM

But hard to test; I wasn't able to see any collectibles anywhere :)

![image](https://github.com/status-im/status-desktop/assets/5377645/5ee1038e-eec1-4cf6-8f0f-b586dadc3f5c)

2023-07-25 12:27 UTC, dlipicar commented
> Code LGTM
> 
> But hard to test; I wasn't able to see any collectibles anywhere :)
> 

@caybro working fine for me 
![image](https://github.com/status-im/status-desktop/assets/11161531/ded51e3d-80e7-4d29-8ae3-e379e02563ec)

I believe what you see is due to the fact that the current basic version will update collectibles when it's finished fetching them for all accounts. If you have many accounts with many collectibles, that can take a while. I'm working on the improvement to have the app be notified of partial fetches.

2023-07-26 13:20 UTC, alaibe approved these changes

2023-07-27 08:33 UTC, stefandunca approved these changes
Excellent job @dlipicar building a solid foundation for collectible access and moving business logic to status-go.

2023-07-27 13:02 UTC, anastasiyaig commented
@dlipicar i was adding this acc as w/o and it crashed the app `0xd8d6ffe342210057bf4dcc31da28d006f253cef0`. seems to be fine in master but maybe i was just lucky? Does it sound known issue or indeed could be a regression in this PR? 

```
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/src/nim_status_client.nim(193) nim_status_client
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/src/nim_status_client.nim(190) mainProc
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimqml/src/nimqml/private/qobject.nim(52) qobjectCallback
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimqml/src/nimqml/private/qobject.nim(37) onSlotCalled
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(561) onSlotCalled
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/src/app_service/service/wallet_account/service.nim(747) onAllTokensBuilt
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/src/app_service/service/wallet_account/dto.nim(216) getVisibleForNetworkWithPositiveBalance
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tables.nim(244) []
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(179) genericSeqAssign
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(143) genericAssign
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(97) genericAssignAux
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(494) newSeq
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(486) newObj
/Users/jenkins/workspace/s_macos_aarch64_package_PR-11559/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim(735) rawAlloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

2023-07-27 13:23 UTC, dlipicar commented
@anastasiyaig this seems to be the known bug when status-go sends a big chunk of data to nim, it crashes when deserializing (not always, depends on the app's memory usage in that instant). It's triggered by receiving the list of ERC20 tokens, not by anything related to collectibles, so I'd report a separate bug.

2023-07-27 15:48 UTC, merged