fix: Review scrolling behavior for holdings dropdown
status-im/status-desktop pull request #11691
Opened 2023-07-27 13:50 UTC by caybro

- remove padding and use margins so that the listview can span the whole width while having the scrollbar neatly next to it
- make the section header both inline and floatable (which makes it always visible, even when scrolled away)
- fix the special search results "section" to behave the same way
- sort the results by category and name
- expose the `allTokensMode` for easy testing with storybook

Closes #10201

### Affected areas

holdings dropdown

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

[Záznam obrazovky z 2023-07-27 15-46-45.webm](https://github.com/status-im/status-desktop/assets/5377645/6c10ab5f-840d-407b-bb81-1747ae692491)

Plain list, all tokens:
![image](https://github.com/status-im/status-desktop/assets/5377645/7065d43b-88b1-4e70-8eaa-60fb3d575eab)

Plain list, all tokens + search, scrolled down:
![image](https://github.com/status-im/status-desktop/assets/5377645/6af0ab58-d0b8-4512-8832-d79ba98c2802)

2023-07-27 13:55 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f1e77ada | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11691/1/) | 2023-07-27 13:55:43 | ~5 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11691/1//consoleText) |

2023-07-28 09:18 UTC, micieslak requested changes
I have found several issues:

1. In most cases the content is scrollable when it shouldn't be (it's regression in comparison to master):

https://github.com/status-im/status-desktop/assets/20650004/44e73415-d1c1-49f5-aa23-728144ca8b26

2. This design hint seems not taken into account, it seems to be the most crucial part regarding sizing/scrolling:
![Screenshot from 2023-07-28 11-14-02](https://github.com/status-im/status-desktop/assets/20650004/f07a1752-377c-4905-b680-5421aec66aa0)

3. When scrolling, the gray cut-off line should be visible:
Design:
![Screenshot from 2023-07-28 11-07-23](https://github.com/status-im/status-desktop/assets/20650004/be611924-62c7-4a32-9d14-cfee930b91ff)

Impl:
![Screenshot from 2023-07-28 11-07-03](https://github.com/status-im/status-desktop/assets/20650004/57f15e5f-38f7-4381-a272-a8e6f34cacd6)

2023-07-28 09:39 UTC, caybro commented
> I have found several issues:
> 
> 1. In most cases the content is scrollable when it shouldn't be (it's regression in comparison to master):

Right, it's the list view's `bottomMargin` 

> 2. This design hint seems not taken into account, it seems to be the most crucial part regarding sizing/scrolling:

OK, I kinda missed this part

> 3. When scrolling, the gray cut-off line should be visible:

Yeah, overlooked the dropdown shadow there

Thanks for the feedback, will fix!

2023-07-28 13:16 UTC, caybro commented
@micieslak I pushed the fixes (minus the floating divider; added a FIXME)

2023-07-28 13:40 UTC, alexjba commented on ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
> +            visible: false // FIXME this should be visible only when floating
This should do the trick
```suggestion
            visible: parent.y === root.contentY
```

2023-07-28 14:04 UTC, caybro commented on ui/app/AppLayouts/Communities/controls/ListDropdownContent.qml
> +            visible: false // FIXME this should be visible only when floating
Genius! :rocket: it works

2023-07-28 14:55 UTC, micieslak approved these changes
Cool! Especially sections part :)

One minor thing, looks like lack of bottomMargin of listView (in design bottom space is bigger):

![Screenshot from 2023-07-28 16-50-51](https://github.com/status-im/status-desktop/assets/20650004/6f6c17cf-cdfe-4828-a39e-c944270d315d)

2023-07-28 15:46 UTC, merged