feat(@desktop/wallet): Update remove keypair popup to match the Figma
status-im/status-desktop pull request #11838
Opened 2023-08-08 19:02 UTC by Khushboo-dev-cpp

fixes #11734

### What does the PR do

Implements the popup : https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=15814%3A385398&mode=dev

### Affected areas

Wallet Settings

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

2023-08-08 19:08 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 27e18f45 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11838/1/) | 2023-08-08 19:08:23 | ~5 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-imports/job/PR-11838/1//consoleText) |

2023-08-09 08:41 UTC, alaibe approved these changes

2023-08-09 08:48 UTC, saledjenic requested changes

2023-08-09 08:48 UTC, saledjenic commented on ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
> +    title: qsTr("Edit group name and image")
@Khushboo-dev-cpp this is not the correct popup title.

2023-08-09 08:48 UTC, saledjenic commented on ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
> +            text: qsTr("Are you sure you want to remove Metamask seed phrase keypair? The keypair will be removed from all of your synced devices. Make sure you have a backup of your keys or seed phr
@Khushboo-dev-cpp the text is wrong here.

2023-08-09 08:48 UTC, saledjenic commented on ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
> +                Column {
@Khushboo-dev-cpp if there are more accounts, they won't be visible since this area is not scrollable.

2023-08-09 08:55 UTC, saledjenic commented
@Khushboo-dev-cpp one more issue I see in your video is just `0` for account balance, but should be `0,00 USD`.

2023-08-09 09:02 UTC, saledjenic commented
@Khushboo-dev-cpp and one more issue I've just faced, if you leave the app opened for some time, let's say up to 10 mins, you will see that the accounts list in the remove keypair popup gets refreshed and all accounts disappear: 

![__2](https://github.com/status-im/status-desktop/assets/86303051/f7e765e2-499c-4904-a12e-b247cea4ca19)

2023-08-09 16:14 UTC, Khushboo-dev-cpp commented on ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
> +                icon.name: root.isOnKeycard ? "keycard" : "password"
does biometric only work for user profile seed phrase accounts? @saledjenic ?

2023-08-10 06:01 UTC, saledjenic commented on ui/app/AppLayouts/Profile/popups/RemoveKeypairPopup.qml
> +                icon.name: root.isOnKeycard ? "keycard" : "password"
@Khushboo-dev-cpp sorry for the confusion (was into some other work and missed the context :) ), what I wanted to say is that we don't need icon at all, cause we don't need authentication for keypair remove action. Feel free to remove icon from this button.

2023-08-10 06:20 UTC, saledjenic commented
> I think we discussed this a couple of times

I remember that we had a similar discussion for send modal, but also remember that my proposal was that we need to capture the app state at the moment of popup opening, that way any side effect/change won't affect that popup. Also what I remember is that I said that we need to build a mechanism which will monitor on active popup in the moment any related action is received from the network and take appropriate action. But not sure if we ever did something towards that.

> should we close the popup if the app was left idle for 10 mins and a refresh happens on the background?

I am pretty sure that it may happen even earlier, you don't need to wait ~10 mins to face that, depends in which moment you open a popup. There are many actions which trigger refresh, some of them are cause by the user's activity on the device, some of them are caused by syncing and some are time driven. For example if we fetch balances every 10 mins, and user opens remove keypair popup after 9 mins and 55 seconds from the last balances fetch user will see accounts list for few seconds and it will disappear then. That's why I think we need to solve this properly. There are 2 solutions I see:
1. to work with the copy of the model/item depends on context
2. stop UI model update while the popup is opened and refresh it once popup is closed

I am more for the option 1. in this case.

2023-08-10 08:35 UTC, saledjenic commented
@Khushboo-dev-cpp I didn't go into details and didn't investigate what's the reason of that refresh or whatever is the reason, I've just checked out this branch, built the app, opened remove keypair popup and left it for a while and I just lost the list of accounts for the keypair from the view.

We can ask @anastasiyaig to test it and see if that's reproducible?

2023-08-10 08:36 UTC, saledjenic commented
@Khushboo-dev-cpp the rest is fine, thanks for the fixes.

2023-08-10 10:04 UTC, anastasiyaig commented
i checked latest master and it is not reproducible there. I did not check the branch though @saledjenic

2023-08-10 10:35 UTC, Khushboo-dev-cpp commented
> i checked latest master and it is not reproducible there. I did not check the branch though @saledjenic

Hey @anastasiyaig this PR is pending for test anyway so if you could check when you test this PR, it would be perfect.

@saledjenic when you check when I first created the PR the issue was there for sure, I fixed it when updating the review comments :)

2023-08-10 15:50 UTC, Khushboo-dev-cpp commented
Raised https://github.com/status-im/status-desktop/issues/11866 for notification not showing after deleting keypair

2023-08-10 15:57 UTC, anastasiyaig approved these changes

2023-08-10 15:58 UTC, anastasiyaig commented
@saledjenic i was not able to reproduce the issue with disappearing accounts

2023-08-10 16:01 UTC, saledjenic approved these changes

2023-08-10 17:57 UTC, merged