feat(wallet): Fixed balance history chart to use transfers data
status-im/status-desktop pull request #12190
Opened 2023-09-18 11:47 UTC by IvanBelyakoff

### What does the PR do

- Balance history points are now returned at irregular intervals based on transfers timestamps and values.
- Additional points returned at the start and the end of the requested interval, plus additional padding points to make the chart look more smooth
- Fixed wrong balance on tooltip

### Affected areas

wallet->token->balance chart

### Screenshot of functionality
- [x] I've checked the design and this PR matches it (Current design is not very detailed in many aspects. @benjthayer is working on a new design and there was no goal to improve the current one, just not to make it worse, but some changes in look can be noticed - chart labels position and look, tooltip data.

Screenshot 
![new_history_eth_1month](https://github.com/status-im/status-desktop/assets/15627093/151428fd-a6df-4cf1-a017-bbd4da972d19)

https://github.com/status-im/status-desktop/assets/15627093/143cf9c3-081b-4694-bbf8-80bfd1251768

### NOTE
On video balance on chart does not match balance on header when Optimism network is enabled. That is because we don't support ERC1155 transfers yet, which cause this difference.
Account in test: 0x333c5dba8179822056f2289bdede1b53a863f577

Updates UI for [balance history feature](https://github.com/status-im/status-go/issues/3835)

2023-09-18 11:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 144093f1 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-statusq/job/PR-12190/1/) | 2023-09-18 11:53:41 | ~5 min | `tests/imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-statusq/job/PR-12190/1//consoleText) |

2023-10-04 11:13 UTC, caybro reviewed
Looks good with one exception: the x-axis sometimes shows non-localized dates (like Sep 27) and sometimes correctly translated, how come?

2023-10-04 11:15 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
> +                                return label.slice(0,label.indexOf(":")+1) + " %1".arg(RootStore.currencyStore.currentCurrencySymbol) + label.slice(label.indexOf(":") + 1, label.length);
This should properly format the currency amount, ie `LocaleUtils.currencyAmountToLocaleString()`

2023-10-04 11:16 UTC, caybro requested changes
The currency amount formatting needs fixing too

2023-10-04 11:18 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
> +                                return label.slice(0,label.indexOf(":")+1) + " %1".arg(RootStore.currencyStore.currentCurrencySymbol) + label.slice(label.indexOf(":") + 1, label.length);
Your balance on the left suggests your locale uses a comma `,` (2 116,31 USD) as a decimal separator, yet the video shows the tooltip in the chart formatted as `USD2.01`: both currency symbol placement and the decimal separator being wrong

2023-10-04 12:25 UTC, stefandunca approved these changes
I like the details. Excellent first step.

Looking at the video, it seems to me that maybe the line thickness doesn't serve the new model as much. However, a thing to improve on a followup PR.
![image](https://github.com/status-im/status-desktop/assets/47554641/23a7f3cc-a8e0-4b72-9732-9263782fd1c5)

2023-10-06 12:57 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
> +                                return LocaleUtils.currencyAmountToLocaleString({ amount: value.toFixed(2), symbol: RootStore.currencyStore.currentCurrencySymbol })
This (`toFixed(2)`) is probably why the number is formatted wrong... see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

2023-10-06 13:01 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/AssetsDetailView.qml
> +                                return LocaleUtils.currencyAmountToLocaleString({ amount: value.toFixed(2), symbol: RootStore.currencyStore.currentCurrencySymbol })
You can pass `options {displayDecimals: 2}` to get the same result in the correct way

2023-10-06 13:33 UTC, caybro approved these changes
Great stuff, thanks!

2023-10-06 13:53 UTC, merged