feat(discord): Import single channel from discord
status-im/status-desktop pull request #12458
Opened 2023-10-16 18:41 UTC by borismelnik

Fixes: #12238

### What does the PR do

Importing single channel from discord functionality 

### Affected areas

Discord import 

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

![Снимок экрана 2023-10-16 в 21 40 26](https://github.com/status-im/status-desktop/assets/82511785/9b669eab-224e-417a-b937-c59ffc118959)
![Снимок экрана 2023-10-16 в 21 41 20](https://github.com/status-im/status-desktop/assets/82511785/27ea9c18-fcd9-48aa-abdf-c434493285dc)

2023-10-16 18:47 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 04f23551 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-nim/job/PR-12458/1/) | 2023-10-16 18:47:52 | ~5 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/x86_64/job/tests-nim/job/PR-12458/1//consoleText) |

2023-10-17 07:35 UTC, caybro commented on ui/app/AppLayouts/Communities/stores/CommunitiesStore.qml
> +//        console.warn("!!! IMPLEMENT ME requestImportDiscordChannel") // FIXME
Can be removed :)

2023-10-17 07:35 UTC, caybro commented on src/app/modules/main/communities/io_interface.nim
> +method discordImportProgressUpdated*(self: AccessInterface, communityId: string, communityName: string, channelId: string, channelName: string, communityImage: string, tasks: seq[DiscordImportTaskPro
I don't see this being updated in `module.nim`; it still has this signature:
```nim
method discordImportProgressUpdated*(
    self: Module,
    communityId: string,
    communityName: string,
    communityImage: string,
    tasks: seq[DiscordImportTaskProgress],
    progress: float,
    errorsCount: int,
    warningsCount: int,
    stopped: bool,
    totalChunksCount: int,
    currentChunk: int
```

2023-10-17 18:31 UTC, jrainville approved these changes
Looks good

2023-10-17 18:31 UTC, jrainville commented on src/app_service/service/community/service.nim
> +        error "Error importing discord channel", msg = e.msg
Do we have an error state in the popup for a failure to start?

2023-10-25 14:47 UTC, caybro commented on src/app/modules/main/communities/io_interface.nim
> +method discordImportProgressUpdated*(self: AccessInterface, communityId: string, communityName: string, channelId: string, channelName: string, communityImage: string, tasks: seq[DiscordImportTaskPro
Ah my bad!

2023-10-25 14:48 UTC, caybro approved these changes
LGTM

2023-10-30 15:52 UTC, glitchminer requested changes
Hi @borismelnik , I have not successfully been able to import messages. I'm using test data that was shared but modified to have only 1 message, the earliest one.

First test fails to complete due to failed asset download. 
![image](https://github.com/status-im/status-desktop/assets/50769329/2162dcb7-8bf1-4516-99dc-0ba431006c6e)

---
Second test with same data but the failing asset removed fails to complete or create channel at all. App becomes unresponsive and shows messages imported as 133%
![image](https://github.com/status-im/status-desktop/assets/50769329/a84056ee-e44b-44fc-b2f8-b61b186a63b5)

---
Third test using full unmodified json also failed in the same way as the second.

2023-11-03 13:31 UTC, closed without merging

2023-11-03 13:31 UTC, borismelnik commented
Moved to https://github.com/status-im/status-desktop/pull/12634