fix(delete): fix closing the app before login would make it crash
status-im/status-desktop pull request #12881
Opened 2023-11-27 18:23 UTC by jrainville

Fixes #12880

There were two problems:
1. We manually delete the startup module on login to free memory. Part of that clean up includes remove the QVariant (` singletonInstance.engine.setRootContextProperty("startupModule", newQVariant())`), but since that code was put in the `delete` function of the module, it meant it was also executed on quit, and you can't call `setRootContextProperty` on quit
2. The wallet module is created on app start. That's fine, it doesn't do anything. However, it has a sub module that later in its cycle creates account items, but most of the time, those account items are not initiated, so on `delete`, there was a crash.

2023-11-27 18:30 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 01b9c8ce | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-12881/1/) | 2023-11-27 18:30:39 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-12881/1//consoleText) |

2023-11-28 08:02 UTC, anastasiyaig commented
I can confirm this PR fixes issue that were facing my tests, when running - the app was crashing in wallet module. Now they are good

https://ci.status.im/job/status-desktop/job/e2e/job/manual/1124/allure/

2023-11-28 08:16 UTC, saledjenic approved these changes

2023-11-28 08:58 UTC, caybro commented on src/app/modules/main/wallet_section/send/view.nim
> +    if self.selectedSenderAccount != nil:
Now this looks wrong... :) And would still crash under some conditions imo

```suggestion
    if self.selectedReceiveAccount != nil:
```

2023-11-28 09:16 UTC, jakubgs commented
Can't really review this, but thank you for tracking this down.

2023-11-28 10:11 UTC, caybro requested changes
Sorry for the red flag :)

2023-11-28 10:12 UTC, anastasiyaig commented
can someone do this change? Jo is on vacation and i need this pr @caybro

2023-11-28 10:12 UTC, caybro commented
> can someone do this change? Jo is on vacation and i need this pr @caybro

Yeah, I can do it, just a minute

2023-11-28 10:15 UTC, caybro commented
> > can someone do this change? Jo is on vacation and i need this pr @caybro
> 
> Yeah, I can do it, just a minute

Done, let's just wait for the build to finish :)

2023-11-28 10:15 UTC, caybro approved these changes

2023-11-28 11:41 UTC, anastasiyaig commented
I will be brave to merge it :)

2023-11-28 11:41 UTC, merged

2023-11-28 14:59 UTC, jrainville commented
I'm not yet on vacation, but thanks for doing it for me :laughing:

2023-11-28 15:01 UTC, anastasiyaig commented
oh , i am so sorry @jrainville 

![image](https://github.com/status-im/status-desktop/assets/82375995/adab5954-cdae-4f85-a957-3d104328382e)