feat(@desktop/toast): Community Token received notification
status-im/status-desktop pull request #13116
Opened 2024-01-02 12:27 UTC by Cuteivist

Closes https://github.com/status-im/status-desktop/issues/13086

status-go change https://github.com/status-im/status-go/pull/4515

### What does the PR do

Handle new notification - community token received

* Handle backend notification
* Using temporary notification delegates. They will be replaced in https://github.com/status-im/status-desktop/issues/12515

### Affected areas

Wallet / notifications

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/11396062/643343e8-0262-43c9-b112-64dde2e59486

2024-01-02 12:34 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | aa4c805a | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13116/1/) | 2024-01-02 12:34:12 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13116/1//consoleText) |

2024-01-02 13:44 UTC, caybro requested changes

2024-01-02 13:44 UTC, caybro commented on ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
> +            communityColor: community ? community.color : "black"
Is `black` a good default? Shouldn't it rather be `transparent`?

2024-01-02 13:45 UTC, caybro requested changes

2024-01-02 13:45 UTC, caybro commented on ui/imports/shared/views/AssetsView.qml
> +                    return customFilter.isCommunity ? !!model.communityId : !model.communityId
This change doesn't make sense here, pls remove

2024-01-02 13:56 UTC, caybro commented on ui/imports/shared/views/AssetsView.qml
> +                    return customFilter.isCommunity ? !!model.communityId : !model.communityId
It breaks hiding explicitly those selected by the user in `Settings/Manage tokens/Assets/

2024-01-02 13:57 UTC, caybro commented on ui/app/mainui/activitycenter/popups/ActivityCenterPopup.qml
> +            communityColor: community ? community.color : "black"
Alright...

2024-01-02 13:58 UTC, caybro commented on ui/imports/shared/views/AssetsView.qml
> +                    return customFilter.isCommunity ? !!model.communityId : !model.communityId
In other works, you have to factor in the following code:
```qml
if (!d.controller.filterAcceptsSymbol(symbol)) // explicitely hidden
  return false
```

2024-01-02 14:25 UTC, caybro approved these changes
Nice, thanks!

2024-01-04 11:24 UTC, alaibe approved these changes

2024-01-04 12:22 UTC, merged