fix(@wallet): prevent black image in token list
status-im/status-desktop pull request #13119
Opened 2024-01-03 11:05 UTC by alaibe

fixes #12718

2024-01-03 11:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | dd2487e8 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13119/1/) | 2024-01-03 11:11:42 | ~5 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13119/1//consoleText) |

2024-01-03 11:27 UTC, Khushboo-dev-cpp approved these changes
LGTM

2024-01-03 12:37 UTC, Khushboo-dev-cpp commented on ui/app/AppLayouts/Profile/popups/TokenListPopup.qml
> -        /* This late binding has been added here because without it all
can we please still keep this component, we are stilling assigning model on Component.onCompleted and not normally to avoid performance issues.

2024-01-03 12:37 UTC, Khushboo-dev-cpp approved these changes
one small comment else looks good

2024-01-03 15:21 UTC, caybro requested changes

2024-01-03 15:21 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/RightTabView.qml
> +                    visible: walletTabBar.currentIndex !== 2 // hide filter button on activity tab
This is not part of the fix and not even desired:

![image](https://github.com/status-im/status-desktop/assets/5377645/cecf6694-62a5-491a-b5b3-35678cee96c8)

2024-01-04 11:15 UTC, caybro approved these changes
:+1:

2024-01-04 11:59 UTC, merged