fix: Remove fleet selection from settings
status-im/status-desktop pull request #13848
Opened 2024-03-05 17:36 UTC by caybro

### What does the PR do

- drop the modal and radio selector too, not used anywhere else

Fixes #13352

### Affected areas

Settings/Advanced

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

![image](https://github.com/status-im/status-desktop/assets/5377645/429e7506-0c42-4654-8c7b-6b3888824435)

2024-03-05 17:43 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5e1009c8 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13848/1/) | 2024-03-05 17:43:52 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-13848/1//consoleText) |

2024-03-05 21:40 UTC, saledjenic approved these changes
Removing is ok, not sure only about the point @richard-ramos made in [this](https://github.com/status-im/status-desktop/issues/13352#issuecomment-1938702046) comment.

2024-03-05 22:09 UTC, igor-sirotin requested changes
The implementation (de-implementation I'd say 😄) is good with me.
Explaining the  mark as 'request changes' below.

-----

Indeed there was a discussion today to keep this selector, but make it "more dev-usage-only obvious". E.g. move to some "Debug section", or only allow to change when `Debug` is enabled, smth like that. Or even keep it as is, but add some exaplnating label.

The reason why to keep this is to be able to test deployed fleets with Status apps. Recently we faced an issue because `shards.test` fleet was upgraded. This wouln't happen if the upgrade was first done on `.test` fleet, tested by Status QA team and then deployed to `.prod` fleet.

This workflow also requires switching status to `prod`. 

cc @chair28980 @anastasiyaig @John-44

2024-03-06 08:02 UTC, caybro commented
> The implementation (de-implementation I'd say 😄) is good with me. Explaining the mark as 'request changes' below.
> 
> Indeed there was a discussion today to keep this selector, but make it "more dev-usage-only obvious". E.g. move to some "Debug section", or only allow to change when `Debug` is enabled, smth like that. Or even keep it as is, but add some exaplnating label.
> 
> The reason why to keep this is to be able to test deployed fleets with Status apps. Recently we faced an issue because `shards.test` fleet was upgraded. This wouln't happen if the upgrade was first done on `.test` fleet, tested by Status QA team and then deployed to `.prod` fleet.
> 
> This workflow also requires switching status to `prod`.
> 
> cc @chair28980 @anastasiyaig @John-44

OK then the most straightforward solution would be to just hide it in `production`, wdyt?

2024-03-06 09:28 UTC, igor-sirotin commented
> > The implementation (de-implementation I'd say 😄) is good with me. Explaining the mark as 'request changes' below.
> > Indeed there was a discussion today to keep this selector, but make it "more dev-usage-only obvious". E.g. move to some "Debug section", or only allow to change when `Debug` is enabled, smth like that. Or even keep it as is, but add some exaplnating label.
> > The reason why to keep this is to be able to test deployed fleets with Status apps. Recently we faced an issue because `shards.test` fleet was upgraded. This wouln't happen if the upgrade was first done on `.test` fleet, tested by Status QA team and then deployed to `.prod` fleet.
> > This workflow also requires switching status to `prod`.
> > cc @chair28980 @anastasiyaig @John-44
> 
> OK then the most straightforward solution would be to just hide it in `production`, wdyt?

Yes, until we want to test this with prod release 😄 

Let's see what other people response. I'll tag @jrainville as well for context.

2024-03-06 17:08 UTC, jrainville commented
> > OK then the most straightforward solution would be to just hide it in `production`, wdyt?
> 
> Yes, until we want to test this with prod release 😄
> 
> Let's see what other people response. I'll tag @jrainville as well for context.

If we want QAs to test, then hiding it in production is not the best, because QAs mostly use CI builds that are in production.

Doing something like Igor said is probably the simplest. Hide it when not in Debug, or we can add a new switch in the Advanced section to hide it.

2024-03-07 08:08 UTC, caybro commented
> > > OK then the most straightforward solution would be to just hide it in `production`, wdyt?
> > 
> > 
> > Yes, until we want to test this with prod release 😄
> > Let's see what other people response. I'll tag @jrainville as well for context.
> 
> If we want QAs to test, then hiding it in production is not the best, because QAs mostly use CI builds that are in production.
> 
> Doing something like Igor said is probably the simplest. Hide it when not in Debug, or we can add a new switch in the Advanced section to hide it.

It is already in the Advanced section; I'll add an envvar so that we can enable it at will (by default this will be hidden)

2024-03-07 08:25 UTC, caybro commented
Ok, third time's a charm :) @jrainville @igor-sirotin @anastasiyaig

2024-03-07 12:36 UTC, igor-sirotin reviewed
Maybe go with some more generic solution with desktop config?
https://github.com/status-im/status-desktop/blob/96d9acf1f036426e3882fe1578f2fd9f581b4d7f/src/env_cli_vars.nim#L92

2024-03-07 22:46 UTC, caybro commented
> Maybe go with some more generic solution with desktop config?
> 
> https://github.com/status-im/status-desktop/blob/96d9acf1f036426e3882fe1578f2fd9f581b4d7f/src/env_cli_vars.nim#L92

OK, updated with the suggestion; I hope it's fine now :laughing:

2024-03-08 12:17 UTC, igor-sirotin approved these changes
Looks good to me! Thank you!

2024-03-08 12:29 UTC, merged