fix: Removed duplicated text in Token Popup
status-im/status-desktop pull request #14428
Opened 2024-04-15 12:57 UTC by Seitseman

fixes [#14366](https://github.com/status-im/status-desktop/issues/14366)

### What does the PR do

Made sure Token List title is only appended if sourceName does not already ends with such string

### Screenshot of functionality (including design for comparison)

![image](https://github.com/status-im/status-desktop/assets/5157464/59ff4787-3286-46c0-891a-346feaae9190)

2024-04-15 13:04 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5aa9b4a6 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14428/1/) | 2024-04-15 13:04:29 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14428/1//consoleText) |

2024-04-15 13:18 UTC, caybro requested changes
This won't (or may not) work due to the translations; better just display the token list name verbatim

2024-04-18 06:39 UTC, alexjba commented
> This won't (or may not) work due to the translations; better just display the token list name verbatim

Yup. I think it's better, but still not something we can translate.

@alaibe Would it be a good idea to change the `name` to contain only the provider name (E.g. Status or Uniswap) so that we can append `Token List` and also to translate this?

https://github.com/status-im/status-go/blob/12deb2336028639ff11b6a3e08043e2961bed5c4/services/wallet/token/uniswap_tokenstore.go#L19

2024-04-18 07:55 UTC, alaibe commented
@alexjba yes indeed, backend should not provide any text to render, we could even potentially simply returns a "key"

2024-04-18 08:03 UTC, alexjba commented
> @alexjba yes indeed, backend should not provide any text to render, we could even potentially simply returns a "key"

Good point! A "key" is even better. Do you want me to add a task for this?

2024-04-18 08:07 UTC, Seitseman commented
In this case current PR becomes irrelevant. Should it be discarded now?

2024-04-18 08:46 UTC, Seitseman commented
I would leave on the backend side only names, I doubt anyone would like to see 'Uniswap' or 'Status' words translated, and then UI part appends translated 'Token List'

2024-04-18 08:48 UTC, caybro commented
> I would leave on the backend side only names, I doubt anyone would like to see 'Uniswap' or 'Status' words translated, and then UI part appends translated 'Token List'

That's how it should look like actually, e.g.:
```qml
  text: qsTr("%1 Token List").arg(backendTokenListName)
```

2024-04-18 09:12 UTC, alexjba commented
> > In this case current PR becomes irrelevant. Should it be discarded now?
> 
> Not sure. It's true, we'll need a status-go update to do a proper fix in status-desktop. But if the status-go update will not happen soon, we can have an intermediary version where we consider the `name` as `key` and set the title as a full `qsTr`. The `name` is hardcoded in status-go and it should be safe for now.
> 
> I guess you have a few options:
> 
> 1. Get your hands dirty and go for an e2e fix. But it's not going to be a nice first task 😄 Lots of logistics and code to go through.
> 2. Do an intermediary fix and wait for a status-go update. But we'll need a new task so that we don't forget about this.
> 3. Drop it and wait for status-go and nim integration. We should add the `blocked` task and link it with the new backend tasks.

NVM, looks like we have a key in the nim model. So could be just a string mapping:
```
https://github.com/status-im/status-desktop/blob/master/src/app/modules/main/wallet_section/all_tokens/sources_of_tokens_model.nim#L41
```

2024-04-18 09:45 UTC, caybro commented
We also have this in Constants.qml:
```qml
readonly property QtObject supportedTokenSources: QtObject {
        readonly property string uniswap: "Uniswap Labs Default Token List"
        readonly property string status: "Status Token List"
        readonly property string custom: "custom"
    }
```

2024-05-10 14:32 UTC, caybro commented
@Seitseman ping, any progress here?

2024-07-15 14:34 UTC, closed without merging