fix(identicon): fix Ethereum icon not appearing in community tags
status-im/status-desktop pull request #14604
Opened 2024-05-03 18:32 UTC by jrainville

Fixes #14599

The problem was that the Twemoji `emojiId` function blocked on the replace whereas `iconHex` works.
It's the same that is used in `StatusCommunityTag.qml`.

Maybe it's worth modifying all the `emojiId` calls to `iconHex`?

![image](https://github.com/status-im/status-desktop/assets/11926403/d1d9d4af-720f-46e7-8287-d7c7b7c94965)

2024-05-03 18:39 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | cd102b73 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14604/1/) | 2024-05-03 18:39:09 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14604/1//consoleText) |

2024-05-03 21:23 UTC, caybro approved these changes
LGTM

Not sure if it's worth and safe replacing it everywhere; would need more testing/checking

2024-05-03 22:34 UTC, caybro requested changes
Aha, got it now :) This change results in your other bug report here: https://github.com/status-im/status-desktop/issues/14605

2024-05-06 14:21 UTC, jrainville commented
Hmm, I'm not sure what we should do then. The Ethereum emoji doesn't work with the normal Twemoji function. Can I let you guys from the UI team handle it @noeliaSD @caybro ?

2024-05-09 09:35 UTC, closed without merging

2024-05-09 09:35 UTC, caybro commented
> Hmm, I'm not sure what we should do then. The Ethereum emoji doesn't work with the normal Twemoji function. Can I let you guys from the UI team handle it @noeliaSD @caybro ?

I'll try fix the issue in a different way :)