fix(ProfileDescriptionPanel): Profile settings -> Identity : Addition of validation to bio field
status-im/status-desktop pull request #14772
Opened 2024-05-15 13:40 UTC by Seitseman

fixes #13623

### What does the PR do

- Added validator to the bio component to allow only ascii and emoji characters
- Added ProfileDescriptionPanelPage to a storybook

### Affected areas
Profile->views: ProfileDescriptionPanel, MyProfileView

![image](https://github.com/status-im/status-desktop/assets/5157464/41d1a464-b3c3-4152-ab3b-8469943b5f83)

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

https://github.com/status-im/status-desktop/assets/5157464/397939d2-4f29-4ff4-99ec-90c747ac2502

2024-05-15 13:46 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f58aab67 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14772/1/) | 2024-05-15 13:46:49 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14772/1//consoleText) |

2024-05-16 08:42 UTC, caybro commented on storybook/pages/ProfileDescriptionPanelPage.qml
> +                id: emptyModelChecker
?

2024-05-16 08:42 UTC, caybro commented on storybook/pages/ProfileDescriptionPanelPage.qml
> +                    displayName.validators: isEnsName ? [] : Constants.validators.displayName
I wonder why you have to change the behavior here in SB?

2024-05-16 20:29 UTC, alexjba reviewed
Sorry about this, the task description wasn't properly updated.
Please have a look at these comments.

2024-05-16 20:29 UTC, alexjba commented on ui/imports/utils/Constants.qml
> +        readonly property var asciiWithEmoji: /^(?:(?:[\x00-\x7F])|(?:\ud83c\udff4(?:\udb40[\udc61-\udc7a])+\udb40\udc7f|(?:\ud83c[\udde6-\uddff]){2}|(?:[\#\*0-9]\ufe0f?\u20e3)|(?:\u00a9|\u00ae|[\u20
We'll need to keep it inline with mobile regex to make sure we don't have any mismatches between platforms.

Please have a look at this regex used on mobile:
https://github.com/status-im/status-mobile/pull/19562/files#diff-9e385a06538a147df92716d390b2b37d2a07d495b3733f1f16439251b6d9dc6dR14

Please add a comment about keeping this regex inline.

cc @mohsen-ghafouri

2024-05-16 20:29 UTC, alexjba commented on ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
> +                    errorMessage: qsTr("Only letters, numbers, ASCII characters or emojis allowed")
The error message has been updated in Figma to remove the ASCII reference.
https://www.figma.com/design/ibJOTPlNtIxESwS96vJb06/👤-Profile-|-Desktop?node-id=2460-8755&t=7EUM0YB7om3UmscW-0

2024-05-17 19:02 UTC, micieslak requested changes
Hey, some comments/questions there :)

The sb page generates warnings:
```
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot call method 'validate' of null
file:///home/michalc/workspace/status-desktop/storybook/pages/ProfileDescriptionPanelPage.qml:20:1: QML ProfileDescriptionPanelPage: Binding loop detected for property "globalUtils"
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
```
Additionally, it's kind of rule that single page tests single component on top level, there are two: `ProfileHeader` and `ProfileDescriptionPanel`

2024-05-17 20:31 UTC, Seitseman commented
> Hey, some comments/questions there :)
> 
> The sb page generates warnings:
> 
> ```
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot call method 'validate' of null
> file:///home/michalc/workspace/status-desktop/storybook/pages/ProfileDescriptionPanelPage.qml:20:1: QML ProfileDescriptionPanelPage: Binding loop detected for property "globalUtils"
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Controls/StatusInput.qml:285: TypeError: Cannot read property 'validate' of null
> file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
> file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
> file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
> file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:37: TypeError: Cannot read property 'isCompressedPubKey' of null
> ```
> 
> Additionally, it's kind of rule that single page tests single component on top level, there are two: `ProfileHeader` and `ProfileDescriptionPanel`

Those warnings are generated because some of the validators of the component use ```globalUtilsInst``` . It looks like other storybook pages have similar problems. Fix might be out of the scope of this task.

2024-05-20 08:56 UTC, micieslak reviewed
LGTM in general, some small notes only.

Moreover, the added page doesn't work properly right now:

![Screenshot from 2024-05-20 10-50-29](https://github.com/status-im/status-desktop/assets/20650004/67c648f7-bf3e-49cf-9dd6-fb25bf1fb3e0)

It can be relatively easily fixed by mocking this `isAlias` method. Look e.g. for `MembersDropdownPage` where similar mocking is done. The long term solution is to remove access to backend from singletons, but for now workaround is fine. However the newly added page itself should work without errors/warnings imo.

2024-05-20 12:13 UTC, micieslak approved these changes
Nice!

2024-05-20 15:41 UTC, caybro approved these changes
LGTM :+1:

2024-05-20 21:13 UTC, merged