14879 error message is misleading when pasting bio longer than 240 chars
status-im/status-desktop pull request #14881
Opened 2024-05-22 10:59 UTC by Seitseman

### What does the PR do

In ProfileDescriptionPanel.qml in bioInput component separated charLimit and input.maximumLength, so StatusInput was left intact. This made bio input to behave on desktop similarly to mobile clients

### Affected areas

ProfileDescriptionPanel.qml 

### Screenshot of functionality (including design for comparison)

https://github.com/status-im/status-desktop/assets/5157464/8d7b8939-0955-4a73-8620-d13cd060737e

2024-05-22 11:05 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1bd8a631 | [#2](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14881/2/) | 2024-05-22 11:05:42 | ~4 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-14881/2//consoleText) |

2024-05-22 15:39 UTC, caybro requested changes
Otherwise looks good!

2024-05-22 15:39 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
> +                    errorMessage: qsTr("Bio can’t be longer than %n characters", "", bioInput.charLimit)
```suggestion
                    errorMessage: qsTr("Bio can’t be longer than %n character(s)", "", bioInput.charLimit)
```

2024-05-22 15:39 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
> +            input.maximumLength : 0
It feels weird to set this to 0; I'd set it to the max value, which is according to docs and source code:
> By default, this property contains a value of 32767.

2024-05-22 15:40 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/ProfileDescriptionPanel.qml
> +                    errorMessage: qsTr("Bio can’t be longer than %n characters", "", bioInput.charLimit)
Yes, the parentheses _must_ be there (`(s)`)

2024-05-27 07:49 UTC, caybro approved these changes
LGTM

Pls don't forget to create another PR for master :)

2024-05-28 21:01 UTC, alexjba approved these changes
LGTM!

2024-05-29 11:41 UTC, caybro commented
@jrainville merge at will :)

2024-05-29 17:59 UTC, merged