fix: Improve code snippets display in chats
status-im/status-desktop pull request #15247
Opened 2024-06-19 07:15 UTC by kounkou

### What does the PR do

It is sometimes hard to read certain messages containing code snippets or block of texts, logs, etc. in Status app chat. This can be prevent a user to use Status desktop or even consider the Status app for exchanges involving a lot of code snippets or blocks of text. The following PR is an attempt to reduce friction with displaying code snippets/block of text.

Please take a look at the following example : 

**BEFORE**

![Screenshot from 2024-06-18 23-47-10](https://github.com/status-im/status-desktop/assets/2589171/b42e3c3a-cc91-46bf-85e9-b7586c31963a)

**AFTER - LIGHT**

![Screenshot from 2024-06-18 23-47-07](https://github.com/status-im/status-desktop/assets/2589171/b33ab03a-814c-48a8-bbb5-70a1d9e14b36)

**AFTER - DARK**

![Screenshot from 2024-06-19 00-07-19](https://github.com/status-im/status-desktop/assets/2589171/02c5bdbd-4e3f-4e7f-9b8a-d3c1ac0382b9)

### Affected areas

- Chat message display

2024-06-19 07:22 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 3ab95fea | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15247/1/) | 2024-06-19 07:22:52 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15247/1//consoleText) |

2024-06-19 09:59 UTC, caybro requested changes
This is not the right approach to do (in Javascript); we have a dedicated syntax C++ highlighter in `status-desktop/ui/StatusQ/src/statussyntaxhighlighter.cpp`

That said, I have no idea why it doesn't work/apply to the bridged discord messages

2024-06-19 16:17 UTC, kounkou commented
> This is not the right approach to do (in Javascript); we have a dedicated syntax C++ highlighter in `status-desktop/ui/StatusQ/src/statussyntaxhighlighter.cpp`
> 
> That said, I have no idea why it doesn't work/apply to the bridged discord messages

Ah that's good to know. 

> This is not the right approach to do (in Javascript); we have a dedicated syntax C++ highlighter in `status-desktop/ui/StatusQ/src/statussyntaxhighlighter.cpp`
> 
> That said, I have no idea why it doesn't work/apply to the bridged discord messages

Nice! Good to know, how are the highlighter activated ? In other words, do we have ```<language> selectors ?

![Screenshot from 2024-06-19 09-14-13](https://github.com/status-im/status-desktop/assets/2589171/9674c0dc-aa57-43ac-b126-4ea6ed4fe983)

I saw that we have some highlighting, but it doesn't give a `code snippet` feel, see the screenshot for instance.

But anyway, I did this on my free time. Do you want me to improve on my pr or I just drop it?

2024-06-19 16:25 UTC, caybro commented
> > This is not the right approach to do (in Javascript); we have a dedicated syntax C++ highlighter in `status-desktop/ui/StatusQ/src/statussyntaxhighlighter.cpp`
> > That said, I have no idea why it doesn't work/apply to the bridged discord messages
> 
> Ah that's good to know.
> 
> > This is not the right approach to do (in Javascript); we have a dedicated syntax C++ highlighter in `status-desktop/ui/StatusQ/src/statussyntaxhighlighter.cpp`
> > That said, I have no idea why it doesn't work/apply to the bridged discord messages
> 
> Nice! Good to know, how are the highlighter activated ? In other words, do we have ``` selectors ?
> 
> ![Screenshot from 2024-06-19 09-14-13](https://private-user-images.githubusercontent.com/2589171/341144632-9674c0dc-aa57-43ac-b126-4ea6ed4fe983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTQ1NjAsIm5iZiI6MTcxODgxNDI2MCwicGF0aCI6Ii8yNTg5MTcxLzM0MTE0NDYzMi05Njc0YzBkYy1hYTU3LTQzYWMtYjEyNi00ZWE2ZWQ0ZmU5ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTYyNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNhNTI3ZTRmMWQ1NjE5ZjFjYmEwYzcxZWVlNWVhNDEwYjFlNDQyNDg5MzQ3MWU3ZTMxMmZmYzU5NmExM2ZjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GqyKTTG68b2q6sIUzqUZ48c1w9O1KXblXGkhAof025A)
> 
> I saw that we have some highlighting, but it doesn't give a `code snippet` feel, see the screenshot for instance.
> 
> But anyway, I did this on my free time. Do you want me to improve on my pr or I just drop it?

It's based on this class in Qt: https://doc.qt.io/qt-5/qsyntaxhighlighter.html

And I don't think we should combine the 2 approaches together, wdyt @alexjba ?

2024-06-19 17:36 UTC, alexjba commented
That's a really nice output 😮 I don't think it will be difficult to move your code to c++ as @caybro mentioned. 90% of the work is to create the regex anyways and that's done already 👍

2024-06-19 18:06 UTC, kounkou commented
> That's a really nice output 😮 I don't think it will be difficult to move your code to c++ as @caybro mentioned. 90% of the work is to create the regex anyways and that's done already 👍

Nice! I can still continue on my spare time then.
I'll involve Design as well here... I think we also need a floating `copy button` somewhere or something like that?

2024-06-19 18:41 UTC, alexjba commented
BTW, there are nice open source highlighters for code. Maybe we could integrate one
E.g https://github.com/Waqar144/QSourceHighlite

2026-04-14 05:41 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 64242998 | [62](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-15247/62/) | 2026-04-14 05:41:16 | ~22 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260414-051913-642429-pr15247-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260414-051913-642429-pr15247-arm64.apk&size=400x400&errorCorrectionLevel=L)|

2026-04-14 13:10 UTC, micieslak commented
Closing as the regex-based highlighting is planned to be dropped. However the idea of using some 3rd party highlighter is nice and will be investigated.

2026-04-14 13:10 UTC, closed without merging