chore(Wallet.RootStore): Moved backend independent methods0 to a stat…
status-im/status-desktop pull request #15288
Opened 2024-06-20 21:14 UTC by Seitseman

…eless WalletUtils singleton

fixes: #14804

2024-06-20 21:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5f36a24d | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15288/1/) | 2024-06-20 21:21:05 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15288/1//consoleText) |

2024-06-26 15:13 UTC, caybro requested changes

2024-06-26 15:13 UTC, caybro commented on ui/app/AppLayouts/Profile/stores/WalletStore.qml
> +    function processPreferredSharingNetworkToggle(preferredSharingNetworks, toggledNetwork) {
Why is this added here? I thought we wouldn't add new stuff to a store (moreover so when it's a singleton)

2024-06-26 15:13 UTC, caybro commented on ui/app/AppLayouts/Wallet/WalletUtils.qml
> +                const item = SQUtils.ModelUtils.get(model, i)
This can't work under `SQUtils`, you imported it as `import StatusQ.Core.Utils 0.1 as StatusQUtils` on the top

2024-06-26 15:13 UTC, caybro commented on ui/app/AppLayouts/Wallet/WalletUtils.qml
> +        let res = root.lookupAddressObject(tx.sender)
Where is this `lookupAddressObject` coming from?

2024-06-26 15:13 UTC, caybro commented on ui/app/AppLayouts/Wallet/WalletUtils.qml
> +        if (!res || res.type !== RootStore.LookupType.Account || res.object.walletType == Constants.watchWalletType)
This enum (`RootStore.LookupType.Account`) is coming from the `RootStore`, makes no sense here

2024-06-26 15:13 UTC, caybro commented on ui/app/AppLayouts/Wallet/WalletUtils.qml
> +        let res = root.lookupAddressObject(tx.sender)
There's not even a `root` here

2024-06-27 12:35 UTC, noeliaSD commented
We will postpone this task integration to **master** until the stability phase, when the **2.30** branch is already created, to reduce regressions on the release.

2024-07-01 07:06 UTC, alexjba reviewed
I think this is a good candidate for the full e2e suite once the comments from @caybro are solved.

2026-06-10 14:38 UTC, closed without merging