feat(dapps) enable Wallet Connect feature flag
status-im/status-desktop pull request #15791
Opened 2024-07-25 07:41 UTC by stefandunca

### Closes: #15673

Enable Wallet Connect support for dApps

### Affected areas

dApps functionality

### How to test

- Execute all available Wallet Connect test cases

### Risk 

- [x] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

### Cool Spaceship Picture

<img src="https://github.com/user-attachments/assets/a1116edf-6861-4ea1-941c-d884c8751188" height="100">

2024-07-25 07:49 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e350cb7a | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15791/1/) | 2024-07-25 07:49:03 | ~7 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15791/1//consoleText) |

2024-07-25 07:58 UTC, clauxx commented
Great! But beware that it shouldn't be closed just yet till we fix all important issues for wallet connect.

2024-07-25 07:59 UTC, clauxx requested changes
Leaving a request for changes so it's not merged by mistake.

2024-07-26 06:48 UTC, kounkou approved these changes

2024-07-26 06:54 UTC, alexjba approved these changes
Yeeey! Awesome work @stefandunca ! Glad to see it enabled!

2024-07-26 09:29 UTC, clauxx approved these changes

2024-07-26 12:18 UTC, caybro commented
Since we already have a `2.30` branch, this should also be backported

2025-01-22 14:58 UTC, closed without merging