fix(wallet): Constrain token name size to send modal width
status-im/status-desktop pull request #15859
Opened 2024-07-29 12:56 UTC by Cuteivist

Fixes #15576 

### What does the PR do

Update send amount input layouts to properly resize with different token name lengths

### Affected areas

Send modal amount input

### Screenshot of functionality (including design for comparison)

https://github.com/user-attachments/assets/d4b3db66-c40f-4870-ab0d-31a87be8b34c

2024-07-29 12:59 UTC, caybro requested changes
That doesn't look correct; once you've selected the "too long" token, the Max button is no longer visible (as it should be)

2024-07-29 13:04 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8c91d5ab | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15859/1/) | 2024-07-29 13:04:29 | ~7 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15859/1//consoleText) |

2024-07-29 13:11 UTC, caybro commented
> That doesn't look correct; once you've selected the "too long" token, the Max button is no longer visible (as it should be)

Ah, it's a collectible :facepalm:

2024-07-29 13:11 UTC, caybro approved these changes

2024-07-30 07:25 UTC, saledjenic approved these changes

2024-07-31 04:53 UTC, merged