fix(wallet): Disable adding new watch-only accounts
status-im/status-desktop pull request #15944
Opened 2024-08-01 00:41 UTC by belalshehab

### What does the PR do

- Temporarily removes the ability for users to add new watch-only accounts until issue #15892 is resolved.

closes: #15933 

### Affected areas

- Wallet -> addAccount

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/25a8e231-6f46-4b0f-8a26-4f199f729ccb">

### Impact on end user

User will not be able to add new watch only accounts

### Risk 

Tick **one**:
- [ ] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

2024-08-01 00:47 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4751a12a | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15944/1/) | 2024-08-01 00:47:56 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-15944/1//consoleText) |

2024-08-01 06:37 UTC, saledjenic approved these changes
@belalshehab please remove this "Temporarily removes the ability for users to add new watch-only accounts until..." from the description, cause that's incorrect. We don't disable adding watch-only accounts because of that, but because of app performances and issues we have with adding accounts with big history (a lot of transactions) and in some cases such accounts lock the db.

2024-08-01 06:37 UTC, saledjenic commented on ui/imports/shared/popups/addaccount/states/Main.qml
> +                    expression: model.keyPair.keyUid !== "LABEL-OPTION-ADD-WATCH-ONLY-ACC"
Please use `Constants.appTranslatableConstants.addAccountLabelOptionAddWatchOnlyAcc` instead.

2024-08-01 08:08 UTC, caybro commented on ui/imports/shared/popups/addaccount/states/Main.qml
> +        readonly property SortFilterProxyModel originModelWtihoutWatchOnlyAcc: SortFilterProxyModel {
```suggestion
        readonly property SortFilterProxyModel originModelWithoutWatchOnlyAcc: SortFilterProxyModel {
```

2024-08-01 08:08 UTC, caybro commented on ui/imports/shared/popups/addaccount/states/Main.qml
> +                originModel: root.store.editMode? [] : d.originModelWtihoutWatchOnlyAcc
```suggestion
                originModel: root.store.editMode? [] : d.originModelWithoutWatchOnlyAcc
```

2024-08-01 11:48 UTC, caybro requested changes
So... it was decided that this is only a temporary measure; why is this going to `master` and not just to the release branch?

2024-08-02 07:35 UTC, saledjenic commented
Well, all we have in the release should be in the master branch as well, what if we don't manage to sort that out for 2.31, and need to cut the branch from the master again and it will be with watch-only accounts enabled again. 

Unrelated, this is so small, two lines change, so no reason to not have it, but even if it's a much bigger change, we can always revert.

2024-08-02 09:00 UTC, merged