remove some dependencies from PinnedMessagePopup
status-im/status-desktop pull request #16435
Opened 2024-10-01 15:23 UTC by iurimatias

### What does the PR do

Removes some of the dependencies on the store on PinnedMessagePopup, however some still remains because it requires refactoring the MessageView component.

### Affected areas

Pinned Messages

### Impact on end user

Functionality should stay the same

### How to test

On Group Chats:
- Pin a message
- View Pinned Messages
- Jump to messages
- Unpin messages

### Risk 

Might affect community pinned messages also

2024-10-01 15:30 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 985f4820 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16435/1/) | 2024-10-01 15:30:19 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16435/1//consoleText) |

2024-10-01 15:31 UTC, jrainville approved these changes

2024-10-01 15:34 UTC, caybro approved these changes
LGTM

Modulo the typo (I know this is existing code though)

2024-10-01 15:34 UTC, caybro commented on ui/app/AppLayouts/Chat/popups/PinnedMessagesPopup.qml
> +    readonly property bool isPinActionAvaliable: true
```suggestion
    readonly property bool isPinActionAvailable: true
```

2024-10-01 15:34 UTC, caybro commented on ui/app/mainui/Popups.qml
> +            isPinActionAvaliable: store && store.oneToOneChatContact ? store.oneToOneChatContact.isContact : true
```suggestion
            isPinActionAvailable: store && store.oneToOneChatContact ? store.oneToOneChatContact.isContact : true
```

2024-10-02 11:53 UTC, micieslak requested changes
Is the storybook working for you? It looks like that for me:

![image](https://github.com/user-attachments/assets/d2806bf9-c60b-45d4-8d50-012388f3a842)

No content and many warning in logs.

2024-10-02 13:01 UTC, micieslak reviewed
The SB page seems to be kind of work in progress, many things are broken here and need adjustments.

After quick investigation I manged to display some content:

![Screenshot from 2024-10-02 14-56-17](https://github.com/user-attachments/assets/2a369ea5-e475-4eb2-861e-44a082f2a096)

However there is still a lot of work to do to adjust everything correctly.

2026-06-18 19:09 UTC, jrainville commented
@micieslak can you review again, I revived this old PR when I saw it only had a small conflict.

I also fixed the storybook page, it now works as expected:

[fixed-storybook-page.webm](https://github.com/user-attachments/assets/af85c5ac-26a5-4a3d-bd88-881454e67cf4)

The only thing is it has a lot of warnings still , but those warning also exist in 2.38 and master. They are because we don't pass contentModule and emojiPopup.

The app's popup works too as expected:

<img width="926" height="550" alt="image" src="https://github.com/user-attachments/assets/82ed0eb2-f9b4-4dff-bd51-1243b364275e" />

2026-06-18 19:22 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (40)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1fbf855f | [5](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16435/5/) | 2026-06-18 19:22:26 | ~9 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16435/5//consoleText) |
| :heavy_check_mark: | 1fbf855f | [2](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/2/) | 2026-06-18 19:23:43 | ~10 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260618-191306-1fbf85-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260618-191306-1fbf85-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | 1fbf855f | [5](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/tests-ui/job/PR-16435/5/) | 2026-06-18 19:26:52 | ~13 min | `tests/ui` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/tests-ui/job/PR-16435/5//consoleText) |
| :heavy_check_mark: | 1fbf855f | [2](https://ci.status.im/job/status-app/job/prs/job/ios/job/aarch64/job/package/job/PR-16435/2/) | 2026-06-18 19:27:19 | ~14 min | `ios/aarch64` | [:iphone:`ipa`](https://i.diawi.com/Yxrz7N) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fi.diawi.com%2FYxrz7N&size=400x400&errorCorrectionLevel=L)|
| :heavy_multiplication_x: | 1fbf855f | [4124](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4124/) | 2026-06-18 19:29:52 | ~5 min | `tests/e2e-android` | [:package:`pkg`](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4124/testReport/) |
| :heavy_check_mark: | 1fbf855f | [5](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/package/job/PR-16435/5/) | 2026-06-18 19:31:39 | ~18 min | `linux/x86_64` | [:package:`tgz`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260618-191316-1fbf85-pr16435-x86_64.tar.gz) |
| :heavy_check_mark: | 1fbf855f | [2](https://ci.status.im/job/status-app/job/prs/job/linux/job/x86_64/job/package-flatpak/job/PR-16435/2/) | 2026-06-18 19:32:54 | ~19 min | `linux-flatpak/x86_64` | [:package:`fla`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260618-191313-1fbf85-pr16435-x86_64.flatpak) |
| :heavy_check_mark: | 1fbf855f | [5](https://ci.status.im/job/status-app/job/prs/job/macos/job/aarch64/job/package/job/PR-16435/5/) | 2026-06-18 19:33:58 | ~20 min | `macos/aarch64` | [:apple:`dmg`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260618-191331-1fbf85-pr16435-aarch64.dmg) |
| :heavy_check_mark: | 1fbf855f | [11862](https://ci.status.im/job/status-app/job/e2e/job/prs/11862/) | 2026-06-18 19:47:48 | ~16 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/e2e/job/prs/11862/allure/) |
| :heavy_check_mark: | 1fbf855f | [5](https://ci.status.im/job/status-app/job/prs/job/windows/job/x86_64/job/package/job/PR-16435/5/) | 2026-06-18 19:48:00 | ~34 min | `windows/x86_64` | [:cd:`exe`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260618-191332-1fbf85-pr16435-x86_64.exe) |
| :heavy_check_mark: | 1fbf855f | [3763](https://ci.status.im/job/status-app/job/e2e/job/prs-windows/3763/) | 2026-06-18 20:07:25 | ~19 min | `tests/e2e-windows` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/e2e/job/prs-windows/3763/allure/) |
| :heavy_multiplication_x: | 1fbf855f | [4356](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4356/) | 2026-06-26 08:43:32 | ~2 hr 57 min | `tests/e2e-android` | [:package:`pkg`](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4356/testReport/) |
| :heavy_multiplication_x: | 1fbf855f | [4581](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4581/) | 2026-07-03 05:58:08 | ~11 min | `tests/e2e-android` | [:package:`pkg`](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4581/testReport/) |
| :heavy_multiplication_x: | 1fbf855f | [4667](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4667/) | 2026-07-07 08:39:17 | ~2 hr 44 min | `tests/e2e-android` | [:package:`pkg`](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4667/testReport/) |
| :heavy_multiplication_x: | 1fbf855f | [4712](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4712/) | 2026-07-08 10:38:08 | ~4 hr 37 min | `tests/e2e-android` | [:package:`pkg`](https://ci.status.im/job/status-app/job/e2e/job/prs-android/4712/testReport/) |
| | | | | | | |
| :heavy_check_mark: | 79069897 | [3](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/3/) | 2026-06-20 05:42:32 | ~23 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260620-051914-790698-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260620-051914-790698-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| | | | | | | |
| :heavy_check_mark: | 36ce8acf | [4](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/4/) | 2026-06-23 05:43:37 | ~24 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260623-051912-36ce8a-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260623-051912-36ce8a-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| | | | | | | |
| :heavy_check_mark: | e8bc219c | [5](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/5/) | 2026-06-24 05:42:46 | ~23 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260624-051912-e8bc21-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260624-051912-e8bc21-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| | | | | | | |
| :heavy_check_mark: | 2e47cbe9 | [6](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/6/) | 2026-06-25 05:44:58 | ~25 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260625-051955-2e47cb-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260625-051955-2e47cb-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| | | | | | | |
| :heavy_check_mark: | cd915a51 | [7](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/7/) | 2026-06-26 05:45:50 | ~26 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260626-051921-cd915a-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop-260626-051921-cd915a-pr16435-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| | | | | | | |
| :heavy_check_mark: | cc889fea | [8](https://ci.status.im/job/status-app/job/prs/job/android/job/arm64/job/package/job/PR-16435/8/) | 2026-06-27 05:46:56 | ~27 min | `android/arm64` | [:robot:`apk`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-260627-051916-cc889f-pr16435-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-im-desktop-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Desktop [...]

2026-07-08 22:50 UTC, micieslak approved these changes
Nice!

2026-07-09 08:57 UTC, caybro approved these changes
Cool, just 2 minor things

2026-07-09 08:57 UTC, caybro commented on ui/app/mainui/Popups.qml
> +                onJumpToMessageRequested: messageStore.messageModule.jumpToMessage(messageId)
These will probably complain about the missing paraam:
```qml
onPinMessageRequested: messageId => messageStore.pinMessage(messageId)
...
```

2026-07-09 08:57 UTC, caybro commented on storybook/pages/PinnedMessagesPopupPage.qml
> +import AppLayouts.Chat.stores 1.0
Drop the version numbers

2026-07-09 18:17 UTC, merged