fix: Remove forced OpenGl context sharing
status-im/status-desktop pull request #16443
Opened 2024-10-02 13:05 UTC by alexjba

### What does the PR do

closes #16391

Remove the forced openGL context sharing. This will be done in the QtWebView::initialise by Qt if possible, depending on platform.

### Affected areas

WebEngineView
WalletConnect

### Architecture compliance

- [ x I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

2024-10-02 13:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | c3057df8 | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16443/1/) | 2024-10-02 13:11:54 | ~6 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16443/1//consoleText) |

2024-10-02 14:08 UTC, alexjba commented
@yakimant Added the fixes for WebEngineView for both qt 5.15.2 and 5.15.8. Found a more granular option to disable a specific sandbox feature on chromium on 5.15.2. I think it's quite ok for our usage.

For 5.15.8 I've updated the code to fix the race condition.

https://chromium.googlesource.com/chromium/src/+/0e94f26e8/docs/linux_sandboxing.md#the-sandbox-1

2024-10-02 14:12 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/prs/windows/x86_64/package/PR-16443#3](https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-16443/3/) :small_blue_diamond: ~20 min :small_blue_diamond: d1aa7278 :small_blue_diamond: [:package: windows/x86_64 package](https://status-im-desktop-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-241002-135212-d1aa72-pr16443-x86_64.exe)

2024-10-03 06:34 UTC, alexjba commented
@micieslak Could you please have a look to see if webviews are working now in Storybook as well?

2024-10-03 09:11 UTC, caybro approved these changes

2024-10-03 11:04 UTC, alexjba commented
Ohh..Looks like we've had qml tests on `WebEngineLoader`. Just that it was disabled on linux because the page doesn't load.

https://github.com/status-im/status-desktop/blob/master/ui/StatusQ/tests/TestComponents/tst_WebEngineLoader.qml#L75C1-L77C10

2024-10-03 11:39 UTC, caybro commented
> Ohh..Looks like we've had qml tests on `WebEngineLoader`. Just that it was disabled on linux because the page doesn't load.
> 
> https://github.com/status-im/status-desktop/blob/master/ui/StatusQ/tests/TestComponents/tst_WebEngineLoader.qml#L75C1-L77C10

I'd uncomment it temporarily here to see what happens

2024-10-03 11:57 UTC, alexjba commented
> > Ohh..Looks like we've had qml tests on `WebEngineLoader`. Just that it was disabled on linux because the page doesn't load.
> > https://github.com/status-im/status-desktop/blob/master/ui/StatusQ/tests/TestComponents/tst_WebEngineLoader.qml#L75C1-L77C10
> 
> I'd uncomment it temporarily here to see what happens

yes, I'll enable the tests. I'll probably need to update the Makefile as well to pass the chromium flag to ctest.

2024-10-04 15:38 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/prs/windows/x86_64/package/PR-16443#4](https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-16443/4/) :small_blue_diamond: ~25 min :small_blue_diamond: ce9e25b8 :small_blue_diamond: [:package: windows/x86_64 package](https://status-im-desktop-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-241004-151252-ce9e25-pr16443-x86_64.exe)

2024-10-04 18:11 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/prs/windows/x86_64/package/PR-16443#5](https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-16443/5/) :small_blue_diamond: ~22 min :small_blue_diamond: 89bf229f :small_blue_diamond: [:package: windows/x86_64 package](https://status-im-desktop-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-241004-174951-89bf22-pr16443-x86_64.exe)

2024-10-04 18:15 UTC, alexjba commented
Webengine tests enabled and fixed.

2024-10-07 06:47 UTC, alexjba commented
@yakimant Please have a look on this PR when you'll get the chance. It will affect your current work on the nix shell.

There are 2 points here:
1. Fixing webviews for qt 5.15.8 without disabling the GPU. I'm avoid deadlocks by initialising the webEngineView in a different order in the code. In the nix shell PR we won't need to set custom `export QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu"` flag.
2. Adding the necessary flags for the qt 5.15.2 webviews to work. When merging your nix shell PR we can revert these flags `QTWEBENGINE_CHROMIUM_FLAGS="--disable-seccomp-filter-sandbox"` (assuming we're decommissioning the old linux builds)

2024-10-07 09:59 UTC, yakimant requested changes
Left comments in the code.

But also curious, why non-nix build with qt 5.15.2 worked with dapps var set.

2024-10-07 09:59 UTC, yakimant commented on storybook/main.cpp
> +    qputenv("QTWEBENGINE_CHROMIUM_FLAGS", QByteArrayLiteral("--disable-seccomp-filter-sandbox"));
Can we add to flags, not to rewrite them?
It can be set already.

2024-10-07 09:59 UTC, yakimant commented on Makefile
> +run-statusq-tests: export QTWEBENGINE_CHROMIUM_FLAGS="--disable-seccomp-filter-sandbox"
Would be great to add a flag instead of rewriting the flags if set already.

2024-10-07 09:59 UTC, yakimant commented on AppRun
> +export QTWEBENGINE_CHROMIUM_FLAGS="--disable-seccomp-filter-sandbox"
Same, adding is better than rewriting.

2024-10-09 09:36 UTC, alexjba commented
> Left comments in the code.
> 
> But also curious, why non-nix build with qt 5.15.2 worked with dapps var set.

Please have another look.

It works because `--disable-seccomp-filter-sandbox` is a workaround for this issue https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468

2024-10-09 09:58 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/prs/windows/x86_64/package/PR-16443#6](https://ci.status.im/job/status-desktop/job/prs/job/windows/job/x86_64/job/package/job/PR-16443/6/) :small_blue_diamond: ~24 min :small_blue_diamond: 4ec89cf6 :small_blue_diamond: [:package: windows/x86_64 package](https://status-im-desktop-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-241009-093436-4ec89c-pr16443-x86_64.exe)

2024-10-10 07:29 UTC, merged