feat: Transaction deep link sharing
status-im/status-desktop pull request #16543
Opened 2024-10-17 11:03 UTC by Cuteivist

Task https://github.com/status-im/status-desktop/issues/16412

User stories: https://www.notion.so/Transaction-deep-link-10d8f96fb65c803c85fed5f4440ad439

Status-go : https://github.com/status-im/status-go/pull/5959

### What does the PR do

* Added ShareButton
* Added logic to call generation and parsing of transaction deep link
* Added logic to handle transaction deep link in chat
* Added logic to open send or swap modals with data passed in the link
* Added feature flag, disabled by default

NOTE that design is still in progress

### Affected areas

Chat 
Wallet

### Architecture compliance

- [X] I am familiar with the application architecture and agreed good practices.
My PR is consistent with this document: [Status Desktop Architecture Guide](https://github.com/status-im/status-desktop/blob/master/CONTRIBUTING.md)

### Screenshot of functionality (including design for comparison)

https://github.com/user-attachments/assets/32b128bc-0d07-4c39-a23d-7022baac3168

### Impact on end user

What is the impact of these changes on the end user (before/after behaviour)

### How to test

- How should one proceed with testing this PR.

It would be best to follow testing through same code with included unfurling here https://github.com/status-im/status-desktop/pull/16541

Otherwise checkout to this branch https://github.com/status-im/status-go/pull/5959 on status-go and set env variable `FLAG_TRANSACTION_DEEP_LINK_ENABLED` to "1"

- What kind of user flows should be checked?

Send modal and swap modal generating the link.
Pasting the link into the chat.

### Risk 

Described potential risks and worst case scenarios.

Tick **one**:
- [X] Low risk: 2 devs MUST perform testing as specified above and attach their results as comments to this PR **before** merging.
- [ ] High risk: QA team MUST perform additional testing in the specified affected areas **before** merging.

2024-10-17 11:10 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | aefe804d | [#1](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16543/1/) | 2024-10-17 11:10:33 | ~7 min | `tests/nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/prs/job/linux/job/x86_64/job/tests-nim/job/PR-16543/1//consoleText) |

2024-10-17 12:00 UTC, caybro reviewed
Overall code LGTM however:

- missing some QML tests for this new feature; at least the new ShareButton and tst_SwapModal
- some of the QML components have a SB page, those could use some updates

2024-10-21 13:10 UTC, caybro approved these changes

2024-10-29 08:21 UTC, alexjba approved these changes
LGTM!

2024-11-05 13:13 UTC, micieslak commented
@Cuteivist please wait a bit with merging, review in progress.

2024-11-05 15:13 UTC, micieslak requested changes
LGTM in general

I have some doubts related to architecture - mainly caused by already existing problems. We need to think how to address it in a way leaving the codebase in a possibly better shape.

2024-11-05 15:13 UTC, micieslak commented on vendor/SortFilterProxyModel
what is this change?

2025-01-29 06:10 UTC, closed without merging