uiux(StatusChatInput): highlight matching formatting option
status-im/status-desktop pull request #1968
Opened 2021-03-03 15:41 UTC by PascalPrecht

This will highlight any option in the text formatting menu whose
formatting matches the selected text formatting

Closes #1931

2021-03-03 15:51 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 3809c7db | [#1](https://ci.status.im/job/status-desktop/job/macos/job/PR-1968/1/) | 2021-03-03 15:51:54 | ~10 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-210303-154134-3809c7-pr.dmg) |

2021-03-03 16:12 UTC, jrainville approved these changes

2021-03-03 18:50 UTC, iurimatias requested changes
https://user-images.githubusercontent.com/176720/109856338-62515c00-7c27-11eb-8baf-91f7790919e7.mov

doesn't work for me, see video

2021-03-03 20:12 UTC, PascalPrecht commented
> doesn't work for me, see video

You need to select the text including the markers

2021-03-04 13:57 UTC, iurimatias commented
opened #1974 to address the other issue

2021-03-04 13:57 UTC, merged