fix: fix settings not being refetched when they had been edited before
status-im/status-desktop pull request #2093
Opened 2021-03-22 20:19 UTC by jrainville

We used to set the settings as dirty only when the `saveSettings` failed, so that meant that in a best case scenario, the settings would **never** be set as dirty.

Dirty means that out local cache needs to be updated when fetching a new setting.

Apart from that, I also made the asset fetch more performant and also removed the useless parameters

2021-03-22 20:28 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 9aba4167 | [#1](https://ci.status.im/job/status-desktop/job/macos/job/PR-2093/1/) | 2021-03-22 20:28:32 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-210322-201945-9aba41-pr.dmg) |

2021-03-23 04:04 UTC, michaelsbradleyjr requested changes
Very nice! I have just a few suggestions and a question / change-request below.

It's late, I'm reviewing after a very long day, so there may be some mistakes/misunderstandings on my part. 😄

2021-03-23 04:04 UTC, michaelsbradleyjr commented on src/status/libstatus/tokens.nim
> +  result = convertStringSeqToERC20ContractSeq(visibleTokenList)
```suggestion
  convertStringSeqToERC20ContractSeq(visibleTokenList) 
```

2021-03-23 04:04 UTC, michaelsbradleyjr commented on src/status/libstatus/tokens.nim
> +  result = convertStringSeqToERC20ContractSeq(visibleTokenList)
```suggestion
  convertStringSeqToERC20ContractSeq(visibleTokenList)
```

2021-03-23 04:04 UTC, michaelsbradleyjr commented on src/status/wallet.nim
> +  self.tokens = visibleTokenList
```suggestion
  self.tokens = status_tokens.toggleAsset(symbol)
```

2021-03-23 14:04 UTC, jrainville commented
@michaelsbradleyjr I updated with your changes. You were right, I had missed the part where we only set settings when not keeping sensitive data

2021-03-23 20:27 UTC, michaelsbradleyjr approved these changes

2021-03-24 16:44 UTC, richard-ramos approved these changes

2021-03-24 17:06 UTC, merged