fix: order joined communities from newest to oldest
status-im/status-desktop pull request #2198
Opened 2021-04-07 18:03 UTC by jrainville

Fixes #2154

The communities api doesn't return the date of joining or creation, but it always returns them in order of oldest to newest, so it was only a matter of inverting the display order.

Later, we can implement drag and drop and save that order, hopefully in the DB

2021-04-07 18:12 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | c864eace | [#1](https://ci.status.im/job/status-desktop/job/macos/job/PR-2198/1/) | 2021-04-07 18:11:59 | ~7 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-210407-180359-c864ea-pr.dmg) |

2021-04-08 20:04 UTC, richard-ramos approved these changes

2021-04-13 18:53 UTC, iurimatias requested changes
the public chats icon still remains on top, it should be on the bottom

2021-04-13 19:52 UTC, jrainville commented
> the public chats icon still remains on top, it should be on the bottom

@iurimatias Done

2021-04-13 22:01 UTC, iurimatias approved these changes

2021-04-13 22:02 UTC, merged