fix(Profile): ensure profile popup has window
status-im/status-desktop pull request #2220
Opened 2021-04-12 11:45 UTC by PascalPrecht

When the profile popup is opened inside the contacts list, it doesn't have
a surrounding window context (`Popup` types should usually be used within `ApplicationWindow`
or `Window` components as per https://doc.qt.io/qt-5/qml-qtquick-controls2-popup.html).

This is problematic when popup are nested, like it's the case with the
nickname popup that will be instantiated by the profile popup.
With no window context, such nested popup can't be opened by the application.

This commit ensures the profile popup is created with a proper context,
fixing the issue that the nickname popup won't open when visting via
contacts list.

Fixes #2216

2021-04-12 11:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 156c7e5b | [#1](https://ci.status.im/job/status-desktop/job/macos/job/PR-2220/1/) | 2021-04-12 11:53:35 | ~7 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-210412-114551-156c7e-pr.dmg) |

2021-04-12 13:34 UTC, jrainville requested changes
Looks good. I asked for changes just so this doesn't get merged until the `destroy` is there so that we don't "leak" memory

2021-04-12 13:34 UTC, jrainville commented on ui/app/AppLayouts/Profile/Sections/Contacts/ContactList.qml
> +        id: profilePopup
You need to add a `destroy()` call `onClosed` since you create a new object instance each time.

2021-04-14 16:40 UTC, iurimatias approved these changes

2021-04-14 16:40 UTC, merged