fix: prevent crash on generate account wrong password
status-im/status-desktop pull request #2556
Opened 2021-05-13 06:13 UTC by emizzle

Fixes #2448.

Currently, if a wrong password is entered when generating a wallet account, the app will crash due to attempting to decode a `GeneratedAccount` from the rpc response containing only an error.

With this PR, we are detecting if an error is returned in the response, and if so, raising a `StatusGoException`. This exception is caught in the call chain, and translated in to a `StatusGoError` which is serialised and sent to the QML view, where it is parsed and displayed as an invalid password error in the input box.

refactor: remove string return values as error messages in wallet model
In the wallet model, we were passing back empty strings for no error, or an error as a string. This is not only confusing, but does not benefit from leaning on the compiler and strong types. One has to read the entire code to understand if a string result is expected to be returned when there is no error instead of implicitly being able to understand there is no return type (with `void`).

To alleviate this, wallet account creation functions that do not need to return a value have been changed to a `void` return type, and raise `StatusGoException`s if there is an error encountered. This can be caught in the call chain and used as necessary (ie to pass to QML).

refactor: move invalid password string detection to Utils
Currently, we are reading returned view model values and checking to see if they include a known string from Status Go that means there was an invalid password used. This string was placed in the codebase in multiple locations.

This PR moves the string check to a Utils function and updates all the references to use the function in Utils.

2021-05-13 06:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5c3a801d | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2556/1/) | 2021-05-13 06:21:53 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210513-061315-5c3a80-pr.dmg) |

2021-05-13 13:23 UTC, jrainville requested changes
Nice refactor.

I'm asking for changes, because I don't want this to be merged and then have the error sound play for every account generation haha

2021-05-13 13:23 UTC, jrainville commented on ui/app/AppLayouts/Wallet/components/AddAccountWithPrivateKey.qml
> +                errorSound.play();
Shouldn't the errorSound only play if there is an error?

2021-05-13 13:23 UTC, jrainville commented on ui/app/AppLayouts/Wallet/components/AddAccountWithSeed.qml
> +                errorSound.play();
Same for the sound

2021-05-13 13:23 UTC, jrainville commented on ui/app/AppLayouts/Wallet/components/GenerateAccountModal.qml
> +                errorSound.play();
Same

2021-05-14 07:47 UTC, anastasiyaig commented
so basically i've tested it successfully in terms of wallet interaction, @emizzle could you please adjust the sounds and we merge?

2021-05-14 07:49 UTC, emizzle commented
There is only a result if there is an error. This is a leftover from the "return errors as strings" issue that this PR partly refactored. IOW, a sound will not play when there is no error. This should be ok to merge as is.

2021-05-14 14:08 UTC, jrainville approved these changes

2021-05-14 14:27 UTC, merged