fix(communities): Naming validation for communities
status-im/status-desktop pull request #2782
Opened 2021-06-29 16:05 UTC by saledjenic

I sorted out some validation related stuff. There were some unused and some redundant methods. I guess that validation messages for each input will be uniform now, across these three parts (channel, channel category and community). If it's needed we may easily change text of the error messages (Utils.validateAndReturnError) which will have same pattern now.

Fixes: #2297

2021-06-29 16:16 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 095ae7bb | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2782/1/) | 2021-06-29 16:16:08 | ~10 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210629-160534-095ae7-pr2782.dmg) |

2021-06-29 18:22 UTC, jrainville requested changes
Very clean!

Requesting changes because the `replace` needs to be fixed, but it's  a minor issue

2021-06-29 18:22 UTC, jrainville commented on ui/imports/Utils.qml
> +            str = str.replace(" ", "-")
Replace only replaces the first one without using a regex
```suggestion
            str = str.replace(/ /g, "-")
```

2021-06-30 07:11 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/branches/linux/PR-2782#3](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-2782/3/) :small_blue_diamond: ~16 min :small_blue_diamond: e033d74d :small_blue_diamond: [:package: linux package](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-210630-065439-e033d7-pr2782.tar.gz)

2021-06-30 12:50 UTC, saledjenic commented
@jrainville I fixed the issue you added, you can proceed with review.

2021-06-30 13:22 UTC, jrainville approved these changes

2021-07-01 14:24 UTC, anastasiyaig commented
@saledjenic could please check why windows build is not being created here. it is something related to the changes u made?
we can merge after the windows artefact is created

2021-07-01 15:39 UTC, jakubgs commented
Okay, i see the error now:
```
-- Selecting Windows SDK version 10.0.10240.0 to target Windows 10.0.19041.
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/BuildTools/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 7/1/2021 3:38:29 PM.
    Project "C:\Users\jenkins\workspace\desktop_branches_windows_PR-2782\vendor\DOtherSide\build\CMakeFiles\3.20.5\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.10240.0 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\jenkins\workspace\desktop_branches_windows_PR-2782\vendor\DOtherSide\build\CMakeFiles\3.20.5\VCTarg
etsPath.vcxproj]
    Done Building Project "C:\Users\jenkins\workspace\desktop_branches_windows_PR-2782\vendor\DOtherSide\build\CMakeFiles\3.20.5\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\jenkins\workspace\desktop_branches_windows_PR-2782\vendor\DOtherSide\build\CMakeFiles\3.20.5\VCTargetsPath.vcxproj" (default target) (1) ->
    (_CheckWindowsSDKInstalled target) ->
      C:\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.10240.0 was not found. Install the required version of Windows SDK or change the SDK 
version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\jenkins\workspace\desktop_branches_windows_PR-2782\vendor\DOtherSide\build\CMakeFiles\3.20.5\VCTa
rgetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.61


  Exit code: 1
```
Looks like the issue is with the Windows SDK installation.

2021-07-01 16:27 UTC, jakubgs commented
We've had this issue before: https://github.com/status-im/status-desktop/pull/2469#issuecomment-830008544

2021-07-02 07:26 UTC, jakubgs commented
The error states that:
```
error MSB8036: The Windows SDK version 10.0.10240.0 was not found.
Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```
We CLEARLY install `10.0.10240.0` because that's the version that's selected in our build setup script:
https://github.com/status-im/status-desktop/blob/aa4bdaf9108340dbbf7116cd4a9b0c9aa2ea6a5e/scripts/windows_build_setup.ps1#L45-L47

So the error makes zero sense to me.

2021-07-02 08:29 UTC, jakubgs commented
I had some similar issue when I was setting this up in the first place: https://github.com/status-im/status-desktop/issues/595#issuecomment-698421422

Then I just downgrade the Visual C++ Build Tools verison. But we've been using this version for a while and it worked.

I did replace the hosts because of https://github.com/status-im/nim-waku/pull/652#issuecomment-871205562, so I had to reinstall Build Tools, but nothing should have changed about how it is installed.

2021-07-02 09:03 UTC, jakubgs commented
There's something seriously wrong with the Build Tools installation process:
```
PS C:\Users\jenkins\Downloads> . .\windows_build_setup.ps1
PS C:\Users\jenkins\Downloads> Install-VC-BuildTools
Downloading Microsoft Visual C++ Build Tools...
Installing Microsoft Visual C++ Build Tools...

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
     54       6      892       4096       0.06   6512   0 vs_BuildTools


PS C:\Users\jenkins\Downloads>
admin@windows-02 MINGW64 /c/Users/jenkins/Downloads
$ ls -l /c/BuildTools/
total 0
```

2021-07-02 09:42 UTC, jakubgs commented
I don't get it, for some reason the Build Tools executable doesn't even return help:
```
admin@WINDOWS-02 C:\Users\admin\Downloads>.\vs_BuildTools.exe --help

admin@WINDOWS-02 C:\Users\admin\Downloads>
```

2021-07-02 10:06 UTC, jakubgs commented
It looks like running the installer leaves a bunch of defunct processes laying around:

![image](https://user-images.githubusercontent.com/2212681/124258603-e3fdbb80-db2d-11eb-8ede-c13321e477d0.png)

2021-07-02 11:04 UTC, jakubgs commented
I upgraded our Windows Server image to be Windows Server 2019 Core in https://github.com/status-im/infra-ci/commit/3c04e159 and it works now.

2021-07-02 12:53 UTC, merged