fix(@desktop/wallet): app crash when signing token transaction with invalid password
status-im/status-desktop pull request #2834
Opened 2021-07-07 10:10 UTC by saledjenic

The issue was accessing non existent property after parsing received response. That caused
app crash, fixed now.

Fixes: #2623

2021-07-07 10:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 52d6189d | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2834/1/) | 2021-07-07 10:21:11 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210707-101111-52d618-pr2834.dmg) |

2021-07-07 13:53 UTC, jrainville approved these changes

2021-07-08 18:57 UTC, iurimatias requested changes
I still get a crash here, although on the normal eth transfer


```
ult="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32602,\"message\":\"invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash\"}}"
Traceback (most recent call last)
/Users/iurimatias/Projects/Status/nim-status-client/src/nim_status_client.nim(220) nim_status_client
/Users/iurimatias/Projects/Status/nim-status-client/src/nim_status_client.nim(217) mainProc
/Users/iurimatias/Projects/Status/nim-status-client/vendor/nimqml/src/nimqml/private/qapplication.nim(8) exec
/Users/iurimatias/Projects/Status/nim-status-client/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/iurimatias/Projects/Status/nim-status-client/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/iurimatias/Projects/Status/nim-status-client/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(572) onSlotCalled
/Users/iurimatias/Projects/Status/nim-status-client/src/app/wallet/views/transactions.nim(138) transactionWatchResultReceived
```

2021-07-09 07:09 UTC, anastasiyaig commented
i was not able to reproduce the crash in branch, however it is reproducible in master:

`Traceback (most recent call last)
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(220) nim_status_client
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/nim_status_client.nim(217) mainProc
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qapplication.nim(8) exec
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(572) onSlotCalled
/Users/jenkins/workspace/us-desktop_branches_macos_master/src/app/wallet/views/transactions.nim(138) transactionWatchResultReceived
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
[11751:259:0709/100018.737630:ERROR:gl_bindings_autogen_gl.cc(14644)] Trying to call glFlush without current GL context
`

2021-07-09 07:22 UTC, anastasiyaig commented
https://user-images.githubusercontent.com/82375995/125039734-7c9cba00-e09f-11eb-8663-d1cee3d17348.mov

2021-07-09 13:37 UTC, richard-ramos approved these changes

2021-07-12 21:01 UTC, iurimatias commented
I tried again and cannot replicate the crash anymore

2021-07-12 21:01 UTC, merged