feat: add basic local chat search
status-im/status-desktop pull request #2846
Opened 2021-07-07 16:05 UTC by jrainville

Fixes #2771

Adds a very basic search feature. It only searches the current channel, and only messages that were locally loaded, so it is very limited. Another limit is that it only searches the raw message, so if there is a mention, you can't search the name. This should all be improved once the search is moved to status-go. I purposefully made it simple on the Nim side, since it will move anyway.

This also includes a new BadgeContent component that is both used in the ActivityCenter and the Search. It is used to show this: 
![image](https://user-images.githubusercontent.com/11926403/124792847-636b0080-df1b-11eb-8e6c-c13d78b26651.png)

It is not currently possible to search more than the current channel or to change the channel searched. It will be improved in another issue/PR

![image](https://user-images.githubusercontent.com/11926403/124793017-92817200-df1b-11eb-9d6e-8bdc8eee24fb.png)

![image](https://user-images.githubusercontent.com/11926403/124793056-9dd49d80-df1b-11eb-9a01-9264a9ec103d.png)

2021-07-07 16:15 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5dc71471 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2846/1/) | 2021-07-07 16:15:00 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210707-160547-5dc714-pr2846.dmg) |

2021-07-07 16:58 UTC, borismelnik approved these changes

2021-07-07 16:58 UTC, borismelnik commented on ui/app/AppLayouts/Chat/ChatColumn/TopBar.qml
> +                id: searchPopopComponent
just small stupid thing - `PopOp`?

2021-07-07 16:58 UTC, borismelnik commented on ui/app/AppLayouts/Chat/components/BadgeContent.qml
> +    id: wrapper
Will be great if you move id to first line

2021-07-08 19:14 UTC, iurimatias requested changes
Hey good job on this, I gived it a spin, and the search modal height does grow all over the place depending on the search results, could we give it a max height or even a set height once search results show up to avoid this?

2021-07-08 19:17 UTC, jrainville commented
Ah I did give it a max height, but forgot to test it. I'll adjust it to make it work better and also I forgot to add a scroll 🤦 
I'll fix tomorrow morning.

2021-07-12 10:47 UTC, anastasiyaig commented
@jrainville can we please fix the problem Iury mentioned , also a few more:

- [ ] missing scroll in search modal
- [ ] fix the modal height
- [ ] put a contact name in a 1x1 chat search indicator
<img width="1012" alt="Screenshot 2021-07-12 at 11 16 14" src="https://user-images.githubusercontent.com/82375995/125254081-cb965980-e302-11eb-92d4-37c9e4943d01.png">
- [ ] custom picture is not being applied in search pictogram
<img width="1344" alt="Screenshot 2021-07-12 at 12 08 05" src="https://user-images.githubusercontent.com/82375995/125261525-0485fc80-e30a-11eb-8ccf-f1652d996034.png">
- [ ] search icon (magnifying glass) seems to be different than in figma
<img width="1440" alt="Screenshot 2021-07-12 at 12 19 48" src="https://user-images.githubusercontent.com/82375995/125263291-93474900-e30b-11eb-977a-88a57bd59dcc.png">

- [ ] hash symbol is missing when referring a channel in community (assume from designs it should be there), also the community indicator (grey rainbow) probably should not be there (it is not shown on designs)

<img width="1440" alt="Screenshot 2021-07-12 at 12 43 11" src="https://user-images.githubusercontent.com/82375995/125266876-eff83300-e30e-11eb-8036-0d1863f2c76d.png">

2021-07-12 18:36 UTC, jrainville commented
@iurimatias and @anastasiyaig thanks for the tests.
Your issues should be fixed now

2021-07-13 11:57 UTC, anastasiyaig commented
@jrainville thank you for the hard work, looks amazing! is it also possible to make the search non-global, so when entering a search criteria it is not saved there after i close and open the search modal?

here is what @simonricoo suggests:

1. It defo should be cleared when you switch and search the another channel. So you dont bring searched content from "channel 2" to "channel 1" 
2. When searching the same channel Im fine both ways either its remembered or not


https://user-images.githubusercontent.com/82375995/125447553-4ab6b4df-d0e4-44d7-a0ca-191fc1d17ddc.mov

it could be handled in another issue if this is something that will break the whole feature :D Please let me know what u think!

2021-07-13 15:00 UTC, jrainville commented
I can fix it here. It's simple enough. I'll do it later today

2021-07-13 18:14 UTC, jrainville commented
@anastasiyaig done

2021-07-14 09:32 UTC, anastasiyaig commented
great job, thank you @jrainville

2021-07-14 21:42 UTC, merged