feat(mentions): show mentions ordered by how it matches the filter
status-im/status-desktop pull request #2850
Opened 2021-07-07 20:23 UTC by jrainville

Fixes #2543

2021-07-07 20:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 19dfe4d6 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2850/1/) | 2021-07-07 20:33:00 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210707-202342-19dfe4-pr2850.dmg) |

2021-07-09 14:15 UTC, richard-ramos commented on ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml
> +                    text: model[container.property.find(p => !!model[p])]
TIL!

2021-07-09 14:17 UTC, richard-ramos commented on ui/app/AppLayouts/Chat/ChatColumn/SuggestionBox.qml
> +                    text: model[container.property.find(p => !!model[p])]
Ah! it was already part of the suggestionfilter code, but nevertheless, I did not know it was possible to get a model property like this

2021-07-09 14:17 UTC, richard-ramos approved these changes

2021-07-09 15:46 UTC, iurimatias requested changes
there is an issue with the selector, for e.g in this screenshot I type `@em` expecting to see Emizzle first, but instead the cursor is somewhere else, also it doesn't look the results are ordered
![Screen Shot 2021-07-09 at 11 44 17 AM](https://user-images.githubusercontent.com/176720/125104323-3cdbcf80-e0ab-11eb-98a9-2487f9d6a79e.png)

2021-07-09 21:00 UTC, jrainville commented
@iurimatias You issues should be fixed

2021-07-13 13:41 UTC, merged