[#2376] Removed invalid error message when adding new contact
status-im/status-desktop pull request #2903
Opened 2021-07-13 16:25 UTC by alexandraB99

* Also removed from adding new chat

Closes #2376

2021-07-13 16:34 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 433b7123 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2903/1/) | 2021-07-13 16:34:57 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210713-162548-433b71-pr2903.dmg) |

2021-07-13 18:01 UTC, jrainville approved these changes

2021-07-13 21:47 UTC, iurimatias requested changes
I can still replicate this: 3 spaces, 3 backspaces, the box is empty but still shows the error message


https://user-images.githubusercontent.com/176720/125529614-5f9f70dd-2a5d-47aa-bedb-4395d2849fee.mov

2021-07-14 10:14 UTC, alexandraB99 commented
> I can still replicate this: 3 spaces, 3 backspaces, the box is empty but still shows the error message
> 
>  Screen.Recording.2021-07-13.at.5.46.10.PM.mov

Good catch @iurimatias, please check updated PR

2021-07-14 13:55 UTC, jrainville approved these changes

2021-07-14 22:21 UTC, merged