feature(@desktop/communities): add loading state when import community
status-im/status-desktop pull request #2937
Opened 2021-07-16 05:38 UTC by saledjenic

Toast message is added when user access an existing community using community's private key. Toast
message with message that importing community is in progress is displayed while community is being
imported and once it is imported toast is closed and new one, which will be closed in 4 seconds,
with message that community is imported is displayed.

Fixes: #2467

2021-07-16 05:47 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b85b875e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2937/1/) | 2021-07-16 05:47:47 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210716-053844-b85b87-pr2937.dmg) |

2021-07-16 05:52 UTC, pinebit commented on ui/shared/ToastMessage.qml
> +    property string title: "Transaction pending..."
not translated

2021-07-16 05:53 UTC, pinebit commented on ui/shared/ToastMessage.qml
> +        title = "Transaction pending..."
not translated

2021-07-16 09:34 UTC, saledjenic commented
@pinebit for "Transaction pending..." text property particularly I just moved it, it was there before my changes. I add translations for all untranslated properties we have in this branch so far in a separate commit.

2021-07-16 14:03 UTC, jrainville requested changes
Nice job.

I'm requesting changes, because I think that displaying the private key is not a good idea.

Also, I don't think it was necessary to run the translation scripts, though it's good to do from time to time, so it's no big deal. At least you put the translation changes in a different commit, though both your commits have the same name, so I got confused. You should probably rename your second commit something like "chore: run translation scrips"

2021-07-16 22:36 UTC, saledjenic commented
@jrainville I fixed what you requested. There are two commits one with my changes and another with translation related changes. But for it I noticed that many properties doesn't have translations not only properties from changes I applied here, what about that? Do we have translations for them or I should add them only for en language?

Another thing popped up while I tested this now, and it's related most likely to status-go (but I am not sure if such check may be even applied) when you try to import a community even you set some fake pk, community is imported, but without name. I guess that status-go should return kind of error in such case if that check is possible.

2021-07-19 14:06 UTC, jrainville approved these changes

2021-07-19 16:27 UTC, merged