fix(@desktop/chat): cannot unpin last message in modal
status-im/status-desktop pull request #2950
Opened 2021-07-19 08:53 UTC by alaibe

fixes #2659

1 - Avoid to double refresh the pin messages by removing call to addPinMessage and removePinMessage.
This is done by event

2 - Change call from remove to deleteMessage
Remove were not updating the index and was causing the issue

3 - Erase the remove proc as the deleteMessage should always be used

3 - Rename addPinnedMessages to refreshPinnedMessages

2021-07-19 09:03 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1a2fc436 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2950/1/) | 2021-07-19 09:03:12 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210719-085338-1a2fc4-pr2950.dmg) |

2021-07-19 09:31 UTC, pinebit approved these changes

2021-07-19 14:14 UTC, jrainville approved these changes

2021-07-19 17:25 UTC, iurimatias requested changes
I cannot unpin, see video


https://user-images.githubusercontent.com/176720/126201283-e10f281e-4502-46b7-bb5f-fd27a9c99d1d.mov

2021-07-20 07:30 UTC, alaibe commented
@iurimatias PR updated. I was working from the communities chat and the problem you found was from group chat. Would you know why there is no chat update event triggered when pinning/unpining from a group but there is one from a community chat?

2021-07-20 12:25 UTC, anastasiyaig commented
it seems to be working to me, the only part i did not check is pin / unpin in modal for community channels since the pin indicator is gone there for some reason https://github.com/status-im/status-desktop/issues/2976

2021-07-20 12:33 UTC, alaibe commented
@anastasiyaig you can test this part by right click on the channel -> Edit -> Pinned message

2021-07-20 12:34 UTC, anastasiyaig commented
@alaibe this one i did for sure!

2021-07-20 13:11 UTC, jrainville approved these changes

2021-07-20 14:00 UTC, merged