feat(chat): add unfurling message for images
status-im/status-desktop pull request #2989
Opened 2021-07-20 18:30 UTC by jrainville

Fixes #1940

![image](https://user-images.githubusercontent.com/11926403/126376844-3c2ec9f4-a415-4141-8ac3-93f2414b645e.png)

2021-07-20 18:40 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8f3a1140 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-2989/1/) | 2021-07-20 18:40:46 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210720-183053-8f3a11-pr2989.dmg) |

2021-07-21 05:30 UTC, pinebit approved these changes

2021-07-21 14:02 UTC, richard-ramos approved these changes

2021-07-23 18:52 UTC, iurimatias requested changes
in this case it's a URL, but it says it's an image unfurling

<img width="638" alt="Screen Shot 2021-07-23 at 2 51 34 PM" src="https://user-images.githubusercontent.com/176720/126828227-b2109077-5c08-45fc-94e5-000ad3969ea9.png">

2021-07-23 19:42 UTC, jrainville commented
> in this case it's a URL, but it says it's an image unfurling

Sorry about that. I fixed it, @iurimatias

2021-07-23 21:44 UTC, iurimatias commented
found https://github.com/status-im/status-desktop/issues/3043 but this PR is unrelated

2021-07-23 21:44 UTC, merged