fix(@desktop/chat): channel suggestions are not being displayed
status-im/status-desktop pull request #3267
Opened 2021-08-23 04:34 UTC by pinebit

Fixes #3260 
and fixes one annoying QML warning in InvitationBubble.qml

2021-08-23 04:44 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e83467a8 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3267/1/) | 2021-08-23 04:44:44 | ~10 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210823-043431-e83467-pr3267.dmg) |

2021-08-23 08:03 UTC, alaibe approved these changes

2021-08-23 19:03 UTC, iurimatias requested changes
the suggestions are still missing

<img width="1233" alt="Screen Shot 2021-08-23 at 2 51 55 PM" src="https://user-images.githubusercontent.com/176720/130503177-db82f550-9945-497f-bddc-3d1d352d06ec.png">

2021-08-24 09:59 UTC, pinebit commented
I did not check that use case. Now fixed.

2021-08-24 19:35 UTC, merged