feat(@desktop/Windows): status-im:// protocol support and installer
status-im/status-desktop pull request #3372
Opened 2021-09-06 09:04 UTC by pinebit

Fixes #837 

1. Windows only.
2. Installer to execute `vc_redist.x64.exe` silently when installing the app.
3. Installer to registry `status-im://` protocol handler.
4. Application to receive `--url=status-im://0x123...` cmd line argument to create/open 1-1 chat.
5. Only 1-1 chat links are supported for now.

Future work (TODOs):
1. Integrate "single instance" feature https://github.com/status-im/status-desktop/pull/3003
2. Support status protocol variations for communities, public chats, etc. Need a full list of possibilities.

How to test:
1. Uninstall Status app.
2. Install Status app using the new installer built from this branch.
3. Open a browser (e.g. Chrome) or File Explorer, paste the link
`status-im://0x04ecb3636368be823f9c62e2871f8ea5b52eb3fac0132bdcf9e57907a9cb1024d81927fb3ce12fea6d9b9a8f1acb24370df756108170ab0e3454ae93aa601f3c33`
4. You should have a 1-1 chat with "Round True Cicada" user
Note: application must not be running until the TODOs mentioned in above are resolved.

2021-09-06 09:14 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f29fa513 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3372/1/) | 2021-09-06 09:14:47 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210906-090506-f29fa5-pr3372.dmg) |

2021-09-06 09:23 UTC, alaibe approved these changes
LGTM!

2021-09-07 09:50 UTC, saledjenic approved these changes

2021-09-08 07:19 UTC, pinebit commented
@anastasiyaig I fixed some bugs and now this should be working as expected. Given the only limitation for now: the app shall not be running when invoked by a deep link from browser or file explorer.
The latter is to be addressed in my next work (single app instance logic), but this PR is a pre-requisite.

2021-09-09 08:10 UTC, pinebit commented
Rebased. Again.

2021-09-09 10:49 UTC, anastasiyaig commented
@pinebit status.exe on mac?

<img width="1552" alt="Screenshot 2021-09-09 at 13 48 45" src="https://user-images.githubusercontent.com/82375995/132672826-d4b556d9-c66c-4590-a572-d475dd5e1815.png">

2021-09-09 13:55 UTC, richard-ramos requested changes
The format for the URL for 1:1 chats should be:

status-im://p/0x1234.....5453

For reference, the URL formats supported on mobile are defined in:
https://github.com/status-im/status-react/blob/develop/src/status_im/utils/universal_links/core.cljs#L24-L38

Also in here for join.status.im
https://github.com/status-im/universal-links-handler/blob/cadf83ef9631123688f6883bc0841509ca7c3c86/routes/index.js#L208-L235

2021-09-09 14:54 UTC, pinebit commented
> The format for the URL for 1:1 chats should be:
> 
> status-im://p/0x1234.....5453
> 
> For reference, the URL formats supported on mobile are defined in:
> https://github.com/status-im/status-react/blob/develop/src/status_im/utils/universal_links/core.cljs#L24-L38
> 
> Also in here for join.status.im
> https://github.com/status-im/universal-links-handler/blob/cadf83ef9631123688f6883bc0841509ca7c3c86/routes/index.js#L208-L235

Fixed for 1-1 chats. Thank you @richard-ramos !

2021-09-09 14:56 UTC, pinebit commented
> @pinebit status.exe on mac?
> 
> <img alt="Screenshot 2021-09-09 at 13 48 45" width="1552" src="https://user-images.githubusercontent.com/82375995/132672826-d4b556d9-c66c-4590-a572-d475dd5e1815.png">

This is rendered by browser. The installation package for Mac seems to have executable named with .exe at the end. Anyway, since @saledjenic is going to work on Mac support, then he will pay attention to this and fix as needed.

2021-09-09 20:53 UTC, merged

2021-09-10 13:54 UTC, saledjenic commented
> Anyway, since @saledjenic is going to work on Mac support, then he will pay attention to this and fix as needed.
That is handled.

![open_popup](https://user-images.githubusercontent.com/86303051/132864209-f6b94722-2b79-48ea-a4d1-739a4d073e3e.png)

MacOs PR is [here](https://github.com/status-im/status-desktop/pull/3465).