feat(wallet2): introduce saved addresses
status-im/status-desktop pull request #3425
Opened 2021-09-08 12:26 UTC by emizzle

Closes #3307.

WalletV2 view can be toggled between normal wallet view and the SavedAddresses view.

Users can load, add, edit, and delete saved addresses.

Favouriting a saved address is out of scope, as is sending to a saved addresses, drilling down in to a saved address, and supporting multiple networks.

Updates components that utilised the StatusMinLengthValidator component to support the changes made to StatusQ.

### Notes
1. Depends on status-go PR https://github.com/status-im/status-go/pull/2356
2. Depends on StatusQ PR https://github.com/status-im/StatusQ/pull/394.

2021-09-08 12:36 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 97dae1c6 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3425/1/) | 2021-09-08 12:36:13 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210908-122639-97dae1-pr3425.dmg) |

2021-09-08 13:33 UTC, pinebit commented on ui/app/AppLayouts/WalletV2/LeftTab.qml
> +    //RowLayout {
intentional dead code?

2021-09-08 13:34 UTC, pinebit approved these changes

2021-09-09 09:53 UTC, emizzle commented on ui/app/AppLayouts/WalletV2/LeftTab.qml
> +    //RowLayout {
Removed.

2021-09-10 18:07 UTC, iurimatias commented
tested looks good, waiting for statusQ PR to have go ahead

2021-09-13 11:08 UTC, emizzle commented
> tested looks good, waiting for statusQ PR to have go ahead

@iurimatias all depending PRs have been merged and bumped in this PR.

2021-09-15 17:23 UTC, iurimatias requested changes
I get this error when trying to save an addresss, the status-go version is correct etc..

`ERR 2021-09-15 13:23:26-04:00 rpc response error                         topics="rpc" tid=22383258 file=core.nim:24 methodName=wallet_addSavedAddress payload="[{\"name\":\"test\",\"address\":\"0x0000000000000000000000000000000000000000\"}]" result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"no such table: saved_addresses\"}}"`

2021-09-17 03:23 UTC, emizzle commented
@iurimatias - I am not seeing this error at all. Have rebased this yet again and merged in the conflicts that have changed since this PR was put up.

2021-09-20 12:32 UTC, merged