WIP: generating a .deb for status-desktop
status-im/status-desktop pull request #3512
Opened 2021-09-14 00:45 UTC by richard-ramos

All the changes in the Docketfile and Makefile are just so I can test stuff.
**Do not review this PR yet**

2021-09-14 00:48 UTC, richard-ramos commented
I had to execute
```
unset QTDIR
 unset QT_PATH
```
so it uses the OS QT libs on /usr/lib/x86_64-linux-gnu instead of those of the manual installation of QT

2021-09-14 00:50 UTC, richard-ramos commented
The following packages are required in Ubuntu 21.04:
```
pbuilder ubuntu-dev-tools apt-file qtbase5-dev qtdeclarative5-dev qml-module-qt-labs-platform qtquickcontrols2-5-dev libqt5svg5-dev libqt5gui5 libqt5core5a libqt5network5 libqt5qml5 libqt5quick5 libqt5svg5 libqt5webengine5 libqt5webenginecore5 libqt5quickcontrols2-5 libqt5widgets5 
```

2021-09-14 00:53 UTC, richard-ramos commented
Installing the resulting .deb and executing `status-desktop` displays the following error:
```
status@laptop:~/status-desktop$ status-desktop
/home/status/status-desktop/src/nim_status_client.nim(269) nim_status_client
/home/status/status-desktop/src/nim_status_client.nim(45) mainProc
/home/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(693) readFile
Error: unhandled exception: cannot open: /usr/local/fleets.json [IOError]
```
**TODO**: make the content of fleets.json part of a defined constant in nim, instead of reading it from the .json

2021-09-14 00:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 9393db07 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3512/1/) | 2021-09-14 00:53:30 | ~7 min | `macos` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3512/1/consoleText) |

2021-09-19 00:52 UTC, richard-ramos commented
The new dockerfile uses debian:bullseye instead of ubuntu:21.04,  so it uses a slightly older version of libc, and also because in this version Qt 5.15.2 is introduced. The resulting .deb works in Debian, Ubuntu and Pop OS.

2021-09-20 08:17 UTC, jakubgs commented on build-linux-appimage.sh
> +docker run -it --rm \
Could we maybe move these scripts into `scripts`? The root of this repos is already cluttered enough as it is.

2021-09-20 08:19 UTC, jakubgs commented on Makefile
> +deb: check-pkg-target-linux $(STATUS_CLIENT_DEB)
Shouldn't this be `deb-linux`? Or really, the targets should start with the platform, so it's:
```
make linux-deb
make linux-app
make windows-zip
make windows-exe
```

2021-09-20 08:21 UTC, jakubgs commented on scripts/deb/control
> +Package: status-desktop
None of these files are scripts, and should not be under `scripts`. As stated in #3367 we need something like a `resources` folder where we can put stuff like that. So it's `resources/pkg/deb/control` or something like that.

2021-09-20 08:22 UTC, jakubgs commented on docker-linux.sh
> +make V=1 $1
This should also be in `scripts`, not in repo root.

2021-09-20 08:30 UTC, jakubgs commented on ci/README.md
> +cd ..
Don't you mean `ci/AppImage`? Also, you can do this like this:
```
docker build -t statusteam/nim-status-client-build:latest ci/AppImage
```
Without having to `cd` anywhere`.

2021-09-20 08:31 UTC, jakubgs requested changes
Looks decent, but the location of some of the files doesn't make sense.

2021-09-20 16:14 UTC, jakubgs approved these changes
Much better.

2021-09-20 16:15 UTC, merged