fix(ContactsColumn): call `itemAt` on delegate.model instead of delegate
status-im/status-desktop pull request #3574
Opened 2021-09-16 14:09 UTC by PascalPrecht

Fixes #3328

2021-09-16 14:28 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 618fd821 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/windows/job/PR-3574/1/) | 2021-09-16 14:28:59 | ~19 min | `windows` | [:package:`exe`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210916-140947-618fd8-pr3574.exe) |

2021-09-16 16:33 UTC, alaibe requested changes
I think the error will persist as itemAt is not available on channel list.

I *think* you need to expose the id of the repeater an call itemAt there

2021-09-17 08:14 UTC, PascalPrecht commented
@alaibe good catch!

I wasn't seeing that error before because it's triggered by a `Connection`. Updated the PR accordingly.

2021-09-17 11:38 UTC, alaibe approved these changes

2021-09-20 14:36 UTC, merged