chore: remove status-go from desktop
status-im/status-desktop pull request #3686
Opened 2021-09-23 19:09 UTC by richard-ramos

Requires
- https://github.com/status-im/status-lib/pull/50

2021-09-23 19:19 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 242036ad | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-3686/1/) | 2021-09-23 19:19:34 | ~9 min | `linux` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-3686/1/consoleText) |

2021-09-23 20:54 UTC, michaelsbradleyjr requested changes
This line needs to be updated: https://github.com/status-im/status-desktop/blob/242036ad203b583a1be35d2c6248e7cfe92e3449/Makefile#L327

To:
```Makefile
cp vendor/status-lib/vendor/status-go/build/bin/libstatus.so tmp/linux/dist/usr/lib/
```

2021-09-23 21:11 UTC, michaelsbradleyjr approved these changes

2021-09-24 06:34 UTC, pinebit approved these changes

2021-09-24 07:41 UTC, alaibe approved these changes
Nice!

2021-09-29 18:50 UTC, merged