feat(ProfilePopup): Add avatar change functionality
status-im/status-desktop pull request #3825
Opened 2021-10-15 08:04 UTC by borismelnik

Closes: #3734

2021-10-15 08:16 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6d06f844 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-3825/1/) | 2021-10-15 08:16:22 | ~11 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-211015-080509-6d06f8-pr3825.dmg) |

2021-11-11 08:08 UTC, PascalPrecht approved these changes
LGTM! Well done!

2021-11-11 18:57 UTC, alexandraB99 approved these changes

2021-12-23 10:53 UTC, anastasiyaig commented
@borismelnik would u mind to show  a picture preview instead of empty circle?

this is how it looks when editing profile from online/offline identifier (new functionality u added)

<img width="1427" alt="Screenshot 2021-12-23 at 13 48 07" src="https://user-images.githubusercontent.com/82375995/147230311-d0658bd7-8900-4478-b571-7f6b000cf58f.png">

and this is how it looks like when editing profile from Settings

<img width="1427" alt="Screenshot 2021-12-23 at 13 48 33" src="https://user-images.githubusercontent.com/82375995/147230420-6d3c5be9-4852-4f75-a6f8-083d79d3c7a6.png">

2022-01-16 20:33 UTC, borismelnik commented
@alexandraB99 It will be great if you find time for checking proper use of the store.

2022-01-17 19:50 UTC, alexandraB99 requested changes

2022-01-17 19:50 UTC, alexandraB99 commented on ui/app/AppMain.qml
> +import "./AppLayouts/Profile/stores" as ProfileStores
There is no need for an additional store instance, you can add this in the `status-desktop/ui/app/AppLayouts/stores/RootStore.qml` and assign it in line 462 like`store: appMain.rootStore.profileStore`.

2022-01-19 15:21 UTC, Khushboo-dev-cpp approved these changes

2022-01-20 08:29 UTC, noeliaSD approved these changes

2022-01-21 00:21 UTC, alexandraB99 approved these changes

2022-01-25 07:25 UTC, merged