refactor: move contact requests to new architecture
status-im/status-desktop pull request #4065
Opened 2021-11-08 21:31 UTC by jrainville

Fixes #4061

Most of the contact request code was already moved, but it wasn't hooked to the QML yet and also there were missing events and some code to improve.

I think that with these changes, it would be possible to now remove the old code for contacts. I will do that in another PR

2021-11-08 21:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a6adcb0b | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-4065/1/) | 2021-11-08 21:42:10 | ~10 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-211108-213150-a6adcb-pr4065.dmg) |

2021-11-09 12:41 UTC, richard-ramos approved these changes
nice!

2021-11-11 08:54 UTC, anastasiyaig commented
@jrainville i created new account from scratch in the PR (commit https://github.com/status-im/status-desktop/commit/0fa49523f36530309184c11d776912580f5e41a4) and it looks like a lot of this are missing here:

can u please take a look:

flags enabling is not working:

<img width="1344" alt="Screenshot 2021-11-11 at 11 48 08" src="https://user-images.githubusercontent.com/82375995/141267272-f876793f-b653-4939-95bb-ed1ea1cca5ee.png">


timeline and settings icons are the same
<img width="1344" alt="Screenshot 2021-11-11 at 11 47 55" src="https://user-images.githubusercontent.com/82375995/141267294-c7998c1c-2d9a-412a-a47e-0a685f8e8303.png">

when creating new account, there is a weird contact request to someone
<img width="1344" alt="Screenshot 2021-11-11 at 11 47 44" src="https://user-images.githubusercontent.com/82375995/141267299-1bfee2d5-2f9f-46c6-b784-4c03a5f3e455.png">

profile picture is not shown
<img width="1344" alt="Screenshot 2021-11-11 at 11 47 37" src="https://user-images.githubusercontent.com/82375995/141267303-c7244a9e-3f32-489f-bbe7-8436e394c232.png">

adding contact results in error

```
INF 2021-11-11 11:52:23.463+03:00 history request started                    topics="mailserver-interaction" tid=236337 file=core.nim:103
qrc:/StatusQ/src/StatusQ/Components/StatusRoundedImage.qml:27:5: QML Image: Cannot open: qrc:/app/AppLayouts/Profile/panels/(jsonrpc: %22%22, result: %22data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAgElEQVR4nOzWsQmAQBAFURV7sTI7sAw7sDKr0VwMVvC44TMvlEuGD4vTEMIQGkNoDKExhMYQGkNoDKGJCZmrD49zv96+r8s29nj/FLOIITSGqJGYRQyhMYTGfy0aQ2gMoSlfra+q1+YvMYsYQmOIGolZxBAaQ2gMoTGE5g4AAP//I/YZaHdYNaEAAAAASUVORK5CYII=%22, id: 0, error: nil)
```

<img width="1344" alt="Screenshot 2021-11-11 at 11 52 26" src="https://user-images.githubusercontent.com/82375995/141267702-cb541d04-ff3b-4d5f-ab16-ec38358f92f8.png">

removed contact still appears in list when opening 1x1 chat menu

<img width="1344" alt="Screenshot 2021-11-11 at 11 53 53" src="https://user-images.githubusercontent.com/82375995/141267921-551094d3-c881-409b-8f8c-cdc6dc651a58.png">

2021-11-11 15:09 UTC, jrainville commented
This is mostly a list for myself so I remember. Here are the issues that are part of `base_bc`, so were not introduced in my branch. I think they are fixed in master and once `base_bc` will be rebased, most of them will be fixed:
- timeline and setting as same icon
- New account contact request thingy
- profile picture not shown
- empty my profile

2021-11-11 15:13 UTC, anastasiyaig commented
@jrainville ya, some of this is already fixed in master, maybe we need to rebase `base_bc` , but i think the issues about contact requests mentioned above should be relevant, at least i dont see them in master

2021-11-11 15:15 UTC, jrainville commented
@anastasiyaig yeah all the contact issues should be from my own branch. I'll fix them now

2021-11-11 16:42 UTC, jrainville commented
@anastasiyaig I fixed the contact issues. The other issues are caused by the base branch being very much a breaking change branch.

2021-11-15 10:20 UTC, anastasiyaig commented
@jrainville were u able to finish fixing the issues for adding a contact? 

<img width="1344" alt="Screenshot 2021-11-15 at 13 20 30" src="https://user-images.githubusercontent.com/82375995/141764779-e4420589-ca56-488f-9476-eee219513590.png">

2021-11-15 15:59 UTC, jrainville commented
@anastasiyaig It should be fix. I just rebased and tested and it worked fine for me

2021-11-15 20:52 UTC, alexandraB99 commented
@jrainville is this ready for review? (it is marked as do-not-merge)

2021-11-15 20:57 UTC, jrainville commented
@alexandraB99 yes. I think Nastya marked as Do not merge because she found a bug, but I fixed it, but also the code can still be reviewed.

2021-11-16 21:41 UTC, alexandraB99 requested changes

2021-11-16 21:41 UTC, alexandraB99 commented on ui/app/AppMain.qml
> +        const index = contactsModule.model.list.getContactIndexByPubkey(pubkey)
Could this be moved to AppMain's store? +all the below

2021-11-17 14:45 UTC, jrainville commented
@alexandraB99 thanks for the review. I focused more on the Nim side for the refactor. 
I know my store usage is subpar to say the least, but it was because I know Sale and some of you guys are already refactoring the QML side for chats and I wanted to be able to test quickly and possibly merge this without as many conflicts.

Let me know if you think I should still commit to refactoring the stores as well

2021-11-17 16:34 UTC, alexandraB99 commented
> @alexandraB99 thanks for the review. I focused more on the Nim side for the refactor. I know my store usage is subpar to say the least, but it was because I know Sale and some of you guys are already refactoring the QML side for chats and I wanted to be able to test quickly and possibly merge this without as many conflicts.
> 
> Let me know if you think I should still commit to refactoring the stores as well

fair enough, could you just please add TODO so that we move these parts in stores at some point of time?

2021-11-17 16:35 UTC, jrainville commented
Good point. I'll add the TODOs once I rebase

2021-11-17 19:18 UTC, jrainville commented
@alexandraB99 you can review again. I rebased and added TODOs.
I'll squash when I have your 👍

2021-11-17 21:14 UTC, alexandraB99 approved these changes

2021-11-17 21:28 UTC, merged