perf(@chat): Demonstrate slowliness of switching chat
status-im/status-desktop pull request #4505
Opened 2022-01-20 12:24 UTC by alaibe

First load is very fast < 0.1s
But then coming back & forth between chat with a lot of message become
slower.

I couldn't find any particular call being slow but as we 100s of message
in memory, the rendering takes time. It can go up to 1s which is I think
not reasonable.

As we keep chat content in memory I would trim the number of messages we
keep in memory to < 20 when we are switching to another chat

2022-01-20 12:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 999e09d5 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-4505/1/) | 2022-01-20 12:33:32 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220120-122505-999e09-pr4505.dmg) |

2022-01-20 14:21 UTC, jrainville commented
We can try keeping the chats at 20 messages in history. We probably would have needed to do some kind of culling at one point anyway in the future if we ended up supporting tablets or older computers. For now, you can even do an ugly hardcode in the model like "if messages.len > 19 -> don't add" just to try if it helps the situation.

2022-01-21 07:39 UTC, saledjenic commented
@alaibe I'll think out loud below, maybe something of that may help us or give an idea to find a reason why we have that slowness. 

I don't not think that keeping hundreds of messages in memory should have some performance impact (even we have there thousands of them shouldn't be an issue, a single message is just a struct with ~15 simple type fields and all PCs today have big RAM). Instead maybe we should take a look and go in a way what's happening when we switch a chat in terms of actions taken after we call `setActiveItemSubItem` from controller of chat section module. 

That action is doing an async load of initial messages (up to 20 messages) for a chat, but only if they are not already fetched, so that shouldn't be an issue.

Next step is `activeItemSubItemSet` from the view of chat section module, it looks a bit problematic, maybe, briefly looking into that method:

- line `self.view.chatsModel().setActiveItemSubItem(itemId, subItemId)` -  shouldn't be problematic since it just updated a single `active` prop of an item, **but we should check if there are connected actions if an active state of the chat item has changed on the qml side** since it could be some additional components creation is caused by that 
- `self.view.activeItemSubItemSet(item, subItem)` -  in this line we're updating `activeItem` property for which **we also need to check qml side** for the same reasons as in a previous line.
- `self.delegate.onActiveChatChange(self.controller.getMySectionId(), self.controller.getActiveChatId())` - this line shouldn't have any performances impact, but may be checked as well
- `self.controller.markAllMessagesRead(self.controller.getActiveChatId())` - this line shouldn't have any performances impact since it's an async action, but it sends `SIGNAL_MESSAGES_MARKED_AS_READ` signal which in turns calls `updateNotifications` which is an action which may have a performance impact.

Those are some point where I would look for some performance improvements.

2022-01-21 08:40 UTC, alaibe commented
@saledjenic the problem is not indeed the 100s of messages in memory, as you mention it they are simple struct. Also the issue doesn t seem to be on the nim side. I couldn t find any slow function even called with many messages.

It seems the problem is coming from re-rendering messages. Let me explain a bit more:
when switching chat, if this chat as 100 messages, then the 100 messages will be re-render. If you compare to master, only the messages displayed on screen will be re-render. I believe this is the issue

@jrainville did a second commit where he get rid of the StackLayout which seems to solve the problem

2022-01-21 09:07 UTC, saledjenic commented
> when switching chat, if this chat as 100 messages, then the 100 messages will be re-render. If you compare to master, only the messages displayed on screen will be re-render. I believe this is the issue

Yes, this sounds reasonable, I also thought that performance issues are most likely caused by some components on the qml side, that's why I said in the previous comment `we should check if there are connected actions on the qml side` and `root.activeChatId` used in that `StackLayout` which @jrainville updated is exactly the change connected to the `activeItem`.

> @jrainville did a second commit where he get rid of the StackLayout which seems to solve the problem

Yes I agree, that `StackLayout` is totally useless, it's kept there only cause it was like that in the old code and that part was just adapted to follow backend changes, not refactored, but we need to improve it. We definitely need to remove that StackLayout and make `EmptyChatPanel` visible only when there is no chats.

2022-01-21 14:15 UTC, jrainville requested changes
Looks good, but I'll ask changes on my own duo work haha.
One step that's messing from this and it pretty necessary is an initial Loader for the chats, so that they are lazy loaded.

So we wrap the `ChatContentView` in a  Loader that is false by default except the active one. We add a Connection on `activeChatId` and `activeSubItemId`, when there is a new one that is activated, we turn that Loader `true`.

Later, we can add another layer of memory protection by turning old Loaders to `false` if the user activated a lot of chats, so we keep only in memory the more recent ones.

Le me know if it's not clear and I can show better

2022-01-21 14:15 UTC, jrainville commented on ui/app/AppLayouts/Chat/stores/RootStore.qml
> +
```suggestion

```

2022-01-21 14:15 UTC, jrainville commented on ui/app/AppLayouts/Chat/views/ChatColumnView.qml
> +    Item {
The Item shouldn't be needed anymore. I had kept it just because I wanted to test quickly

2022-01-21 14:15 UTC, jrainville commented on ui/app/AppLayouts/Chat/views/ChatColumnView.qml
> +                        // anchors.fill: parent
Leftover

2022-01-21 14:15 UTC, jrainville commented on ui/app/AppLayouts/Chat/views/ChatColumnView.qml
> +                        height: {
Might be worth adding a comment here saying what the hell this does.

2022-01-21 14:15 UTC, jrainville commented on ui/app/AppLayouts/Chat/views/ChatColumnView.qml
>                  DelegateChoice { // In all other cases
The other DelegateChoice above will need the `height` change as well.

2022-01-24 11:04 UTC, alaibe commented
@jrainville all comments done I think, let me know if there is something else

2022-01-24 14:45 UTC, jrainville approved these changes
Looks good. Nice job.

We just need to add new issues, one for the Loaders, so not all the `ChatContentView`s are loaded on start

Then a second one to unload some of the `ChatContentView`s if the user ever opens a ton of them, so the older ones can free some memory.

2022-01-24 14:55 UTC, jrainville commented
> about this one I am not sure, will be a bit weird if one know that he opened some chat/channel and after some time when he goes back to see that messages need to be loaded again or see that he has only last 20 messages, but he opened that chat/channel like 5hrs ago. Maybe we should think better about this one.

Yeah we can test and discuss that one. I guess I mostly wanted to have an issue so we remember that having a lot of chats active could cause an issue

2022-01-25 14:45 UTC, merged