refactor(communities): sort categories and chats
status-im/status-desktop pull request #4657
Opened 2022-02-01 22:49 UTC by richard-ramos

- Fixes: #4543
- Fixes: #4521

2022-02-01 22:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1a756930 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-4657/1/) | 2022-02-01 22:57:59 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220201-224929-1a7569-pr4657.dmg) |

2022-02-02 10:39 UTC, Khushboo-dev-cpp commented on src/app/modules/main/communities/controller.nim
> +  self.events.on(SIGNAL_COMMUNITY_CATEGORY_REORDERED) do(e:Args):
remove as this doesn't nothing?

2022-02-02 10:42 UTC, Khushboo-dev-cpp commented on src/app/modules/main/communities/controller.nim
> +  self.events.on(SIGNAL_COMMUNITY_CATEGORY_REORDERED) do(e:Args):
remove this as it is unused? also maybe emitting signal is not needed? handled in chat_sections controller

2022-02-02 10:43 UTC, Khushboo-dev-cpp requested changes
I just found one small leftover code

2022-02-02 14:01 UTC, anastasiyaig commented
sometimes reordering channels does not make any effect, not sure the reason @richard-ramos could u please also check?


https://user-images.githubusercontent.com/82375995/152168213-84c929cd-be39-46f4-ba18-f5200a687632.mov

2022-02-04 11:26 UTC, anastasiyaig commented
@richard-ramos  will u have time to look into this?

2022-02-04 12:22 UTC, richard-ramos commented
I'll have a look now

2022-02-04 17:38 UTC, richard-ramos commented
@anastasiyaig latest commit in this branch should fix the issue

2022-02-07 09:50 UTC, Khushboo-dev-cpp approved these changes
thank you :)

2022-02-08 17:01 UTC, anastasiyaig approved these changes

2022-02-08 17:35 UTC, iurimatias approved these changes

2022-02-08 18:26 UTC, merged