Fix duplicate channels on community signals for edits and category changes (implements all category signal)
status-im/status-desktop pull request #4866
Opened 2022-02-22 21:36 UTC by jrainville

Fixes #4859, #4858, #4865, #4753

The problem was that signals were received with chat updates, but we didn't check the communityId correctly, and also we didn't check if the chat wasn't added yet.

This also implements the community category signal handling, making it possible to update the categories and chats within it when updating from another device. It also fixes issues of duplication when doing that.

2022-02-22 21:49 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 2ca4b34e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-4866/1/) | 2022-02-22 21:49:23 | ~12 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220222-213715-2ca4b3-pr4866.tar.gz) |

2022-02-23 10:01 UTC, saledjenic approved these changes

2022-02-23 18:36 UTC, jrainville commented
@anastasiyaig I fixed the bug about adding a channel to category.

For the other bug about editing, I can't reproduce. Do you have repro steps?

2022-02-23 21:18 UTC, iurimatias approved these changes

2022-02-23 21:23 UTC, iurimatias requested changes
When doing the steps mentioned by Nastya: `Also, when i add a channel to category by creating category first and then clicking + button -> it is not being created inside the category, but out of it`

It works but the channel is blank like in this screenshot

![Screen Shot 2022-02-23 at 4 22 13 PM](https://user-images.githubusercontent.com/176720/155410813-fa5ec8f6-65c9-4fb9-a8bb-c7308577aecd.png)

2022-02-24 10:08 UTC, anastasiyaig commented
@jrainville addition to @iurimatias comment, creating a channel in community is now adding it like this (no matter of category presence):

<img width="1438" alt="Screenshot 2022-02-24 at 13 06 41" src="https://user-images.githubusercontent.com/82375995/155503474-e38db2fc-f195-4d11-ac00-3121abf7a5d1.png">

i can't reproduce the Edit bug in latest build

2022-02-24 10:43 UTC, saledjenic commented
@jrainville please take a look at PR #4879 changes done there are not big, but maybe would be good to have that merged into `master` before these changes here and you just update your code accordingly (cause we updated the same few lines).

Most important changes there which may be useful here are done in `addChatIfDontExist` proc, [here](https://github.com/status-im/status-desktop/blob/ade5a2d239d02f32f4322db0b4e49a2f2d158082/src/app/modules/main/chat_section/module.nim#L749-L757).

2022-02-24 18:10 UTC, jrainville commented
@iurimatias and @anastasiyaig it should be fixed now

2022-02-24 18:48 UTC, jrainville commented
This latest commit (https://github.com/status-im/status-desktop/pull/4866/commits/8ca2658c3089ec0c6ed264eb0352388c0e65b351) fixes #4842

2022-02-24 21:53 UTC, iurimatias approved these changes
tested

2022-02-24 21:54 UTC, merged