feat: display name
status-im/status-desktop pull request #4946
Opened 2022-03-02 00:18 UTC by richard-ramos

Requires:
- https://github.com/status-im/nim-status-go/pull/7
- https://github.com/status-im/status-go/pull/2541

Fixes #4783

Adds the minimum required functionality for setting the display name. It looks ugly because it's just to show the functionality. 
That should be solved in #4921

2022-03-02 00:25 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 9767ac8b | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-4946/1/) | 2022-03-02 00:25:40 | ~6 min | `linux` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-4946/1/consoleText) |

2022-03-03 17:43 UTC, iurimatias requested changes
generating an account is only generating one key

https://user-images.githubusercontent.com/176720/156621501-cd69c542-319d-4beb-ae9d-213fcabecf27.mov

2022-03-03 17:44 UTC, iurimatias commented
status-go vendor needs to updated

2022-03-14 16:57 UTC, alexandraB99 approved these changes
please rebase

2022-03-14 17:46 UTC, iurimatias approved these changes

2022-03-14 19:17 UTC, merged