Improve ChatContentView loading and duplication
status-im/status-desktop pull request #4963
Opened 2022-03-03 21:19 UTC by jrainville

Removes some duplication for the category and normal channels that was suggested here: https://github.com/status-im/status-desktop/pull/4929#discussion_r818429901

Also, and more importantly, in the second commit, I put the `ChatContentView` in a Loader that is disabled by default.
What this does is speeding up the initial app load since only one channel will be loaded. It also reduces the initial memory usage.
We retain the channel switching speed improvement we implemented last time, because once a channel is loaded, we don't unload it when switching, we just hide it like before.

The only downside of this change is that the first load of a clicked channel can have a mini delay, since it loads the content. However, once it is loaded, you can go back and forth between it and another and it will be instant.

For QAs, there is no issue attached, but what you can test is the channels and switching work as before, aka there is no regression with channel switching.

2022-03-03 21:28 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d6eb1b93 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-4963/1/) | 2022-03-03 21:28:16 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220303-211928-d6eb1b-pr4963.dmg) |

2022-03-04 08:41 UTC, alaibe approved these changes
LGTM

2022-03-04 09:22 UTC, saledjenic requested changes
@jrainville I haven't tried this solution, but I see it as more natural, shorter and maybe easier for one who is going to look at this part of code in the future. 

If our goal is to have only one chat loaded on the app start, then we firstly need to update backend and then qml, so some steps I see are:
- Procs `buildChatUI` and `buildCommunityUI` are responsible for loading chats for "Chat"(only one) and "Community"(can be 0 or more) sections on the app start and those 2 procs set `active` prop of each item of corresponding model to `false` and on their ends have `self.setActiveItemSubItem` which sets `activeItem` and `activeSubItem` which are `Q_PROPERTY` and also sets `active` prop of appropriate item in the corresponding model. 
Based on above description that means we set "active" chat for each loaded section, so that's the first thing we need to update in order to be sure that active chat is set only for active section.
- Now we need to make sure that changing chat within the active section appropriately updates `activeItem` and `activeSubItem` properties as well as "active" prop of appropriate item (that is already as described I think)
- Now we need to make sure that switching section sets `activeSection` property (which is already done) but now that action need to set `activeItem` and `activeSubItem` properties as well as "active" prop of appropriate item of the section we have switched to (active chat in this case will be always the first chat in the if model is not empty)
- Now we're ready to do changes on the qml side, so with above changes I hope that it will be enough just to set `active` prop of both `Loader`s (one with id `chatLoader` and one with id `categoryChatLoader`) like this `active: model.active` and that should substitute all changes you did on the qml side. If that doesn't work (but it should be working) then this change will surely work:
  - for loader with id `chatLoader` should be `active: model.itemId == root.activeChatId`
  - for loader with id `categoryChatLoader` should be `active: model.itemId == root.activeSubItemId`

@jrainville comments below are more like some observation, while here what is written above is suggestion for the change.

2022-03-04 16:23 UTC, jrainville commented
@saledjenic I updated the code with regards to your comments. Thanks for them.

As for the bigger comment on updating the code in Nim, like I talked to you, it's better to do it later, when the issue of loading chats is fixed, since for now, when we load a channel, sometimes it loads way more messages than it should.
I created a new issue to fix the underlying issue here https://github.com/status-im/status-desktop/issues/4968

2022-03-05 16:37 UTC, abhi-status commented
hey Jo! 
There is this issue of overlapping Channels in the Chat view when the user opens or closes the Online Users panel

https://user-images.githubusercontent.com/95302135/156892118-e6401daa-dc00-48c1-be19-a41c4f83b634.mp4

2022-03-07 16:23 UTC, jrainville commented
@abhi-status I fixed the issue. It was weird, but it's gone

2022-03-08 07:45 UTC, saledjenic approved these changes

2022-03-08 18:37 UTC, abhi-status approved these changes

2022-03-08 18:40 UTC, merged