fix(group-chats): wrong group name in a subsequent edit attempt
status-im/status-desktop pull request #4967
Opened 2022-03-04 15:47 UTC by stefandunca

### What does the PR do
    
Root cause: the name used as input for the naming edit field was sourced from the active group entry which is updated only hen switching the active group.

fixes #4910

### Affected areas

Group Chats

### Screenshot of functionality

### Cool Spaceship Picture

2022-03-04 15:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e968e374 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-4967/1/) | 2022-03-04 15:57:01 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220304-154806-e968e3-pr4967.dmg) |

2022-03-04 18:33 UTC, richard-ramos approved these changes

2022-03-05 17:00 UTC, abhi-status commented
Hi @stefandunca !
Is there a reason why I dont see the Windows build here ?
If this isn't intentional, could you please try and kick off the build again ?

2022-03-07 10:04 UTC, stefandunca commented
> Hi @stefandunca ! Is there a reason why I dont see the Windows build here ? If this isn't intentional, could you please try and kick off the build again ?

It was due to pushing on my fork

I fixed it

Thanks for the heads up.

2022-03-07 10:26 UTC, osmaczko requested changes
:+1: 

Please comply with commit msgs policy: https://hackmd.io/@status-desktop/B1naRjxh_/%2FMVIfVN0yQdOyhYJP0LLLKQ#-Commit-Message-Guidelines

Also, please squash commits before the merge.

2022-03-07 11:21 UTC, stefandunca commented
> +1
> 
> Please comply with commit msgs policy: https://hackmd.io/@status-desktop/B1naRjxh_/%2FMVIfVN0yQdOyhYJP0LLLKQ#-Commit-Message-Guidelines
> 
> Also, please squash commits before the merge.
Done, thanks for the findings.

2022-03-07 12:09 UTC, abhi-status approved these changes

2022-03-07 16:52 UTC, osmaczko approved these changes

2022-03-07 22:12 UTC, merged