feat(profile): add Messaging settings view in profile
status-im/status-desktop pull request #5003
Opened 2022-03-09 21:26 UTC by jrainville

Fixes #4931

![image](https://user-images.githubusercontent.com/11926403/157538367-f3a40927-2bc6-4389-8b6e-61f116a88cc2.png)
![image](https://user-images.githubusercontent.com/11926403/157538485-400e1a2d-78db-4eb7-b982-7c6d78dfac63.png)
![image](https://user-images.githubusercontent.com/11926403/157538527-e7e59360-61bf-4170-9c20-e4a3cae52232.png)
![image](https://user-images.githubusercontent.com/11926403/157538567-facbeb3b-414a-4ccd-a3dd-0fe05db5f1c0.png)
![image](https://user-images.githubusercontent.com/11926403/157538597-8ebf9921-eb13-4aeb-8a14-e20e099fc9a2.png)
![image](https://user-images.githubusercontent.com/11926403/157538631-62c1028a-59d5-4e1c-a58e-aa92d1814f6c.png)
![image](https://user-images.githubusercontent.com/11926403/157538713-bafd882f-b858-4f44-87e3-2b689ee76949.png)

Note that the Contact view is not final, it's quite an undertaking so it should be done in another PR, because this one is quite massive already

2022-03-09 21:35 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 56be3f80 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-5003/1/) | 2022-03-09 21:35:51 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220309-212629-56be3f-pr5003.dmg) |

2022-03-10 08:40 UTC, alaibe approved these changes

2022-03-10 08:40 UTC, alaibe commented on src/app_service/service/settings/dto/settings.nim
> +  echo jsonObj
oops ;)

2022-03-10 14:52 UTC, jrainville commented on src/app_service/service/settings/dto/settings.nim
> +  echo jsonObj
🤫

2022-03-11 21:47 UTC, iurimatias requested changes
The Messaging section should be in the Apps group

![](https://user-images.githubusercontent.com/176720/156066225-be3a4abb-eebb-4dd3-9aad-3a4e6c163b49.png)

2022-03-16 10:41 UTC, anastasiyaig approved these changes

2022-03-17 18:59 UTC, iurimatias approved these changes
tested

2022-03-17 18:59 UTC, merged