Feat/uri support mac
status-im/status-desktop pull request #5087
Opened 2022-03-18 12:59 UTC by saledjenic

This is till a draft PR.

What's handled, examples:

1. Browser:
`status-im://b/www.google.com`
`status-im://browser/www.google.com`

2. User profile:
`status-im://u/0x049f864a99d7a2cc0e550bf26df938fe44da58eb35a7f361c05f34a4a3ace635539ad7d4097d45d60d01f83476617c9cb0d2956a4d32212fc9f5efb9bb12102077`
`status-im://user/0x049f864a99d7a2cc0e550bf26df938fe44da58eb35a7f361c05f34a4a3ace635539ad7d4097d45d60d01f83476617c9cb0d2956a4d32212fc9f5efb9bb12102077`
`status-im://u/nastya.stateofus.eth`
`status-im://user/nastya.stateofus.eth`

3. Private message (1:1 chat):
`status-im://pm/0x04754c9bc92f7b066b3d24ba1366fd84a3e24bdc307242eeefe822132db9afe194f8a9550963f0dcb24af431649bb03eadf452f7dbaf9e128757e30d6ba5d81720`
status-im://private-`message/0x04754c9bc92f7b066b3d24ba1366fd84a3e24bdc307242eeefe822132db9afe194f8a9550963f0dcb24af431649bb03eadf452f7dbaf9e128757e30d6ba5d81720`
`status-im://pm/rabbit.stateofus.eth`
`status-im://private-message/rabbit.stateofus.eth`

2022-03-18 13:06 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | ff1fbb1e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5087/1/) | 2022-03-18 13:06:16 | ~6 min | `linux` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5087/1/consoleText) |

2022-03-23 15:35 UTC, richard-ramos approved these changes

2022-03-24 14:02 UTC, iurimatias requested changes
1

2022-03-24 14:06 UTC, iurimatias commented
I got this with safari using `status://public/test4`



https://user-images.githubusercontent.com/176720/159934084-2bc17114-d491-40d8-8010-2b2ccfb41636.mov

2022-03-24 14:11 UTC, iurimatias commented
@saledjenic see video below, rejoining same channel using deep link makes it unselectable. I cannot replicate this if using the normal join modal
https://user-images.githubusercontent.com/176720/159934988-5e44b9d8-1a40-4e4d-bff6-ded6c30014d1.mov

2022-03-25 13:42 UTC, jrainville approved these changes
Code looks good

2022-03-25 13:42 UTC, jrainville commented on src/app/modules/main/controller.nim
> +    args.groupName, args.listOfUserIds)
nit: can you add a tab here to separate the different lines

2022-03-25 13:42 UTC, jrainville commented on src/app/modules/main/module.nim
> +      i = i + 1
You can use `i.inc()`

2022-05-30 10:09 UTC, anastasiyaig commented
@saledjenic please rebase, thanks

2022-05-30 12:48 UTC, saledjenic commented
> @saledjenic please rebase, thanks

@anastasiyaig rebased again

2022-05-31 07:28 UTC, anastasiyaig commented
@saledjenic 

- `/browse/[url]` this pattern opens a browser , but does not open a page, so `status-im://browse/google.com` does not open google.com
- `status-im://u/anastasija@stateofus.eth` is opening some weirdo profile, should be support only exact ENS name like `anastasija` or `anastasija@stateofus.eth` too? 

<img width="491" alt="Screenshot 2022-05-31 at 10 07 16" src="https://user-images.githubusercontent.com/82375995/171113113-7f166985-84fb-48a4-b117-ecf23c878ecd.png">

- `status-im://community-requests/0x0271148720b640eafbe64c9b709c7e105584bb30c2602a55d0473853c4e192c938` does not open a community
- `status-im://cr/0x0271148720b640eafbe64c9b709c7e105584bb30c2602a55d0473853c4e192c938` does not open community
- `status-im://community-channel/1` or `status-im://cc/1` are not opening community with channel `1` and the channel is not shown as active

2022-05-31 07:28 UTC, anastasiyaig commented
**QA NOTE:** https://ethstatus.testrail.net/index.php?/runs/view/9309&group_by=tests:assignedto_id&group_order=asc

2022-05-31 13:03 UTC, saledjenic commented
@anastasiyaig I've checked issues you stated:

> /browse/[url] this pattern opens a browser , but does not open a page, so status-im://browse/google.com does not open google.com

This works perfectly fine, just be sure that you typed `status-im://browser/google.com`.

> status-im://u/anastasija@stateofus.eth is opening some weirdo profile, should be support only exact ENS name like anastasija or anastasija@stateofus.eth too?

This was a bug, actually we were displaying user's popup even for a public key or ens name which is not the correct one, that's fixed now.

> status-im://community-requests/0x0271148720b640eafbe64c9b709c7e105584bb30c2602a55d0473853c4e192c938 does not open a community
> status-im://cr/0x0271148720b640eafbe64c9b709c7e105584bb30c2602a55d0473853c4e192c938 does not open community

Yes, it doesn't open a community, it just sends a request to join community. If you just want to switch to a community use `c`, `cr` is for request to join community, follow [this](https://github.com/status-im/specs/pull/159/files).

> status-im://community-channel/1 or status-im://cc/1 are not opening community with channel 1 and the channel is not shown as active

Following spec, you should add community channel id, instead of `1`, it is composed of `communityId` + `chatId` that way we can know what exactly to show, otherwise we cannot do that.

2022-05-31 13:13 UTC, anastasiyaig commented
@iurimatias how user will know community chat id ? it is not visible in UI , therefore this use case is not actually live

2022-05-31 14:59 UTC, anastasiyaig commented
so the discussion about how to get chatId is still ongoing and i dont want to hold the PR because of that (since the logic is implemented anyway) . If there will be a ui ticket to show the chatId -> then it will be done separately and i will retest specific scenarios for community

2022-05-31 18:53 UTC, saledjenic commented
@iurimatias this issue is approved and tested, but I cannot merge it since you requested changes [here](https://github.com/status-im/status-desktop/pull/5087#pullrequestreview-920318199), so please either remove requested changes or feel free to merge this PR.

2022-05-31 18:54 UTC, iurimatias approved these changes

2022-05-31 18:54 UTC, iurimatias commented
@saledjenic done

2022-06-01 06:42 UTC, merged