fix(onboarding): show warning when trying to re-encrypt existing account
status-im/status-desktop pull request #5131
Opened 2022-03-23 19:53 UTC by jrainville

Fixes #5029

![image](https://user-images.githubusercontent.com/11926403/159784357-66e2d57c-d5d5-4414-8cef-9e1d7a1c412b.png)

2022-03-23 20:02 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5f0f96c7 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-5131/1/) | 2022-03-23 20:02:13 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220323-195341-5f0f96-pr5131.dmg) |

2022-03-24 07:28 UTC, saledjenic approved these changes

2022-03-24 07:28 UTC, saledjenic commented on ui/app/AppLayouts/Onboarding/views/ConfirmPasswordView.qml
> +            MessageDialog {
@jrainville don't we have some kind of Status styled message popup?

2022-03-24 13:15 UTC, noeliaSD approved these changes

2022-03-28 16:41 UTC, iurimatias requested changes
I'm not always getting the warning

2022-03-28 20:10 UTC, jrainville commented
@iurimatias fixed. Now the warning appears on entering the seed phrase. I left the one on entering password as well as a double safety.
Requesting-review again because I had to change more files.

2022-03-29 10:22 UTC, abhi-status commented
Cheers @jrainville !
I can now see this pop-up in both places.

2022-03-29 10:22 UTC, abhi-status approved these changes

2022-03-29 14:47 UTC, noeliaSD commented
@jrainville just one curious think... From code I can see the text message is written correctly with spaces after commas but look at my screenshot.. it seems it has no commas there.. is it just only my perception? I promise I haven't altered the code to make the screenshot! haha

![Screenshot 2022-03-29 at 16 39 09](https://user-images.githubusercontent.com/97019400/160638474-35f53f8a-a01d-4798-8d2e-b30ecf620f0c.png)

2022-03-29 17:04 UTC, noeliaSD commented
> @noeliaSD now sure why yours looks like that. On Linux is looks fine ![image](https://user-images.githubusercontent.com/11926403/160666120-3351e4ef-45ee-4f81-9043-6137feba8984.png)
> 
> Anyway, when we actually have a design, it might be fine then.

It was on Mac, but yes, just it seemed curious to me!

2022-03-29 17:04 UTC, noeliaSD approved these changes

2022-03-29 20:48 UTC, merged