fix(main): Close app on onboarding step
status-im/status-desktop pull request #5173
Opened 2022-03-25 09:57 UTC by borismelnik

Closes: #5170

### What does the PR do

Remove old `login` reference from `close` event

### Affected areas

Root window

2022-03-25 10:10 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 96b1a0b8 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5173/1/) | 2022-03-25 10:10:38 | ~13 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220325-095735-96b1a0-pr5173.tar.gz) |

2022-03-25 10:37 UTC, Khushboo-dev-cpp approved these changes
LGTM :)

2022-03-25 11:12 UTC, alaibe approved these changes

2022-03-25 12:47 UTC, saledjenic requested changes
@borismelnik there is a `login` component used in the line `139` here in this file, but it's not defined in this context, would be good to update that line as well, cause there is handled app closing for other than the `MacOs`.

2022-03-25 12:52 UTC, saledjenic approved these changes

2022-03-25 13:46 UTC, jrainville approved these changes

2022-03-28 18:22 UTC, iurimatias approved these changes

2022-03-28 18:23 UTC, iurimatias commented
tested

2022-03-28 18:23 UTC, merged