fix(users): user not added when joining group + only show joined users
status-im/status-desktop pull request #5277
Opened 2022-03-30 19:53 UTC by jrainville

Fixes #5202

You had to restart the app to see newly joined users in a group chat. Now they are added when they join.

**Note**: This also changes the behaviour of the user list. Only `joined` users (of a group or a community) will show in the list.
First, it fixes the weird behaviour of group chats where on creating them, the list would be empty, but on restarting, every user would be there, even if they didn't join.
Second, it also makes sense, because the user isn't actually in the group chat or community, so seeing them in the list is misleading.
I tested public chats as well, and it didn't affect them.

2022-03-30 19:55 UTC, jrainville commented on src/app/modules/main/chat_section/chat_content/users/module.nim
> +method addChatMember*(self: Module,  id: string) =
This is just the code from `onChatMembersAdded` that I moved out to this function so I can reduce duplication.

2022-03-30 20:02 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f8546919 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-5277/1/) | 2022-03-30 20:02:23 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220330-195414-f85469-pr5277.dmg) |

2022-03-31 13:32 UTC, saledjenic approved these changes

2022-03-31 13:32 UTC, saledjenic commented on src/app/modules/main/chat_section/chat_content/users/module.nim
> +  if (joined == false):
@jrainville you could just do this (somehow more natural):
```
if(not joined):
  return
```

2022-03-31 19:57 UTC, borismelnik approved these changes

2022-03-31 21:25 UTC, iurimatias requested changes
_

2022-03-31 21:31 UTC, merged