Fix duplicated chats when joining
status-im/status-desktop pull request #5340
Opened 2022-04-04 16:32 UTC by jrainville

Fixes https://github.com/status-im/status-desktop/issues/5324

The problem was that signals sometimes came faster than the "normal" flow, so we added the chat without checking first for duplication

Note: I was never able to reproduce the issue, so I'm not 100% sure if it is fixed. My VM is not fast enough to process the signal before the normal flow.
However, the guards I added should do the trick.

2022-04-04 16:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a4e9a012 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5340/1/) | 2022-04-04 16:42:44 | ~10 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220404-163222-a4e9a0-pr5340.tar.gz) |

2022-04-04 23:00 UTC, iurimatias requested changes
1. create account
2. open join modal, and join #test
3. open join modal, and join #status
4. with #status channel opened and without doing anything, wait 3-5 minutes
5. go to #test

result: #test has history of #status

2022-04-05 10:57 UTC, endulab commented
Interesting. I saw this problem in one of my previous branches. But, it seems that current master does not have this issue.
Also I can't reproduce your issue @iurimatias. I suggest checking master one more time before merging.

2022-04-05 15:15 UTC, jrainville commented
I was able to replicate the bug once in this branch. Then I rebased on master and I can no longer reproduce.
Either there was something in master that fixed it, or I'm just very unlucky (or lucky) that I can't reproduce anymore.
Let me know @iurimatias if you still have it

2022-04-07 04:53 UTC, elina2015 commented
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8919&group_by=tests:status_id&group_order=asc

The case of @iurimatias is not reproduced.

2022-04-07 04:54 UTC, elina2015 approved these changes
Tested in https://ethstatus.testrail.net/index.php?/runs/view/8919&group_by=tests:status_id&group_order=asc

2022-04-07 05:20 UTC, elina2015 commented
@jrainville I found a bug in the public chats in this PR: https://github.com/status-im/status-desktop/issues/5410 Could you kindly check it? I cannot reproduce it on master.

2022-04-07 05:22 UTC, elina2015 reviewed
Found a bug https://github.com/status-im/status-desktop/issues/5410

2022-04-07 05:22 UTC, elina2015 reviewed
The bug is found https://github.com/status-im/status-desktop/issues/5410

2022-04-07 14:09 UTC, jrainville commented
@elina2015 I couldn't reproduce your issue. I also rebased, so maybe something later in master fixed it.

2022-04-07 14:50 UTC, iurimatias commented
added test case to cover this here https://ethstatus.testrail.net/index.php?/cases/view/702173

2022-04-07 14:51 UTC, merged