feat(@desktop/onboarding): Biometrics screen updates
status-im/status-desktop pull request #5602
Opened 2022-05-03 07:36 UTC by MishkaRogachev

### What does the PR do

[x] Update text on the Biometrics screen
[ ] Update img on the Biometrics screen

### Affected areas

onboarding

### Screenshot of functionality

..in porogress

2022-05-03 07:45 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f963dca3 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-5602/1/) | 2022-05-03 07:45:06 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220503-073635-f963dc-pr5602.dmg) |

2022-05-03 07:49 UTC, alaibe approved these changes

2022-05-04 15:26 UTC, alexandraB99 requested changes

2022-05-05 07:26 UTC, saledjenic approved these changes

2022-05-05 07:26 UTC, saledjenic commented on ui/app/AppLayouts/Onboarding/views/TouchIDAuthView.qml
> +                text: qsTr("Yes, use Touch ID ")
@MishkaRogachev we don't need `" "` (space) at the end.

2022-05-05 08:53 UTC, MishkaRogachev commented on ui/app/AppLayouts/Onboarding/controls/OnboardingBasePage.qml
> +        id: backButton
Hmmm. I've just removed back button from TouchIDAuthView.qml, but button still present on GenKeyView. Is it correct?

2022-05-06 08:02 UTC, MishkaRogachev commented on ui/app/AppLayouts/Onboarding/controls/OnboardingBasePage.qml
> +        id: backButton
Fixed!

2022-05-09 20:53 UTC, iurimatias approved these changes
![Screen Shot 2022-05-09 at 4 51 50 PM](https://user-images.githubusercontent.com/176720/167496560-3852b492-3d30-4aa7-8811-1cf32ececc96.png)

biometrics still work too

2022-05-09 20:53 UTC, merged