feat(@desktop): Replace image with animation on the splash screen
status-im/status-desktop pull request #5716
Opened 2022-05-12 10:31 UTC by MishkaRogachev

Close #4984

### What does the PR do

Replace image with animation on the splash screen

### Affected areas

Spash screen

### Screenshot of functionality

![image](https://user-images.githubusercontent.com/2522130/168051272-f40bd07f-0c58-4cea-b6df-0297956a857a.png)

2022-05-12 10:35 UTC, MishkaRogachev commented
It seems that LottieAnimation in Qt does not work properly, should i use gif instead?

2022-05-12 10:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 90193f88 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5716/1/) | 2022-05-12 10:42:58 | ~11 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220512-103139-90193f-pr5716.tar.gz) |

2022-05-12 16:07 UTC, iurimatias commented
is this WIP?

https://user-images.githubusercontent.com/176720/168119860-2a76f0f0-c6c6-42ae-a7fa-525634b519a2.mov

2022-05-12 16:13 UTC, MishkaRogachev commented
> is this WIP?
> 
>  tes.mov

6 min ago was it Draft, but now you can check again ;)

2022-05-12 19:58 UTC, iurimatias requested changes
it's blank for me

2022-05-13 07:30 UTC, MishkaRogachev commented
> it's blank for me

That's strange. Maybee some issue wirh AnimationImage on MAC. I asked team to check it: https://discordapp.com/channels/@me/972849023155318824/974573458136641556

2022-05-13 07:43 UTC, endulab commented
Works for me. 

https://user-images.githubusercontent.com/61889657/168235639-22a22a5e-a9cf-4de3-8143-68a230fe9298.mov

2022-05-13 07:45 UTC, endulab commented on ui/app/mainui/SplashScreen.qml
> +    // LottieAnimation {
Do we want to keep this ?
If yes, then it would be good to add the comment why it is here.

2022-05-13 14:26 UTC, alexandraB99 commented
works for me, however the circle edges are a bit sharp black, like it has a border

2022-05-13 14:29 UTC, MishkaRogachev commented
> works for me, however the circle edges are a bit sharp black, like it has a border

I used gif converter from assest web app. IMHO we should decide how to deal with animations, probably when we move to Qt6 lottie will work properly.

2022-05-13 16:25 UTC, MishkaRogachev commented
> Everything works for me. Except I would suggest to use `scale: 0.5` on `AnimationImage` to support high-res displays. This would also require a larger original gif. But it looks much better with it (I didn't have a larger gif though)
> 
> P.S. I've just finished fixing blurry emojis, so now I have an eye on it smile
> 
> ## scale=1
>  2022-05-13.19.09.48.mov 
> ## scale=2
>  2022-05-13.19.10.34.mov

Nice idea!

2022-05-13 17:52 UTC, iurimatias approved these changes

2022-05-13 17:53 UTC, merged