fix(communities) validate privkey when importing a community
status-im/status-desktop pull request #5755
Opened 2022-05-16 13:15 UTC by richard-ramos

Fixes #5346

2022-05-16 13:20 UTC, PascalPrecht approved these changes

2022-05-16 13:26 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b334f07e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5755/1/) | 2022-05-16 13:26:53 | ~10 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220516-131606-b334f0-pr5755.tar.gz) |

2022-05-16 16:35 UTC, osmaczko approved these changes

2022-05-18 09:49 UTC, endulab requested changes

2022-05-18 09:49 UTC, endulab commented on ui/app/AppLayouts/Chat/popups/community/AccessExistingCommunityPopup.qml
> +        return communityKey.length === bytes32Len && Utils.isHex(communityKey) && Utils.startsWith0x(communityKey)
I think that checking length == 66 should be moved to Utils.qml. There are a lot of functions with such checks, eg. isPrivateKey(). We should keep these numbers (66, 64, 42) in one place. So I suggest adding a new function, eg. Utils.isCommunityKey().

2022-05-19 07:20 UTC, endulab approved these changes

2022-05-25 04:32 UTC, elina2015 approved these changes
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9267&group_by=tests:status_id&group_order=asc with light and dark mode

2022-05-25 18:01 UTC, merged