fix(CreateChatView): Members should show online status
status-im/status-desktop pull request #5758
Opened 2022-05-16 15:50 UTC by alexandraB99

Closes #5625
Depends on: https://github.com/status-im/StatusQ/pull/676

### What does the PR do
Fixes members list should show online status in create new DM/group chat

### Affected areas
create new DM/group chat view

### Screenshot of functionality
TBD

2022-05-16 16:00 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1787423d | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-5758/1/) | 2022-05-16 16:00:08 | ~9 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220516-155022-178742-pr5758.tar.gz) |

2022-05-16 16:19 UTC, osmaczko approved these changes

2022-05-16 16:19 UTC, osmaczko commented on ui/app/AppLayouts/Chat/views/CreateChatView.qml
> +            }
```suggestion
            ringSpecModel: () => Utils.getColorHashAsJson(pubKey)
```

2022-05-16 17:59 UTC, richard-ramos approved these changes

2022-05-17 01:31 UTC, elina2015 requested changes
@alexandraB99 hey,  I tested on MacOS and the contacts are shown offline in the list, while they are online:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/14942081/168709000-80498738-707e-4516-810a-cb8d28d8792d.png">
<img width="909" alt="image" src="https://user-images.githubusercontent.com/14942081/168709041-22654499-3424-4a0b-bda3-333fe0dd582c.png">
 Could you kindly check?

2022-05-18 12:25 UTC, alexandraB99 commented
> @alexandraB99 hey, I tested on MacOS and the contacts are shown offline in the list, while they are online:
> <img alt="image" width="895" src="https://user-images.githubusercontent.com/14942081/168709000-80498738-707e-4516-810a-cb8d28d8792d.png">
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/14942081/168709041-22654499-3424-4a0b-bda3-333fe0dd582c.png">
> Could you kindly check?

@elina2015 this seems to be a different/more general issue https://github.com/status-im/status-desktop/issues/5798

2022-05-19 08:44 UTC, noeliaSD approved these changes

2022-05-19 10:45 UTC, merged