fix(Profile): ContactsView layout and scrolling issues
status-im/status-desktop pull request #6001
Opened 2022-06-03 15:42 UTC by alexandraB99

Closes #5876

### What does the PR do
Fixes ContactsView in profile settings was not behaving correctly when it comes to layout and scrolling

### Affected areas
ContactsView

### Screenshot of functionality
https://user-images.githubusercontent.com/31625338/171897988-4ebee2c1-87e8-4c58-b8c4-6a1467114cba.mov

2022-06-03 15:44 UTC, alexandraB99 commented
@PascalPrecht , @endulab please check on this...I don't have many contacts ( :'( ) so the video is recorded with mock data. Let me know if something like this could work!

2022-06-03 15:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 383d2dcf | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-6001/1/) | 2022-06-03 15:53:10 | ~10 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220603-154308-383d2d-pr6001.tar.gz) |

2022-06-07 07:09 UTC, endulab commented
@alexandraB99 Scroll areas in scroll areas has been always confusing to me.
IMHO, the best option in this case is to have one proxy model and one scroll area - one tree view with sections.
But this will require changes in the model/logic.
On the movie you attached we have 2 lists: Identity Verified Contacts and Contacts. The first one is static (it does not have scroll, right ?), the second one is scrolling. What about making the second view also static. And have scroll for both lists. I am attaching a screenshot which describes what I mean:
![image](https://user-images.githubusercontent.com/61889657/172317399-22781d50-9789-4edc-80ce-df36af55415a.png)

The solution here is much better than what we have now. So, if you don't want to play with it, still worth to merge it. Good job :)

2022-06-07 09:42 UTC, alexandraB99 commented
> @alexandraB99 Scroll areas in scroll areas has been always confusing to me. IMHO, the best option in this case is to have one proxy model and one scroll area - one tree view with sections. But this will require changes in the model/logic. On the movie you attached we have 2 lists: Identity Verified Contacts and Contacts. The first one is static (it does not have scroll, right ?), the second one is scrolling. What about making the second view also static. And have scroll for both lists. I am attaching a screenshot which describes what I mean: ![image](https://user-images.githubusercontent.com/61889657/172317399-22781d50-9789-4edc-80ce-df36af55415a.png)
> 
> To recap. The solution you propose in this pr is much better than what we have now. So, if you don't want to play with it, still worth to merge it. Good job :)

@endulab in the video attached the first list has only 4 entries so no need to scroll. the second list has more entries than available space and thus it scrolls. the overall content scrolls by default, the lists are different. so we can either increase the overall content's contentHeight to scroll more down or keep what's proposed here.

2022-06-09 07:54 UTC, endulab requested changes

2022-06-09 07:54 UTC, endulab commented on ui/app/AppLayouts/Profile/views/ContactsView.qml
> +                    id: vrerifiedContacts
Probably you want "verifiedContacts"

2022-06-09 07:54 UTC, endulab commented on ui/app/AppLayouts/Profile/views/ContactsView.qml
> +                            (stackLayout.height-vrerifiedContacts.contactsListHeight)
Probably you want "verifiedContacts"

2022-06-09 07:54 UTC, endulab commented on ui/app/AppLayouts/Profile/test.qml
> +import QtQuick 2.0
Is this file needed in this pr ?

2022-06-09 07:55 UTC, endulab commented
@alexandraB99 I really like the new video. I added some minor comments to the pr.

2022-06-09 12:23 UTC, alexandraB99 commented on ui/app/AppLayouts/Profile/views/ContactsView.qml
> +                            (stackLayout.height-vrerifiedContacts.contactsListHeight)
fixed

2022-06-09 12:23 UTC, alexandraB99 commented on ui/app/AppLayouts/Profile/test.qml
> +import QtQuick 2.0
not at all, removed! :D

2022-06-09 12:23 UTC, alexandraB99 commented on ui/app/AppLayouts/Profile/views/ContactsView.qml
> +                    id: vrerifiedContacts
fixed, updated

2022-06-10 09:41 UTC, endulab approved these changes

2022-06-10 20:08 UTC, elina2015 commented
@alexandraB99hey, could you check few issues that I found:
1. The Contacts tab doesn't look good when I received a contact request (The double title 'Contacts' appeared):
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/14942081/173137329-9e002553-8983-4aa2-809e-d67392c7e011.png">
2. The title 'Received' is shown very close to other titles on the Pending requests tab:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/14942081/173137876-ab60a659-a26f-429c-bc55-a975cd6f6905.png">
3. The title 'Sent' is shown very close to other titles after I accepted all contact requests:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/14942081/173138389-439aac35-0609-4b1f-895d-dbab359a0d66.png">
4. Default images for profiles are not shown on the Contacts tab:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/14942081/173138653-fcced0d6-d425-499a-9489-327bc242aa16.png">
5. Pending requests tab is empty when I received a lot of incoming requests
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/14942081/173140758-eac4e140-2752-4283-ad25-114b8d674845.png">
6. The Pending requests tab is empty when I accepted all incoming requests but have some sent pending requests ans switching between tabs:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/14942081/173141279-136d8b2c-9f29-4d5f-b668-0a09231de5a2.png">
7. The Contacts tab looks incorrect when I have a lot of contacts there:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/14942081/173142186-5710d8e9-da4b-465b-b753-6dfa66f3da93.png">

2022-06-17 15:45 UTC, alexandraB99 commented
@elina2015 pushed fixes, so please have a second look. As about the scroll bar is because when the list has more (hidden) items, we show always the list's scrollbar so that the user is aware that there is more. The bigger scrollbar refers to the entire content. see video:
https://user-images.githubusercontent.com/31625338/174332231-88e9dff0-c45f-4f25-a5f6-ca7a300090ed.mov

2022-06-21 02:40 UTC, elina2015 commented
@alexandraB99 hey, I tested and the scroll for the requests is not scrolled properly. Please check the attached video:
https://user-images.githubusercontent.com/14942081/174704761-56d0bdd7-3866-4419-86ca-1ec5c8ab99da.mov

2022-06-22 00:46 UTC, elina2015 commented
@alexandraB99 I tested the rebased build and the issue with scrolling is till reproduced. Could you kindly check? https://drive.google.com/file/d/1UazINkuphmnhBbl1lJ9aNYqlXmwZoDsT/view?usp=sharing
My test environment: macOS Monterey 12.3 Beta (21E5227a)

2022-06-22 18:55 UTC, alexandraB99 commented
@elina2015 pushed some updates! please check again 👯

2022-06-22 19:57 UTC, elina2015 commented
@alexandraB99 hey, I tested the updates, but unfortunately the issue is till reproduced: https://drive.google.com/file/d/12sIyMqe8TMtLw8OmpnaD4Qqz_7euiPX0/view?usp=sharing

2022-06-23 10:13 UTC, alexandraB99 commented
> @alexandraB99 hey, I tested the updates, but unfortunately the issue is till reproduced: https://drive.google.com/file/d/12sIyMqe8TMtLw8OmpnaD4Qqz_7euiPX0/view?usp=sharing
@elina2015 thanks for that! pushed another update so please have a second look :)

2022-06-24 00:50 UTC, elina2015 approved these changes
Tested and Approved

2022-06-24 08:41 UTC, Khushboo-dev-cpp approved these changes

2022-06-24 12:24 UTC, merged