fix(GroupChatPanel): drop down was showing empty entries
status-im/status-desktop pull request #6008
Opened 2022-06-06 14:21 UTC by alexandraB99

Closes #5955

### What does the PR do

### Affected areas

### Screenshot of functionality

### Cool Spaceship Picture

<!-- optional but cool ->

2022-06-07 11:41 UTC, PascalPrecht approved these changes

2022-06-08 08:53 UTC, noeliaSD requested changes
2 comments:
- In latest master and in current spec of the group chat (in brief it will change but currently, until the admin is not displayed readonly), admin will not be displayed in the list of members of the group. I've been quickly reviewing the changes you made but I cannot see which is the difference that makes that now the admin is also shown in the group panel list.
- Please, see the behavior I'm getting when testing.. I'm expecting to see the dropdown with options but after removing the members in the list, the dropdown doesn't show the expected contacts to be added again:

https://user-images.githubusercontent.com/97019400/172574520-14cfc76e-e9f8-491b-9a9b-15af928fd882.mov

2022-06-08 08:53 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/panels/GroupChatPanel.qml
> +         onTextChanged: sortModel(d.buildContactsModel())
Why do we need here to rebuild again the `contactModel` list (this list should not change)?

2022-06-10 15:21 UTC, noeliaSD approved these changes
Retested!

2022-06-17 08:24 UTC, Hbouaz approved these changes
Passed testing

2022-06-17 10:55 UTC, merged