fix(@wallet): Always display snt/eth/dai
status-im/status-desktop pull request #6284
Opened 2022-06-29 11:23 UTC by alaibe

fixes #6160

2022-06-29 11:28 UTC, caybro requested changes

2022-06-29 11:28 UTC, caybro commented on ui/imports/shared/controls/AssetDelegate.qml
> +        readonly property variant alwaysVisible : ["ETH", "SNT", "DAI", "STT"]
Please use `var`; `variant` is deprecated and much slower

2022-06-30 07:57 UTC, caybro approved these changes

2022-06-30 14:55 UTC, jrainville approved these changes

2022-07-04 08:34 UTC, Khushboo-dev-cpp approved these changes

2022-07-04 09:12 UTC, merged