Fix/6104/backup community key field
status-im/status-desktop pull request #6296
Opened 2022-06-29 20:41 UTC by osmaczko

fixes: https://github.com/status-im/status-desktop/issues/6104

2022-06-29 20:44 UTC, caybro commented on ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
> +            property string elidedPkey: root.privateKey.substring(0, 15) + "..." + root.privateKey.substring(root.privateKey.length - 16)
`readonly`

2022-06-29 20:44 UTC, caybro commented
Otherwise looks nice

2022-06-29 20:51 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b9672131 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-6296/1/) | 2022-06-29 20:51:08 | ~9 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220629-204124-b96721-pr6296.tar.gz) |

2022-06-30 07:13 UTC, osmaczko commented
> Otherwise looks nice

@caybro Thanks, could you please approve?

2022-06-30 08:03 UTC, caybro approved these changes

2022-07-01 08:04 UTC, endulab requested changes

2022-07-01 08:04 UTC, endulab commented on ui/app/AppLayouts/Chat/popups/community/TransferOwnershipPopup.qml
> +            readonly property string elidedPkey: root.privateKey.substring(0, 15) + "..." + root.privateKey.substring(root.privateKey.length - 16)
In Utils.qml there is a funtion getElidedCompressedPk with very same funtionality. Can you reuse it ?

2022-07-01 10:29 UTC, Hbouaz approved these changes
Passed testing

2022-07-05 07:45 UTC, endulab approved these changes

2022-07-05 15:08 UTC, merged