fix(@desktop): enable the hover effects by default
status-im/status-desktop pull request #6335
Opened 2022-07-04 11:36 UTC by caybro

Close #6254

- since Qt 5.xy, hover is not enabled by default for QQC2, so enable it
unconditionally as we are a desktop app anyway
- this fixes several hover effects being broken, mostly for builtin
components like MenuItem and some buttons (eg. the leftmost NavBar)
where we haven't enabled those with `hoverEnabled: true` explicitely
- additionally, provide a tooltip for the default "chat" section which
doesn't seem to supply its own (unlike the other sections)

### What does the PR do

Fixes mouse over (hover) effects being (mostly) broken

### Affected areas

All areas of status-desktop

### Screenshot of functionality
![Snímek obrazovky z 2022-07-04 12-41-28](https://user-images.githubusercontent.com/5377645/177146645-0dbb08b3-166d-479c-8810-9825fbe1ef74.png)
![Snímek obrazovky z 2022-07-04 12-42-10](https://user-images.githubusercontent.com/5377645/177146649-035e9e51-29a3-4c95-8c8e-065c47f8fe81.png)

2022-07-04 11:48 UTC, PascalPrecht requested changes
The actual fix is of this commit is awesome!
Didn't know this existed. Setting `hoverEnabled` explicitly is quite annoying.

Bonus points if the fix for the tooltip is not in the commit that fixes the hover (no biggie if you don't feel like it)

2022-07-04 11:51 UTC, caybro commented on ui/app/mainui/AppMain.qml
> +                              qsTrId("chat")
Alright, sure will fix it. It's just that the existing code still contains a _lot_ of `qsTrid()` instances... worth cleaning that up at once?

2022-07-04 11:51 UTC, osmaczko approved these changes
:+1:

2022-07-04 11:52 UTC, caybro commented on ui/app/mainui/AppMain.qml
> +                              qsTrId("chat")
It's just empty, dunno why :/ Not enough nim-fu to find the correct cause though

Will split this into 2 commits, no prob

2022-07-04 11:54 UTC, osmaczko commented on ui/app/mainui/AppMain.qml
> +                              qsTrId("chat")
> Alright, sure will fix it. It's just that the existing code still contains a _lot_ of `qsTrid()` instances... worth cleaning that up at once?

https://github.com/status-im/status-desktop/pull/5327 will be merged after the release

2022-07-04 12:06 UTC, caybro commented on ui/app/mainui/AppMain.qml
> +                              qsTrId("chat")
@PascalPrecht fixed and split into 2 commits

2022-07-04 12:06 UTC, caybro commented on ui/app/mainui/AppMain.qml
> +                              qsTrId("chat")
@osmaczko fixed (using qsTr())

2022-07-04 12:39 UTC, alaibe approved these changes

2022-07-04 15:10 UTC, jrainville requested changes
Nice fixes. The fix for the tooltip should be done in Nim however. I don't blame you for not knowing, it's not clear

2022-07-04 15:41 UTC, caybro commented on ui/app/mainui/AppMain.qml
> +                tooltip.text: model.name || qsTr("Chat")
Alright, fixed and (still) works! :)

2022-07-04 15:42 UTC, jrainville approved these changes
Good job

2022-07-05 07:55 UTC, PascalPrecht approved these changes
Great job

2022-07-05 08:18 UTC, caybro commented
@noelia-santos can you please give this one a test too please? TIA

2022-07-05 10:00 UTC, Hbouaz approved these changes
nice one

2022-07-05 10:04 UTC, merged