fix(Communities): Fix channels reordering
status-im/status-desktop pull request #6371
Opened 2022-07-05 16:30 UTC by borismelnik

Closes: #6292

### What does the PR do

Add `reorder` method to `SubModel` and remove prepended communityID to chatID.

### Affected areas

Communities

2022-07-05 16:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | 6d8f73cb | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-6371/1/) | 2022-07-05 16:33:10 | ~2 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-6371/1/consoleText) |

2022-07-07 04:50 UTC, elina2015 commented
@borismelnik hey, the owner reordered the channels and see them like this:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/14942081/177693214-485a2f32-7b75-440e-ab01-4078ec9a8cb0.png">
But the member of the community can see the channels by another way:
<img width="420" alt="image" src="https://user-images.githubusercontent.com/14942081/177693802-4e7be44d-19c6-49c4-bd1a-5e91a4818771.png">

Could you kindly check?

2022-07-28 13:01 UTC, micieslak requested changes

2022-07-28 13:01 UTC, micieslak commented on src/app_service/service/community/service.nim
> +              self.events.emit(SIGNAL_COMMUNITY_CHANNEL_REORDERED, CommunityChatOrderArgs(communityId: updatedCommunity.id, chatId: chat.id, categoryId: chat.categoryId, position: chat.position))
`fullChatId` doesn't work with `self.chatService.getChatById`, plain `chat.Id` is expected as well. When `fullChatId` is used, chat details is not found and chatService is not updated. Error is msg is emitted to the output as well.

2022-08-08 06:42 UTC, elina2015 approved these changes
Tested and approved

2022-08-08 13:05 UTC, micieslak commented
resolved in https://github.com/status-im/status-desktop/pull/6840

2022-08-08 13:05 UTC, closed without merging