fix(contacts): remove isContact, use isMutualContact or isAdded indead
status-im/status-desktop pull request #6375
Opened 2022-07-06 16:55 UTC by jrainville

Fixes #6220

Fixes the issue with the mutual contact icon showing when just added.
It also does a huge cleanup of the codebase to remove isContact and replace it with either isAdded, when we care only about if we added, or isMutualContact if we want the contact to be mutual
Also fixes an issue with the MessageContextMenu not reflecting the added state correctly.

Asking for QA testing on this one, since it touches contacts all over the app. I made sure to double check my changes to make sure to use isAdded and isMutualContact appropriately, but the reason why I did this change is because `isContact` was used in both contexts, so it was confusing.
Anyway, all that to say, make sure the contact list, states and other interactions still work as expected.

2022-07-07 09:09 UTC, osmaczko requested changes
Thanks for fixing that :+1: 

Please change all occurrences of `isMutualContact` back to `isContact` (democracy here :D)

2022-07-07 09:09 UTC, osmaczko commented on src/app/modules/shared_models/user_item.nim
> +    isMutualContact: bool
```suggestion
    isContact: bool
```

2022-07-07 09:09 UTC, osmaczko commented on src/app/modules/shared_models/user_model.nim
> +    IsMutualContact
```suggestion
    IsContact
```

2022-07-07 09:09 UTC, osmaczko commented on ui/app/AppLayouts/Chat/panels/ChatRequestMessagePanel.qml
> +    property bool isContactAdded
```suggestion
    property bool isUserAdded
```

2022-07-07 09:09 UTC, osmaczko commented on ui/app/AppLayouts/Chat/views/ChatColumnView.qml
> +    property bool isContactAdded: root.contactDetails.isAdded
```suggestion
    property bool isUserAdded: root.userDetails.isAdded
```

2022-07-07 09:09 UTC, osmaczko commented on ui/app/AppLayouts/Chat/views/ChatView.qml
> +            if (Utils.getContactDetailsAsJson(pk).isAdded) {
```suggestion
            if (Utils.getUserDetailsAsJson(pk).isAdded) {
```
we should probably create a separate task to fix status-desktup codebase naming in regards to contact vs user

2022-07-08 07:13 UTC, osmaczko commented
> @osmaczko updated. 

Great, thank you.

> getContactDetailsAsJson and contactDetails will be updated in another PR. The number of changes here is already pretty high..

Of course, I haven't expected anything else! -> "[we should probably create a separate task to fix status-desktup codebase naming in regards to contact vs user](https://github.com/status-im/status-desktop/pull/6375#discussion_r915640976)"

2022-07-09 03:56 UTC, elina2015 approved these changes

2022-07-11 08:21 UTC, noeliaSD approved these changes

2022-07-11 13:34 UTC, merged