test(onboarding):  12 18 and 24 seed phrase tests
status-im/status-desktop pull request #6399
Opened 2022-07-10 15:04 UTC by OlufemiAdeOlusile

### What does the PR do
This PR tests positive and negative flows for 12, 18, 24 seed phrase via Squish
https://github.com/status-im/status-desktop/issues/6274
https://github.com/status-im/status-desktop/issues/6275
https://github.com/status-im/status-desktop/issues/6276

### Affected areas

Depends on Icon change (include Object Name) via Status Q https://github.com/status-im/StatusQ/pull/761

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2022-07-10 15:13 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 403a7455 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6399/1/) | 2022-07-10 15:13:42 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220710-150501-403a74-pr6399.dmg) |

2022-07-11 07:58 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        Scenario Outline: User cannot sign up with wrong password format
Identation

2022-07-11 07:58 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        Scenario Outline: User cannot finish Sign Up and Sign In process with wrong password
Identation

2022-07-11 07:58 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        Scenario: User signs up with imported 12 seed phrase
Identation

2022-07-11 08:05 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        When the user opens app settings screen
Not sure why opening settings and wallet section is part of sign up suite

2022-07-11 08:07 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        And user inputs the following <wrongpassword> with ui-component mainWindow_inputValue_StyledTextField
Could the `ui-component` name be more specific? By reading this, I'm not sure which component are you referring and in which page are you.

2022-07-11 08:14 UTC, noeliaSD requested changes
I've tryied to run the scenarios related to seed phrases and I get the following test failures (same happens with `chatFlow` once the user lands into the app, after the onboarding process):

![Screenshot 2022-07-11 at 10 09 00](https://user-images.githubusercontent.com/97019400/178218767-00b05b5e-94ab-4ca6-8ce5-bd27ff4095b5.png)

https://user-images.githubusercontent.com/97019400/178218751-5601e3d2-08a8-491c-8532-c62d874ba36a.mov

2022-07-11 12:01 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        When the user opens app settings screen
Sorry, I don't have access to `TestRail`.. so, is it part of `SignUp` test case?

2022-07-11 12:02 UTC, noeliaSD commented on test/ui-test/testSuites/suite_status/tst_statusSignUp/test.feature
> +        Then the 24 seed phrase address is 0x28cf6770664821a51984daf5b9fb1b52e6538e4b displayed in the wallet
Not sure to undertand why this cannot be data-driven. Could you clarify more?

2022-07-13 11:10 UTC, iurimatias approved these changes

2022-07-15 06:14 UTC, noeliaSD approved these changes
With the new changes the scenario run correctly.

2022-07-15 08:27 UTC, merged