fix(StatusTagSelector): corrected font size in to label
status-im/status-desktop pull request #6414
Opened 2022-07-12 09:06 UTC by alexandraB99

Closes #6349

### What does the PR do

### Affected areas

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2022-07-12 09:18 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 214dec69 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6414/1/) | 2022-07-12 09:18:58 | ~12 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220712-090654-214dec-pr6414.dmg) |

2022-07-12 10:38 UTC, caybro requested changes
Need a screenshot :)

2022-07-12 12:10 UTC, saledjenic approved these changes

2022-07-14 08:28 UTC, alexandraB99 commented
StatusQ change already in master

2022-07-14 08:28 UTC, closed without merging