Usage of `StatusMessage`
status-im/status-desktop pull request #6508
Opened 2022-07-18 14:57 UTC by igor-sirotin

Requires: 
- https://github.com/status-im/StatusQ/pull/752
- https://github.com/status-im/StatusQ/pull/790
- https://github.com/status-im/StatusQ/pull/815
- https://github.com/status-im/status-desktop/pull/6736

Fixes:
- https://github.com/status-im/status-desktop/issues/6124
- https://github.com/status-im/status-desktop/issues/6334
- https://github.com/status-im/status-desktop/issues/6968
- https://github.com/status-im/status-desktop/issues/6851
- https://github.com/status-im/status-desktop/issues/6940

### What does the PR do

* Use the new `StatusMessage` component from StatusQ library.
* `MessageView`, `StatusChatInput` and some other related code refactoring.

### Affected areas

chat

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/25482501/181288720-b71ad6ac-5415-4de2-9332-45b7f04cd50d.mov

## Features checklist

1. Content
    * Message with text
        - [x] Text
        - [x] Highlight user mentions
        - [x] Highlight links
        - [x] Long message "Read more"
        - [x] Edited message badge
    * Image message
        - [x] show image (only works with sent images; not working with received from `dogooding/phase-5`)
        - [x] image click to enlarge
    - [x] Sticker
    - [x] Emoji
    - [x] Automatic link preview
    - [x] Transaction message
should work, can't check because of https://github.com/status-im/status-desktop/issues/6617
    - [x] Invitation message
1. Actions
    * Message reactions
        - [x] Show message reactions
        - [x] Toggle reaction
        - [x] Add reaction
    * Quick actions
        - [x] Add reaction
        - [x] Reply
        - [x] Edit
        - [x] Delete with confirmation
        - [x] Delete without confirmation
        - [x] Pin / Unpin
    * Clicks
        - [x] Profile image
        - [x] Profile name
        - [x] Link
        - [x] Profile link
        - [x] Message right click
        - [x] Image right click
        - [x] Sticker click (open sticker pack)
1. Pinned message
    - [x] highlight
    - [x] pinned by "user" note
1. Reply
    - [x] highlight
    - [x]  from
    - [x] content
    - [x] Profile name click (wasn't done previously) - [Design link](https://www.figma.com/file/MtAO3a7HnEH5xjCDVNilS7/%F0%9F%8E%A8-Design-System-%E2%8E%9C-Desktop?node-id=1907%3A170642)
1. Message details
    * Sender 
        - [x] Profile image / 2-letters-icon
        - [x] Is contact
        - [x] ENS name
        - [x] Old name
        - [x] Trust indicator
        - [x] `You` when current user is the message sender 
1. Other features
    - [x] Message editing 
    - [x] Chat top items (user, "load more", ...)
    - [x] Message with mentions highlight
    - [x] Timestamp
    - [x] `hasExpired`
    - [x] `shouldRepeatHeader`: Hide sender when multiple in a row
    - [x] `isHovered`, `isActive`
    - [x] `DateGroup`
    * Scroll to message
        - [x] `MessageFoundAnimation`
        - [x] Scroll to bottom — fixed (wasn't actually working on master)
        - [ ] Jump to message — ⚠️ not working on master, open a bug later
    - * Refactor click handler
        - [ ] Minimize arguments count (currently 8) — ⚠️ Decided to do this in a separate task, will link an issue here
        - [x] Remove `setXPosition` functions, auto-position to parent by `popup()` call
        
## Before-merge checklist
- [x] Bind to `MessageView` properties instead of `model` ❗
- [x] Check all usages of `MessageView`
    - [x] `ChatMessagesView`
    - [x] `PinnedMessagesPopup`
    - [x] `AppearanceView`
    - [x] `ContactVerificationRequestPopup`
    - [x] `ProfileView`
    - [ ] `ActivityCenterMessageComponentView` — ⚠️  failed to test, no notifications received
- [ ] Remove legacy `MessageView` properties — ⚠️ Mainly removed, decided to finish in a separate task

2022-07-18 15:06 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a2209d61 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6508/1/) | 2022-07-18 15:06:01 | ~8 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220718-145744-a2209d-pr6508.dmg) |

2022-07-23 15:53 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/branches/macos/PR-6508#9](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6508/9/) :small_blue_diamond: ~10 min :small_blue_diamond: 95b9a895 :small_blue_diamond: [:package: macos package](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-220723-154347-95b9a8-pr6508.dmg)

2022-07-23 15:54 UTC, status-im-auto commented
#### :heavy_check_mark: [status-desktop/branches/linux/PR-6508#9](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-6508/9/) :small_blue_diamond: ~11 min :small_blue_diamond: 95b9a895 :small_blue_diamond: [:package: linux package](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-Desktop-220723-154347-95b9a8-pr6508.tar.gz)

2022-07-27 17:51 UTC, jrainville reviewed
Very goods work. I think there is some small cleaning up to do, but then it's good.

2022-07-27 17:51 UTC, jrainville commented on src/app/modules/main/chat_section/chat_content/messages/module.nim
> +    false
Could you add the name of the property for clarity. In this case, it would be `ensVerified = false` if I'm not mistaken

2022-07-27 17:51 UTC, jrainville commented on src/app/modules/main/chat_section/chat_content/messages/module.nim
> +    false
Same here

2022-07-27 17:51 UTC, jrainville commented on ui/imports/shared/status/StatusChatInput.qml
> +                    //                stickerData: sticker
Will this be addressed in this PR or another?

2022-07-27 17:51 UTC, jrainville commented on ui/imports/shared/views/chat/MessageView.qml
> +                        //                        cancelBtn.clicked()
Leftover?

2022-07-27 17:51 UTC, jrainville commented on ui/imports/shared/views/chat/MessageView.qml
> +                    //                    saveBtn.clicked(null)
Leftover

2022-07-27 17:51 UTC, jrainville commented on ui/imports/utils/Utils.qml
>      function getMessageWithStyle(msg, isCurrentUser, hoveredLink = "") {
Can we remove it now?

2022-07-28 08:03 UTC, caybro reviewed
Just some minor blurbs, otherwise very nice cleanup!

2022-07-28 08:03 UTC, caybro commented on ui/imports/utils/Constants.qml
> +    // WARNING: Remove later. Moved to StatusQ.
Time to drop it?

2022-07-29 06:39 UTC, osmaczko approved these changes
You've done a lot of good work here :superhero:

2022-07-29 06:39 UTC, osmaczko commented on ui/app/AppLayouts/Chat/views/ChatContentView.qml
> +            Layout.preferredHeight: chatInput.implicitHeight + chatInput.anchors.leftMargin + chatInput.anchors.rightMargin
Looks wrong that height is obtained using left and right margin (instead of top and bottom) :thinking:

2022-07-29 06:39 UTC, osmaczko commented on ui/imports/shared/controls/chat/UserImage.qml
> -    property var messageContextMenu
:+1: that was not the place for `messageContextMenu` as `UserImage` is also used in different contexts than the message view, thanks for removing it from here

2022-07-29 06:39 UTC, osmaczko commented on ui/imports/shared/views/chat/MessageView.qml
> +            ]
That's strange we don't use the same emojis for reactions as these we send in the chat message (twemoji). I couldn't find designs for reactions, do you have the link maybe?

2022-07-29 10:35 UTC, osmaczko commented on ui/imports/shared/views/chat/MessageView.qml
> +            ]
seems it matches the design :eyes: thanks for finding the link

2022-07-29 11:53 UTC, MishkaRogachev approved these changes
Cool! So much work and code quality good!

2022-07-29 15:17 UTC, jrainville approved these changes

2022-08-01 09:28 UTC, caybro approved these changes

2022-08-10 10:10 UTC, glitchminer commented
### Issues found

#### Notes
- Send/Receive chat issues to be addressed by: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6508/25/

---
#### 1. OPEN Margin on large text is less than on master
Expected
![image](https://user-images.githubusercontent.com/50769329/183866355-bc9f45f2-222a-4f50-966f-d841df338a8e.png)

Actual
![image](https://user-images.githubusercontent.com/50769329/183866626-4e4241a8-8b96-47f6-9727-677a94853328.png)

----
#### 2. OPEN User mentions are not highlighted in chat (also in master)

Actual
![image](https://user-images.githubusercontent.com/50769329/183866942-f118c56c-c04a-4f61-8732-8ac7b02c7177.png)

----
#### 4. OPEN Chat messages displaying out of order (to be migrated to new PR or closed as duplicate)

Actual
![2022-08-09_17-22-43 (1)](https://user-images.githubusercontent.com/50769329/183867604-9a3f543f-45aa-42c3-8a06-e9d95798ddb9.gif)

----
#### 5. OPEN Application crash on SAVE after editing message 
Actual
![2022-08-10_10-35-06 (1)](https://user-images.githubusercontent.com/50769329/183869192-bbec3d38-f7bb-4990-a7b7-b7f6a9b23c0b.gif)

----
#### 6. OPEN Application crash on CANCEL after editing message 
Similar to 5.

----
#### 7. OPEN Timestamps not displaying time
Actual
![image](https://user-images.githubusercontent.com/50769329/183871224-9a6ba4e1-8af5-48d0-aa3b-39e0d7efef8e.png)

----
#### 8. OPEN Text too close to margin on left in chat input box
Actual
![image](https://user-images.githubusercontent.com/50769329/183871570-d09c2567-e985-49f5-9d52-3e44ed0af303.png)

----
#### 9. OPEN Pasted text has a white background in message box
Actual
![image](https://user-images.githubusercontent.com/50769329/183873401-3f723b5f-61d2-4793-be6d-df4c3b12d35a.png)

----
#### 10. OPEN Activity center not displaying activity (migrate to new PR or close as duplicate)

---
#### Test info
Build: https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6508/25/
OS: Mac

2022-08-10 11:08 UTC, glitchminer commented
Updated. Added issue 11. https://github.com/status-im/status-desktop/pull/6508#issuecomment-1210458594

2022-08-15 11:04 UTC, glitchminer commented
@igor-sirotin, thanks for the update. Fixed items have now been reviewed and the issues found list has been updated: https://github.com/status-im/status-desktop/pull/6508#issuecomment-1210458594

2022-08-16 07:50 UTC, caybro commented
@igor-sirotin fix the conflicts and let's merge this :)

2022-08-16 11:00 UTC, glitchminer commented
> @igor-sirotin fix the conflicts and let's merge this :)

@caybro Please note 5 bugs still have open status. https://github.com/status-im/status-desktop/pull/6508#issuecomment-1210458594

2022-08-17 14:18 UTC, micieslak requested changes
I discovered sth like that:

https://user-images.githubusercontent.com/20650004/185157667-f096156f-1fba-439d-8303-be1df0971f7c.mp4

Messages are misaligned just after app start. It doesn't appear on current master.

2022-08-17 16:56 UTC, glitchminer commented
Updated found issues https://github.com/status-im/status-desktop/pull/6508#issuecomment-1210458594

All now addressed except for item 12 just added. Was able to reproduce behaviour found by @micieslak here https://github.com/status-im/status-desktop/pull/6508#pullrequestreview-1075821558

2022-08-17 21:01 UTC, glitchminer commented
Hi @igor-sirotin, issue 12 now seems resolved but a similar problem is now appearing in long messages or larger images. Please refer to the screen recording below. Is this related to 12 or better raised as a separate issue?

https://user-images.githubusercontent.com/50769329/185240792-6eaff411-7258-4708-8f13-256df427575f.mov

https://user-images.githubusercontent.com/50769329/185240949-0d2d519f-7a83-4eab-95dc-41466497ad47.mov

2022-08-18 21:25 UTC, glitchminer commented
### Issue Found

@igor-sirotin, 12 is now resolved! 👍 

New issues tracking comment for clarity. Issues in previous https://github.com/status-im/status-desktop/pull/6508#issuecomment-1210458594 are now addressed, either fixed or moved to new issues. 3 issues found in this cycle:

---
#### 13. OPEN Formatting on pinned messages (addressed later by https://github.com/status-im/status-desktop/issues/6851 ?)

![image](https://user-images.githubusercontent.com/50769329/185496131-60af72cb-a329-4702-bb7a-b587bcd25c0d.png)
![image](https://user-images.githubusercontent.com/50769329/185496196-e34d59b3-5802-4bf3-a71c-9cc00f86ab1a.png)

---
#### 14. OPEN Pinned message limit not reseting after removing pins (showing max at 2)
![image](https://user-images.githubusercontent.com/50769329/185496131-60af72cb-a329-4702-bb7a-b587bcd25c0d.png)

---
#### 15. OPEN Spacing next to time stamp is too large and missing bold dot spacer
Actual
![image](https://user-images.githubusercontent.com/50769329/185496888-afff7adc-c159-49d2-bb29-2d84d9de8ecb.png)

Expected
![image](https://user-images.githubusercontent.com/50769329/185496733-e07e100b-4646-4490-ac58-32a34c2c725b.png)

---
Build: [📦dmg](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220818-184355-e92c92-pr6508.dmg)

2022-08-19 11:02 UTC, micieslak requested changes
I just found that pinned message boxes are not positioned correctly at startup:

https://user-images.githubusercontent.com/20650004/185604859-b72b9630-9085-42a7-9fef-b3f50e3ca45b.mp4

2022-08-19 15:07 UTC, micieslak approved these changes
It's huge! Lgtm, but I left some comments.

2022-08-19 17:36 UTC, glitchminer approved these changes
Tested and approved.

2022-08-20 00:02 UTC, merged