use nim provided language model
status-im/status-desktop pull request #6590
Opened 2022-07-22 16:30 UTC by osmaczko

Use nim provided language model in qml.
closes: https://github.com/status-im/status-desktop/issues/6416

### Affected areas

changing language

2022-07-22 16:54 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | c86c7c3f | [#1](https://ci.status.im/job/status-desktop/job/branches/job/windows/job/PR-6590/1/) | 2022-07-22 16:54:11 | ~22 min | `windows` | [:package:`exe`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220722-163120-c86c7c-pr6590.exe) |

2022-07-25 13:43 UTC, stefandunca approved these changes

2022-07-25 13:50 UTC, caybro requested changes
Just a minor naming problem, otherwise looks good

2022-07-26 07:11 UTC, noeliaSD requested changes
Testing it, and based on current master behaviour, I have 2 questions:

1. How the searcher works? I was expecting it takes into account the complete item name but it just only takes into account if it exactly matches the item name from the starting point. On the current master you can write "brazil" or "taiwan" and it searches the correct item. Here a video of this branch behaviour:

https://user-images.githubusercontent.com/97019400/180944997-de71cd1d-bac9-491c-9614-76f95904f8de.mov

2. Why can I only see some of this `locale_table` options? Is it the expected behaviour? On master we have more visible languages to select. Here a video of the ones I can see.

https://user-images.githubusercontent.com/97019400/180945021-fb22e600-a05c-4c83-a984-77bd9382ea4d.mov

2022-07-26 13:36 UTC, osmaczko commented
@noeliaSD 

AD1) How the search wors is defined in `StatusListPicker`. When I was refactoring `StatusListPicker` I changed `searchText.includes` to `searchText.startsWith` by mistake. Now it should behave as before.

AD2) `locale_table` is just a table with a description of all possible locales. Which languages the app really uses is defined by *.ts (*.qm to be more precise) files and these [come from the Lokalise platform](https://github.com/status-im/status-desktop/pull/6568).

2022-07-26 18:53 UTC, osmaczko commented on ui/app/AppLayouts/Profile/stores/LanguageStore.qml
> +    readonly property string currentLocale: languageModule ? languageModule.currentLocale : null
Yup, that's right. Changed "locale" to "translation": https://github.com/status-im/status-desktop/pull/6590/commits/e0e5e909f54d42a8e06b388882d10ec027265643. 

Still, the "locale" term is misused in some places in qml code, but I would like to keep it out of scope for this PR.

2022-07-26 21:43 UTC, caybro commented on ui/app/AppLayouts/Profile/stores/LanguageStore.qml
> +    readonly property string currentLocale: languageModule ? languageModule.currentLocale : null
Definitely, here's a good start :)

2022-07-26 22:08 UTC, caybro approved these changes

2022-07-27 07:12 UTC, osmaczko commented on ui/app/AppLayouts/Wallet/views/LeftTabView.qml
> +                    Utils.toLocaleString(parseFloat(RootStore.totalCurrencyBalance).toFixed(2), localAppSettings.language, {"currency": true}) + " " + RootStore.currentCurrency.toUpperCase()
> Something to fix globally I guess

Yes, definitely. Do we have a task for that already created?

> Rationale: https://hackmd.io/@status-desktop/B1eOaf-nd/%2FjNzZnH8ZRiynrrXJ--XpmQ#Currency-values

Great summary :+1:

2022-07-27 09:37 UTC, caybro commented on ui/app/AppLayouts/Wallet/views/LeftTabView.qml
> +                    Utils.toLocaleString(parseFloat(RootStore.totalCurrencyBalance).toFixed(2), localAppSettings.language, {"currency": true}) + " " + RootStore.currentCurrency.toUpperCase()
Nope, I'll create one

2022-07-27 11:08 UTC, noeliaSD commented
> @noeliaSD
> 
> AD1) How the search wors is defined in `StatusListPicker`. When I was refactoring `StatusListPicker` I changed `searchText.includes` to `searchText.startsWith` by mistake. Now it should behave as before.
> 
> AD2) `locale_table` is just a table with a description of all possible locales. Which languages the app really uses is defined by _.ts (_.qm to be more precise) files and these [come from the Lokalise platform](https://github.com/status-im/status-desktop/pull/6568).

Thanks for the clarification!

2022-07-27 11:08 UTC, noeliaSD approved these changes
Tested! LGTM!

2022-07-27 12:22 UTC, merged