fix(communities): Cannot leave community, invite, mute from Settings/Communities
status-im/status-desktop pull request #6631
Opened 2022-07-25 15:52 UTC by micieslak

### What does the PR do

fixes #6305

- clicking on community entry moves to the corresponding community
  **Note: it required adding `setActiveCommunity` to `AppLayouts/store/RootStore`, so now `setActiveCommunity` is duplicated, it occurs in 3 different places (RootStore, another RootStore and CommunityStore), because there is no common `RootStore` accessible from the whole app. Are there some plans to refactor those stores?**
- muting community works as expected
- invite icon opens invite dialog, Invite button sends invitations

### Affected areas

`CommunitiesListPanel`, `CommunitiesView`, `AppLayouts/store/RootStore`

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/20650004/180821070-f780a82a-daed-4369-a99b-b8bf2e2e3db3.mp4

- [x] I've checked the design and this PR matches it

2022-07-25 16:01 UTC, caybro requested changes

2022-07-25 16:01 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
> +    signal setActiveCommunityClicked(var communityId)
if `communityId` is a string, then pass it as `string`, not `var`

2022-07-25 16:01 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
> +                onClicked: setCommunityMutedClicked(model.id, !model.muted)
Keep the `root` context

2022-07-25 16:01 UTC, caybro commented on ui/app/AppLayouts/Profile/panels/CommunitiesListPanel.qml
> +                onClicked: inviteFriends(model)
Keep the `root` context

2022-07-26 00:55 UTC, elina2015 approved these changes
Tested and approved. Thanks for the fixes!

2022-07-26 08:08 UTC, caybro approved these changes
LGTM!

2022-07-29 09:11 UTC, merged