fix: Reimplemented selectors using `StatusComboBox`
status-im/status-desktop pull request #6736
Opened 2022-07-31 07:23 UTC by igor-sirotin

Requires https://github.com/status-im/StatusQ/pull/815
Required by https://github.com/status-im/status-desktop/pull/6508

### What does the PR do

Updated selector components using `StatusComboBox`:
- [x] `AddressSourceSelector` - removed, it was totally equal to default `StatusComboBox`
- [x] `ContactsSelector`

### Affected areas

wallet

### Screenshot of functionality (including design for comparison)

I've changed the behavior for an **empty** `ContactsSelector`.
Previously it was enabled and clicking on it would open a dropdown menu with "No contacts" text.
Now it's disabled with "No contacts" text as `contentItem`.

I couldn't find designs for this.
This solution seems better to me, as the user don't have to make another click to see that there're no options to select from.

- [x] I've checked the design and this PR matches it

2022-07-31 07:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b86a7d2f | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux/job/PR-6736/1/) | 2022-07-31 07:33:50 | ~10 min | `linux` | [:package:`tgz`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220731-072344-b86a7d-pr6736.tar.gz) |

2022-08-01 18:46 UTC, caybro requested changes
Some minor nits, otherwise looks cool!

2022-08-01 18:46 UTC, caybro commented on ui/imports/shared/controls/ContactSelector.qml
> +            property var currentContact: Utils.getContactDetailsAsJson(pubKey)
readonly?

2022-08-01 18:46 UTC, caybro commented on ui/imports/shared/controls/ContactSelector.qml
> +                        StatusBaseText {
These should really be one text, see:
https://hackmd.io/@status-desktop/B1eOaf-nd/%2FjNzZnH8ZRiynrrXJ--XpmQ#Dynamic

2022-08-01 18:46 UTC, caybro commented on ui/imports/shared/controls/RecipientSelector.qml
> +            model: root.sources.filter(source => source.visible)
This screams for SortFilterProxyModel :)

2022-08-03 07:52 UTC, Khushboo-dev-cpp commented on ui/imports/shared/controls/ContactSelector.qml
> +//    property alias validationErrorAlignment: comboBox.validationErrorAlignment
why is this commented?

2022-08-03 12:05 UTC, caybro commented on ui/imports/shared/controls/RecipientSelector.qml
> +            model: root.sources.filter(source => source.visible)
Sure

2022-08-03 12:06 UTC, caybro commented on ui/imports/shared/controls/ContactSelector.qml
> +                        StatusBaseText {
Yeah, there's shouldn't be an explicit width limit :) and if yes, `elide` is the way to go

2022-08-03 12:23 UTC, caybro approved these changes

2022-08-03 12:23 UTC, caybro commented on ui/i18n/qml_en.ts
> -<context>
You don't have to touch TS files at all

2022-08-03 12:24 UTC, faust4exe approved these changes

2022-08-03 12:33 UTC, MishkaRogachev approved these changes
LGTM!

2022-08-03 12:37 UTC, caybro commented
@igor-sirotin Noticed one minor issue: 

![Snímek obrazovky z 2022-08-03 14-34-46](https://user-images.githubusercontent.com/5377645/182609461-4abcac02-2342-4f43-858a-0ba789a995f4.png)

2022-08-03 12:41 UTC, caybro commented
And fixed :)

![Snímek obrazovky z 2022-08-03 14-39-14](https://user-images.githubusercontent.com/5377645/182610148-2c93ca9a-f674-4de1-be90-e6638d353903.png)

2022-08-03 12:42 UTC, Khushboo-dev-cpp commented
this brings back https://github.com/status-im/status-desktop/issues/6499

2022-08-03 15:29 UTC, merged