Feat/bio social links
status-im/status-desktop pull request #6947
Opened 2022-08-10 09:04 UTC by osmaczko

### What does the PR do

closes: https://github.com/status-im/status-desktop/issues/5984

- [bump status-go](https://github.com/status-im/status-desktop/commit/bf8d39b36c6ff0aed4e32c420659c888b86987f0)
- [bump statusq](https://github.com/status-im/status-desktop/commit/115774d5e8d0a93a4f7e8065a23d19dfc1a6b9c7)
- [feat: integrate social links and bio endpoints](https://github.com/status-im/status-desktop/commit/af434f8d00d503ccc178be73411f7fa0e383fd47)
- [feat: introduce social links model](https://github.com/status-im/status-desktop/commit/79dc93ff9e9726176c3436f52360cf4176139429)
- [feat: add bio and social links functionality to profile module](https://github.com/status-im/status-desktop/commit/ca8a36bb5507ae1753c87dde6146e06e96b375d1)
- [feat: extend getContactDetailsAsJson with bio and social links](https://github.com/status-im/status-desktop/commit/f7e7171464efafded8dc1d51c5d3bf38df4e41a1)
- [feat: add social links' ui primitives](https://github.com/status-im/status-desktop/commit/ce6aff1ffeb6a30b4d08726faef33e7891b79322)
- [feat: add SocialLinksModal](https://github.com/status-im/status-desktop/commit/11229b4c3b6f026cb89b02417a53762f37c5ffbc)
- [feat: add bio and social links to settings](https://github.com/status-im/status-desktop/commit/306d6cb664dea558dab03b615039898bb32a82a6)
- [feat: add bio and social links to profile view](https://github.com/status-im/status-desktop/commit/333e1142f575d2750246c12f91102da6c634ae48)

### Affected areas

- profile settings
- profile view

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

In some places, the design is not matched due to inconsistencies in the design itself, will describe it soon here..

### Videos

https://user-images.githubusercontent.com/33099791/183860776-814ac044-896f-4a4a-80f9-70edcdf21fb2.mp4

https://user-images.githubusercontent.com/33099791/183861133-b4f90f27-8882-45f2-9bc9-0818798d895e.mp4

2022-08-10 09:16 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 333e1142 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-6947/1/) | 2022-08-10 09:16:22 | ~11 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220810-090430-333e11-pr6947.dmg) |

2022-08-10 09:24 UTC, caybro approved these changes
Looks cool

One suggestion though

2022-08-10 09:24 UTC, caybro commented on src/app/modules/shared_models/social_links_model.nim
> +  proc updateItem*(self: SocialLinksModel, uuid, text, url: string): bool =
What about doing it the right way (tm) by overriding the setData() method? :)

See https://doc.qt.io/qt-5/qabstractitemmodel.html#setData

2022-08-16 09:55 UTC, glitchminer commented
### Issues found 

---
#### 1. OPEN User is required to include whole URL to provide link to social

If a user enters a twitter handle `ethstatus` then should the link on the profile be only to `ethstatus` or to `https://twitter.com/ethstatus`? Please confirm expected behaviour. 

This also applies to the other fields for specific social accounts.

Actual
![image](https://user-images.githubusercontent.com/50769329/184832504-bd787c58-0768-43e0-b51b-e52c71181519.png)
![image](https://user-images.githubusercontent.com/50769329/184832592-0f9af37f-a3ff-4d73-b35f-f7d1aec1db12.png)

---
#### 2. OPEN Max length too long

Custom URLs have a max description of 24 characters but the defined social fields can be long. Decision may be needed on how many chars to show on profile and when clicked, especially for Personal Site (which could be removed in favour of only custom links?)

Actual
![image](https://user-images.githubusercontent.com/50769329/184841461-40a97ed0-5a7f-4544-9d77-9bc2e41a9fc2.png)

**Max length of handle** (excluding base URL):
Twitter: 15
Discord: 37 (32+#+4)
Youtube: 20
Github: 39
Telegram: 32

---
#### 3. OPEN Left margin of icon is not per Figma
   Actual
   ![image](https://user-images.githubusercontent.com/50769329/184841902-078436cb-cf94-4894-83fc-412c51524be5.png)

   Expected
   ![image](https://user-images.githubusercontent.com/50769329/184842162-98aafc69-844f-4367-abd7-34e2e127ba6b.png)

---
#### 4. OPEN Custom URLs have a different height than those with icon

Consider increasing height or using same icon as `Personal Site` 

![image](https://user-images.githubusercontent.com/50769329/184843488-4fc45250-e2c3-40f3-bf28-4a86c59a503e.png)

---
#### 5. OPEN Not possible to tab between fields

Pressing tab is adding a tab to the input on the field in focus

---
#### 6. OPEN Maximum number of links

Many custom links can be added. Please confirm the expected behaviour of the maximum number of custom links.


---
#### 7. OPEN Order of custom links
The custom links appear in alphabetical order, not the order they are entered in the list.
![image](https://user-images.githubusercontent.com/50769329/184844693-4ab0930f-c99c-48ea-9591-13004f0e5bc9.png)

---
#### 7. OPEN Cannot easily clear the 1st custom link

After the first link, it is possible to click on `Remove`. There is not a remove or clear button to easily reset the first custom link.

![image](https://user-images.githubusercontent.com/50769329/184844912-0035d1d9-1090-4538-9493-5674dcdee932.png)

---
#### 8. OBSERVATION ONLY Why use myspace as an example on empty custom links instead of something like `My Status Profile`

---
#### 9. OPEN At min height with many links the remove contact button becomes hidden
![image](https://user-images.githubusercontent.com/50769329/184849468-d0aab2b4-9eef-42ca-83fd-27ed3b6474d9.png)

---
Test info
Build: https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220815-084254-73effb-pr6947.dmg
OS: Mac

2022-08-16 10:00 UTC, glitchminer requested changes
Please see comment with issues found: https://github.com/status-im/status-desktop/pull/6947#issuecomment-1216418888

2022-08-17 11:01 UTC, glitchminer approved these changes
Thanks for the fixes @osmaczko! 
Tested and approved with caveat that the items from https://github.com/status-im/status-desktop/pull/6947#issuecomment-1216418888 are discussed in a follow up:

---
#### Item 1: User is required to include whole URL to provide link to social

If a user enters a twitter handle `ethstatus` then should the link on the profile be only to `ethstatus` or to `https://twitter.com/ethstatus`? Please confirm expected behaviour. 
This also applies to the other fields for specific social accounts.

Actual
![image](https://user-images.githubusercontent.com/50769329/184832504-bd787c58-0768-43e0-b51b-e52c71181519.png)
![image](https://user-images.githubusercontent.com/50769329/184832592-0f9af37f-a3ff-4d73-b35f-f7d1aec1db12.png)

---
#### Item 2: Max length too long
While the issue has been resolved it was noted that eliding handles and URLs at max length may leave them obscured until copied
For example, max length of github account is 39, which is longer than both the 16 and 36 char limits.

![image](https://user-images.githubusercontent.com/50769329/185102620-9b461f0c-1d20-4334-8412-80d6a5f8ac94.png)

---
#### Item 6: Maximum number of links
Many custom links can be added, upper bound to be determined

![image](https://user-images.githubusercontent.com/50769329/184844693-4ab0930f-c99c-48ea-9591-13004f0e5bc9.png)

2022-08-17 11:18 UTC, merged