fix(toast-notifications): Fix notifcations listview sizes
status-im/status-desktop pull request #7111
Opened 2022-08-22 13:00 UTC by borismelnik

Closes: #6767

### What does the PR do

In general, `toastArea` (which is `StatusListView`) missed `width` and also I it use `anchors` to parent - it block mouse clicks under toast notifications area.

### Affected areas

AppMain

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

2022-08-22 13:07 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 64fd9601 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/uitests/job/PR-7111/1/) | 2022-08-22 13:07:32 | ~6 min | `e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/uitests/job/PR-7111/1/consoleText) |

2022-08-24 12:42 UTC, anastasiyaig approved these changes

2022-08-24 12:51 UTC, Khushboo-dev-cpp commented on ui/app/mainui/AppMain.qml
> +            Component.onCompleted: {
I think this was missed to remove?

2022-08-24 12:53 UTC, Khushboo-dev-cpp requested changes
Looks good! only one part that was missed to remove :)

2022-08-26 09:01 UTC, borismelnik commented on ui/app/mainui/AppMain.qml
> +            Component.onCompleted: {
yes :)

2022-08-26 09:22 UTC, Khushboo-dev-cpp approved these changes
LGTM :)

2022-08-26 09:30 UTC, merged