fix(Wallet/AddAccountModal): fix status-go error messages
status-im/status-desktop pull request #7173
Opened 2022-08-29 18:17 UTC by stefandunca

## Fixes: #6984

Remove the unneeded native error dialog showing internal status-go
error strings. Instead redirect the error message for wrong private key
as a specific error message.

Notes:

- I find the back and forth of data and states between `AddAccountModal` , `AdvancedAddAccountView` and `ImportPrivateKey` cumbersome. However, I consider the big refactoring not worth the effort given the upcoming redesign and the importance of the Private Key Import feature.
- `StatusAsyncValidator` has a complex pulling mechanism and something else would have been better alternative, though not worth the investigation due to low feature importance.

### Affected areas

Wallet - Add a private key account

![image](https://user-images.githubusercontent.com/47554641/187270539-95d96273-793a-4cfc-b4ed-ebae1f703b80.png)

- [ ] ~~I've checked the design and this PR matches it~~

2022-08-29 18:22 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | c6d5f78e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7173/1/) | 2022-08-29 18:22:49 | ~4 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7173/1/consoleText) |

2022-08-30 11:33 UTC, caybro requested changes
Looks good, just 2 minor nits

2022-08-30 11:33 UTC, caybro commented on ui/app/AppLayouts/Wallet/panels/ImportPrivateKeyPanel.qml
> +                errorMessage: "Enter a valid private key"
needs `qsTr()`

2022-08-30 11:33 UTC, caybro commented on ui/app/AppLayouts/Wallet/panels/ImportPrivateKeyPanel.qml
> +        property bool invalidPrivateKeyError: Utils.isInvalidPrivateKey(RootStore.derivedAddressesError)
`readonly` (the one above too I guess)

2022-08-30 13:59 UTC, jrainville approved these changes
Looks good to me

2022-08-30 14:31 UTC, richard-ramos approved these changes

2022-08-30 14:55 UTC, caybro approved these changes
Nice

2022-08-30 17:05 UTC, merged