fix(@desktop/wallet): Wallet - Send - Crash after opening send modal
status-im/status-desktop pull request #7185
Opened 2022-08-30 10:14 UTC by Khushboo-dev-cpp

The error seen in the bug is linked to getSuggestedFees returning an rpc error that was unhandled, I think this should resolve this issue.

fixes #6801

### What does the PR do

The error seen in the bug is linked to getSuggestedFees returning an rpc error that was unhandled, I think this should resolve this issue.

### Affected areas

Wallet

2022-08-30 10:24 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 023b0e4b | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-7185/1/) | 2022-08-30 10:24:51 | ~9 min | `macos` | [:package:`dmg`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-220830-101458-023b0e-pr7185.dmg) |

2022-08-31 15:05 UTC, Khushboo-dev-cpp commented
> What is the error?

```
qrc:/StatusQ/src/StatusQ/Components/StatusCard.qml:489:13: QML PropertyChanges: Cannot assign to non-existent property "edit.color"
DBG 2022-08-03 20:17:53.796+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=3039194 file=core.nim:20 rpc_method=wallet_getSuggestedFees
ERR 2022-08-03 20:17:54.065+01:00 rpc response error                         topics="rpc" tid=3039194 file=core.nim:29 err="\nstatus-go error [methodName:wallet_getSuggestedFees, code:-32000, message:transaction type not supported ]\n"
INF 2022-08-03 20:17:54.066+01:00 shutting down...                           topics="status-app" tid=3039194 file=nim_status_client.nim:134
qrc:/imports/shared/popups/SendModal.qml:393:33: QML GasValidator: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/imports/shared/popups/SendModal.qml:393:33: QML GasValidator: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/imports/shared/popups/SendModal.qml:393:33: QML GasValidator: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/imports/shared/popups/SendModal.qml:393:33: QML GasValidator: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Traceback (most recent call last)
/Users/jenkins/workspace/status-desktop/platforms/macos/src/nim_status_client.nim(168) nim_status_client
/Users/jenkins/workspace/status-desktop/platforms/macos/src/nim_status_client.nim(143) mainProc
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/boot/app_controller.nim(233) delete
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/global/global_singleton.nim(67) delete
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimqml/src/nimqml/private/qqmlapplicationengine.nim(40) delete
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

this is what was reported here https://github.com/status-im/status-desktop/issues/6801
```

2022-09-01 16:14 UTC, borismelnik commented on src/app_service/service/transaction/service.nim
> +      error "Error getting suggested fees", msg = e.msg
copy-paste typo :) `Error getting suggested routes :)

2022-09-01 16:15 UTC, borismelnik requested changes
LGTM, just a small typo :)

2022-09-05 09:22 UTC, Khushboo-dev-cpp commented on src/app_service/service/transaction/service.nim
> +      error "Error getting suggested fees", msg = e.msg
done @borismelnik !

2022-09-05 09:33 UTC, borismelnik approved these changes
LGTM

2022-09-05 09:34 UTC, merged