fix(@desktop/chat): adjust emoji popup behaviour
status-im/status-desktop pull request #7210
Opened 2022-09-01 14:30 UTC by faust4exe

Fixes #7094

### What does the PR do

Add logic to capture emoji popup by changing parent and close policy on emoji popup open from Chat input, also release by reverting those properties when emoji popup is closed.

### Affected areas

Desktop Chat

### Screenshot of functionality

https://user-images.githubusercontent.com/6445843/187939475-0e81ad72-8fb3-403d-8fab-75b51df9db69.mp4

2022-09-01 14:36 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | 8bd497fe | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7210/1/) | 2022-09-01 14:36:50 | ~6 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7210/1/consoleText) |

2022-09-02 10:33 UTC, glitchminer approved these changes
Tested and approved

2022-09-02 11:50 UTC, caybro reviewed
@faust4exe @glitchminer please rebase and test again; I did some changes there meanwhile as well, sorry :)

2022-09-02 12:19 UTC, faust4exe commented
> @faust4exe @glitchminer please rebase and test again; I did some changes there meanwhile as well, sorry :)

Rebased and tested - but there is nothing actually to test because your changes were removed on merge, but they had similar idea as my PR

2022-09-02 12:37 UTC, caybro approved these changes

2022-09-02 13:20 UTC, micieslak requested changes
I found a bug and a solution :)

https://user-images.githubusercontent.com/20650004/188153795-d723bbed-def8-42da-88d9-6eb7a343839a.mp4

It could be fixed by adding `Qt.binding` instead of assigning x, y directly. But...
what about fixing it by replacing current changes with artificial state in `d`?

```
        readonly property StateGroup emojiPopupTakeover: StateGroup {
            states: State {
                when: control.emojiPopupOpened

                PropertyChanges {
                    target: emojiPopup

                    parent: control
                    x: control.width - emojiPopup.width - Style.current.halfPadding
                    y: -emojiPopup.height
                    closePolicy: Popup.CloseOnEscape | Popup.CloseOnPressOutsideParent
                }
            }
        }
```
In my opinion it has several advantages:
- more declarative
- the whole logic in a single place
- restoring previous values is done automatically
- works nicely with existing flag `control.emojiPopupOpened`

@faust4exe @caybro what do you think?

2022-09-02 13:29 UTC, faust4exe commented
> I found a bug and a solution :)
> Screencast.2022-09-02.15.10.00.mp4
> 
> It could be fixed by adding `Qt.binding` instead of assigning x, y directly. But... what about fixing it by replacing current changes with artificial state in `d`?
> 
> ```
>         readonly property StateGroup emojiPopupTakeover: StateGroup {
>             states: State {
>                 when: control.emojiPopupOpened
> 
>                 PropertyChanges {
>                     target: emojiPopup
> 
>                     parent: control
>                     x: control.width - emojiPopup.width - Style.current.halfPadding
>                     y: -emojiPopup.height
>                     closePolicy: Popup.CloseOnEscape | Popup.CloseOnPressOutsideParent
>                 }
>             }
>         }
> ```
> 
> In my opinion it has several advantages:
> 
>     * more declarative
> 
>     * the whole logic in a single place
> 
>     * restoring previous values is done automatically
> 
>     * works nicely with existing flag `control.emojiPopupOpened`
> 
> 
> @faust4exe @caybro what do you think?

@micieslak Looks good to me :)

2022-09-02 14:17 UTC, caybro commented
> > I found a bug and a solution :)
> > Screencast.2022-09-02.15.10.00.mp4
> > It could be fixed by adding `Qt.binding` instead of assigning x, y directly. But... what about fixing it by replacing current changes with artificial state in `d`?
> > ```
> >         readonly property StateGroup emojiPopupTakeover: StateGroup {
> >             states: State {
> >                 when: control.emojiPopupOpened
> > 
> >                 PropertyChanges {
> >                     target: emojiPopup
> > 
> >                     parent: control
> >                     x: control.width - emojiPopup.width - Style.current.halfPadding
> >                     y: -emojiPopup.height
> >                     closePolicy: Popup.CloseOnEscape | Popup.CloseOnPressOutsideParent
> >                 }
> >             }
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my opinion it has several advantages:
> > ```
> > * more declarative
> > 
> > * the whole logic in a single place
> > 
> > * restoring previous values is done automatically
> > 
> > * works nicely with existing flag `control.emojiPopupOpened`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @faust4exe @caybro what do you think?
> 
> @micieslak Looks good to me :) And works as expected

I like it too, always better w/o imperative JS code

2022-09-02 14:21 UTC, micieslak approved these changes
LGTM!

2022-09-02 14:22 UTC, merged