fix(AddAccountModal): Updated password error message
status-im/status-desktop pull request #7224
Opened 2022-09-05 08:52 UTC by alexandraB99

Closes #5719

### What does the PR do

### Affected areas

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2022-09-05 08:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | 4baef7ed | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7224/1/) | 2022-09-05 08:57:41 | ~4 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7224/1/consoleText) |

2022-09-05 09:29 UTC, caybro requested changes

2022-09-05 09:29 UTC, caybro commented on ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
> +                d.passwordValidationError = qsTr("Password must be at least %1 characters long").arg(root.minPswLen);
Plural missing, see https://hackmd.io/@status-desktop/B1eOaf-nd/%2FjNzZnH8ZRiynrrXJ--XpmQ#Plurals

2022-09-05 14:57 UTC, alexandraB99 commented on ui/app/AppLayouts/Wallet/popups/AddAccountModal.qml
> +                d.passwordValidationError = qsTr("Password must be at least %1 characters long").arg(root.minPswLen);
done!

2022-09-05 15:44 UTC, caybro approved these changes
Nice :)

2022-09-06 13:42 UTC, alaibe approved these changes

2022-09-06 15:48 UTC, merged