feat(Communities): Add ephemerial notification when request to join was accepted
status-im/status-desktop pull request #7264
Opened 2022-09-07 14:50 UTC by borismelnik

Part of: #7072

### What does the PR do

 Add ephemerial notification when request to join was accepted

### Affected areas

Communities

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

<img width="472" alt="Снимок экрана 2022-09-07 в 17 46 45" src="https://user-images.githubusercontent.com/82511785/188909054-d0a49b13-8ca0-4695-88ed-233ffbaeea95.png">

2022-09-07 14:56 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | 10b5d1b5 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7264/1/) | 2022-09-07 14:56:24 | ~5 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7264/1/consoleText) |

2022-09-07 15:30 UTC, caybro requested changes

2022-09-13 07:53 UTC, endulab approved these changes

2022-09-13 08:06 UTC, caybro approved these changes
Please create the issue for the notifications to be translatable :)

2022-10-21 11:35 UTC, borismelnik commented
> Please create the issue for the notifications to be translatable :)

@caybro https://github.com/status-im/status-desktop/issues/8002

2022-10-28 08:01 UTC, merged