feat(CreateChatView): Support pasting chat key
status-im/status-desktop pull request #7420
Opened 2022-09-17 14:21 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7176

### What does the PR do

Open a "Send contact request" popup when user pastes a valid chat key to "create chat" text field.
Supported values are:
- Public key
- Public key wrapped in a URL
- Compressed key
- Compressed key wrapped in a URL

⚠️  I also made an important (but not a breaking) change - I switched `Global` root item from `QtObject` to `Item`, so that Components could be create right there. This is needed so that we could get the reference to created popup whenever we use `Global.openContactRequestPopup`. In this particular case we bind to it's `closed` signal.

⚠️ Also I made changes to Nim contacts service:
`getContactById` now supports compressed keys.

### Affected areas

CreateChat, ProfilePopup

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/25482501/190861714-7213eeb0-42bc-41bd-8d9c-3b7be2e9726b.mov

2022-09-17 14:26 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | da5a025c | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7420/1/) | 2022-09-17 14:26:08 | ~4 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7420/1/consoleText) |

2022-09-18 12:19 UTC, caybro requested changes
Generally looks good, just some minor issues

2022-09-18 12:19 UTC, caybro commented on ui/app/AppLayouts/Chat/panels/InlineSelectorPanel.qml
> +                                    if ((event.modifiers | Qt.ControlModifier) && event.key === Qt.Key_V) {
Better (also) check for `event.matches(StandardKey.Paste)`

2022-09-18 12:19 UTC, caybro commented on ui/app/AppLayouts/Chat/views/CreateChatView.qml
> +//                enabled: root.rootStore.contactsModel.count > 0
Why commented out?

2022-09-18 12:19 UTC, caybro commented on ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
> +        property var lookupContact: Backpressure.debounce(root, 0, function (value) {
Why not a simple `function()`?

2022-09-18 12:19 UTC, caybro commented on ui/imports/shared/popups/qmldir
> +SendContactRequestModal 1.0 SendContactRequestModal.qml
Again, this file seems to be (physically) duplicated in 2 different subdirectories; please remove one

2022-09-19 09:18 UTC, osmaczko requested changes
Functionally looks good, some comments left.

2022-09-19 09:18 UTC, osmaczko commented on ui/imports/utils/Global.qml
> +        const store = appMain.rootStore.profileSectionStore.contactsStore
unused

2022-09-19 09:18 UTC, osmaczko commented on ui/imports/utils/Global.qml
> +            header.title: qsTr("Send Contact Request to %1").arg(userDisplayName)
Shouldn't it be a part of `SendContactRequestModal` :thinking: ?

2022-09-19 09:18 UTC, osmaczko commented on ui/imports/utils/Global.qml
> +        })
This is inconsistent with how popups are already opened through `Global.qml`. 

```suggestion
        openSendContactRequestRequested(publicKey, contactDetails.displayName, contactDetails.largeImage)
```

2022-09-19 10:01 UTC, caybro commented on ui/app/AppLayouts/Chat/views/MembersSelectorView.qml
> +        property var lookupContact: Backpressure.debounce(root, 0, function (value) {
I guess they would effectively do the same; just like a `QTimer::singleShot()` or `QMetaObject::invokeMethod()`; ie. it forces processing of events

2022-09-21 19:55 UTC, glitchminer commented
## Issues

#### 1. OPEN [Observation] What should happen when after the contact request has been sent
Currently the chat key is just left in the input field. The user must manually clear it to chat with someone else.

Discussed option of closing the Start Chat screen all together - @igor-sirotin to discuss with @John-44  

#### 2. OPEN [Observation] It's not possible to type the key to add the contact

#### 3. MOVED Confirm button is enabled when field is empty and when text is entered but not a contact

#### 4. MOVED Not possible to right click on field to paste

#### 5. MOVED After entering key, the contact list is filtered but there is no indication that there are just no results to select

2022-09-21 19:56 UTC, glitchminer approved these changes
Tested, approved.

2022-09-26 15:27 UTC, caybro approved these changes

2022-09-28 13:55 UTC, merged