fix(ChatMessagesView): Loading spinner and scroll to bottom button overlap
status-im/status-desktop pull request #7719
Opened 2022-10-03 12:20 UTC by caybro

Use the more modern StatusIcon, w/o the uncoditional ColorOverlay

Closes: #7645

### What does the PR do

Fixes visual glitch in the bottom right corner

### Affected areas

ChatMessagesView

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

Before:
![Snímek obrazovky z 2022-10-03 13-35-36](https://user-images.githubusercontent.com/5377645/193574842-7be5bd7a-458c-4d64-90e1-781de0686194.png)

After:
![Snímek obrazovky z 2022-10-03 14-19-59](https://user-images.githubusercontent.com/5377645/193575085-434909c2-c875-4084-8ec9-5a3225a0d067.png)

2022-10-03 12:26 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b259a233 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7719/1/) | 2022-10-03 12:26:08 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7719/1//consoleText) |

2022-10-03 13:19 UTC, alexandraB99 approved these changes

2022-10-03 14:00 UTC, micieslak reviewed
How does it fix the problem of overlapping loading animation and "go to bottom" butotn? It's not clear from the attached image.

2022-10-03 14:06 UTC, micieslak requested changes
The problem reported in the issue seems to be still there:

![Screenshot from 2022-10-03 16-03-21](https://user-images.githubusercontent.com/20650004/193597745-14494624-2168-4d7c-bf2a-45c2277b46fd.png)
![Screenshot from 2022-10-03 16-03-02](https://user-images.githubusercontent.com/20650004/193597781-674ccc23-a9e4-400d-9f46-395ba39a5b38.png)

2022-10-03 15:00 UTC, caybro commented
> The problem reported in the issue seems to be still there:
> 
> ![Screenshot from 2022-10-03 16-03-21](https://user-images.githubusercontent.com/20650004/193597745-14494624-2168-4d7c-bf2a-45c2277b46fd.png) ![Screenshot from 2022-10-03 16-03-02](https://user-images.githubusercontent.com/20650004/193597781-674ccc23-a9e4-400d-9f46-395ba39a5b38.png)

Pls check again, should be fixed

2022-10-04 07:36 UTC, stefandunca approved these changes

2022-10-04 08:05 UTC, micieslak requested changes
@caybro now loading spinner appears in the top part, with no right margin. It looks incorrect imo. 
![Screenshot from 2022-10-04 10-03-19](https://user-images.githubusercontent.com/20650004/193767208-a833e5a3-8c66-4a4c-a15f-bd0f0eed0fd9.png)

2022-10-04 08:06 UTC, caybro commented
> @caybro now loading spinner appears in the top part, with no right margin. It looks incorrect imo. ![Screenshot from 2022-10-04 10-03-19](https://user-images.githubusercontent.com/20650004/193767208-a833e5a3-8c66-4a4c-a15f-bd0f0eed0fd9.png)

What the.... :)

2022-10-04 08:19 UTC, caybro commented
@micieslak I can't reproduce, for me it shows in the bottom right corner, just above the chat input

2022-10-04 19:02 UTC, micieslak commented
> @micieslak I can't reproduce, for me it shows in the bottom right corner, just above the chat input

Strange. For me it's still on top:

![Screenshot from 2022-10-04 20-59-07](https://user-images.githubusercontent.com/20650004/193903871-660dd361-0e92-4ac5-9b21-ac74d14ff06f.png)

2022-10-04 21:28 UTC, caybro commented
> > @micieslak I can't reproduce, for me it shows in the bottom right corner, just above the chat input
> 
> Strange. For me it's still on top:
> 
> ![Screenshot from 2022-10-04 20-59-07](https://user-images.githubusercontent.com/20650004/193903871-660dd361-0e92-4ac5-9b21-ac74d14ff06f.png)

Now it's gone for good :)

2022-10-04 21:55 UTC, micieslak approved these changes
lgtm!

2022-10-05 00:38 UTC, elina2015 approved these changes
Tested and approved

2022-10-05 00:59 UTC, merged