fix(ChatHeaderContentView): Unreachable buttons in community header at min width
status-im/status-desktop pull request #7783
Opened 2022-10-06 10:23 UTC by micieslak

### What does the PR do

Instead of being unreachable under bell icon, icons are placed over chat name with some semi transparent background for readability.

Closes: #7647

### Affected areas

`ChatHeaderContentView`

### Screenshot of functionality (including design for comparison)

- [x] test changes in both light and dark theme?
- [x] I've checked the design and this PR matches it

[Kazam_screencast_00037.webm](https://user-images.githubusercontent.com/20650004/194289416-be90ae60-27e5-4db4-ba75-b6abdbd78190.webm)

2022-10-06 10:31 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a44b78bf | [#2](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7783/2/) | 2022-10-06 10:31:32 | ~6 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7783/2//consoleText) |

2022-10-06 11:31 UTC, caybro approved these changes
Code looks good but I wonder if we shouldn't elide the channel title/subtitle instead... that's more of a design decision

2022-10-06 12:35 UTC, alexandraB99 approved these changes

2022-10-10 07:21 UTC, noeliaSD requested changes
I'm neither sure about this solution. I think it should be better to ask the design team before merging and closing it. 

WDYT @John-44, @benjthayer ?

2022-10-10 10:51 UTC, benjthayer commented
Thanks @micieslak @noeliaSD it works well but I wonder if we should consider instead setting a min width for the main/central message pane panel so there is no overlap? As users of the app do we see the need for the app width to be reduced to that degree? @John-44

2022-10-11 11:32 UTC, micieslak commented
Thank you @noeliaSD nad @benjthayer for your input! I agree that as a target we may want to have different solution here, but it requires further investigation/discussion and design. This PR just removes bugs causing that buttons are unreachable. So I think that it's still worth to merge it now to unblock it. In the future we can take a look once again on that and adjust to design when it's done for this case. Wdyt?

2022-10-11 11:45 UTC, benjthayer commented
Sounds good to me @micieslak - your solution works really nicely!

2022-10-11 14:46 UTC, noeliaSD approved these changes
Ok. Could you add a new issue to give a follow up to this and really agree on the design of this? Thanks

2022-10-11 14:58 UTC, micieslak commented
This PR will be merged as an interim fix. Follow up is defined in this ticket: https://github.com/status-im/status-desktop/issues/7862

2022-10-11 14:58 UTC, merged