fix(MessageView): Changed visual borders of message
status-im/status-desktop pull request #7817
Opened 2022-10-07 13:52 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7815

### What does the PR do

Moved `DateGroupLabel` out of `StatusMessage`. 
Now hovering works correctly.

### Affected areas

chat

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

<img width="1072" alt="Снимок экрана 2022-10-07 в 16 49 09" src="https://user-images.githubusercontent.com/25482501/194569522-40cd6b37-fba5-44ed-ac25-2f1f6b9312de.png">

2022-10-07 13:55 UTC, caybro requested changes
Otherwise looks good

2022-10-07 13:55 UTC, caybro commented on ui/imports/shared/views/chat/MessageView.qml
> +                        root.shouldRepeatHeader || dateGroupLabel.visible || isAReply
`dateGroupLabel.visible`: This is inside a `Component`!

2022-10-07 14:03 UTC, caybro commented on ui/imports/shared/views/chat/MessageView.qml
> +                        root.shouldRepeatHeader || dateGroupLabel.visible || isAReply
Ouch, this is impossible to review now :/

2022-10-07 14:08 UTC, caybro approved these changes

2022-10-12 14:32 UTC, iurimatias commented
@igor-sirotin PR needs rebase

2022-10-18 17:33 UTC, Khushboo-dev-cpp approved these changes
LGTM

2022-10-18 22:36 UTC, elina2015 approved these changes
Tested and approved

2022-10-20 22:44 UTC, merged