feat(Storybook): LogsView added and first model editor
status-im/status-desktop pull request #7856
Opened 2022-10-11 11:25 UTC by micieslak

### What does the PR do

1. Adds model editing for existing page (`CommunitiesPortalLayoutPage.qml`)
It allows modifying content displayed in `CommunitiesPortalPane`. For now I resigned from creating a separate page for `CommunitiesPortalPane` because it wouldn't provide any added value in comparison to what we have in `CommunitiesPortalLayoutPage`.
2. Adds simple component for displaying logs and small example how it's intended to be used

Encountered problem to be fixed in next steps:
1. `CommunitiesPortalLayout` depends on object with id `localAccountSensitiveSettings` (via dynamic scoping)
2. Popups used by `CommunitiesPortalLayout` are tightly coupled with that component. Popups management/handling
is problematic in the whole app and should be rethought/refactored.
3. `CommunitiesPortalPane` - community name is not elided properly, causes stretching description and makes it invisible

Some notes are left in the code and will be addressed in the upcoming works regarding Storybook.

Note: To create model editor I decided to use plain QtQuick instead of custom components from StatusQ. Imo it has some advantages:
- we save time we would have to spend testing/adjusting Storybook after changes in StatusQ
- we avoid regressions in code for manipulating models caused by changes in StatusQ
- standard QtQuick has well defined, stable API, very easy to use
- model editors don't have to look awesome, it's technical utility only

Over time, we will extract some reusable components that are often used in model editors to further streamline the process (for now there is ImageSelectPopup as an example).

Closes: #7816 #7819 #7818

### Affected areas
`CommunitiesPortalLayoutPage`

### Screenshot of functionality (including design for comparison)

[Kazam_screencast_00043.webm](https://user-images.githubusercontent.com/20650004/195077422-eb9887c4-12cd-45c2-b66b-290c2b6cfc30.webm)

2022-10-11 11:31 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b0fa860d | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7856/1/) | 2022-10-11 11:31:41 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7856/1//consoleText) |

2022-10-11 11:36 UTC, caybro requested changes
Nice work, just some minor tidbits

2022-10-11 11:36 UTC, caybro commented on storybook/pages/StorybookUtils.qml
> +pragma Singleton
This seems to be a duplicate file?

2022-10-11 11:36 UTC, caybro commented on storybook/pages/CommunitiesPortalModelEditor.qml
> +                    onCheckedChanged: model.featured = checked
onToggled

2022-10-11 11:36 UTC, caybro commented on storybook/pages/CommunitiesPortalLayoutPage.qml
> +                    id: localAccountSensitiveSettings
This is coming from NIM... no idea how to mock that properly or more efficiently

2022-10-11 11:36 UTC, caybro commented on storybook/Storybook/LogsView.qml
> +    function logEvent(name, argumentNames, args) {
I'd separate the logging functionality from the actual view

2022-10-11 11:36 UTC, caybro commented on storybook/Storybook/LogsView.qml
> +        readOnly: true
add `selectByMouse: true`

2022-10-11 14:05 UTC, osmaczko approved these changes
> Note: To create model editor I decided to use plain QtQuick instead of custom components from StatusQ. Imo it has some advantages:

:+1:

2022-10-11 14:18 UTC, micieslak commented
Thank you @caybro and @osmaczko for reviews! I fixed issues you found. @caybro could you take a look once again?

2022-10-11 14:36 UTC, caybro approved these changes

2022-10-11 14:39 UTC, merged

2026-09-30 08:58 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 3e620c9e | [2666](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2666/) | 2026-09-30 08:58:26 | ~3 min | `unknown` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2666/consoleText) |