fix(@desktop/keycard): onboarding - typo
status-im/status-desktop pull request #7881
Opened 2022-10-13 06:43 UTC by saledjenic

Fixes: #7880

2022-10-13 06:45 UTC, borismelnik approved these changes

2022-10-13 06:46 UTC, osmaczko approved these changes

2022-10-13 06:48 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4e6e4021 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7881/1/) | 2022-10-13 06:48:52 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7881/1//consoleText) |

2022-10-13 07:30 UTC, alaibe approved these changes

2022-10-13 07:56 UTC, caybro requested changes

2022-10-13 07:56 UTC, caybro commented on ui/app/AppLayouts/Onboarding/views/SeedPhraseView.qml
> +            text: qsTr("You will need this to recover your Keycard if you loose\nyour PIN or if the wrong PIN is entered five times in a row.")
There's still one typo ;)

s/loose/lose

2022-10-13 08:14 UTC, caybro approved these changes

2022-10-13 09:04 UTC, merged

2026-10-05 15:07 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | ab2ca311 | [1128](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/1128/) | 2026-10-05 15:07:08 | ~9 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261005-145216-ab2ca3-pr7881-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-261005-145216-ab2ca3-pr7881-arm64.apk&size=400x400&errorCorrectionLevel=L)|