tests(Wallet): add tests for new seed phrase corner cases
status-im/status-desktop pull request #7893
Opened 2022-10-13 18:43 UTC by stefandunca

## Regression tests for the issue fixed by https://github.com/status-im/status-desktop/pull/7885

Note that the new tests fail until merging of the fixes in https://github.com/status-im/status-desktop/pull/7885

Cover the copy-paste corner case for specific seed phrases when having three-words

Also, change the seed phrase filling used in the test to a more realistic method by avoiding the direct input that doesn't generate the event. This way we cover another corner case that relies on user input changing focus and was just fixed

Fix the animation of seed phrase input affecting the clicking using the new seed-phrase inserting.

Updates: #7715

2022-10-13 18:48 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 28248f5f | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7893/1/) | 2022-10-13 18:48:46 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7893/1//consoleText) |

2022-10-14 06:59 UTC, saledjenic approved these changes

2022-10-14 11:45 UTC, noeliaSD requested changes
Code looks good to me but I have issues executing the tests (and once they are correct, please remove the tag `mayfail` if the scenarios are reliable and not broken):

- Both, `User imports a seed phrase using copy-paste` and  `User imports a seed phrase`cannot finish the  last step because the `Add` button is disabled. See screenshot:

![Screenshot 2022-10-14 at 13 34 10](https://user-images.githubusercontent.com/97019400/195838922-c59979ea-f01c-4980-9d9a-c8f71efa1fd9.png)

2022-10-14 12:36 UTC, stefandunca commented on test/ui-test/src/common/SeedUtils.py
> +# Simulate user input of seed phrase by using mouse to trigger enabled events
> please remove the tag mayfail if the scenarios are reliable and not broken

Will do, thanks for the heads up

2022-10-17 11:31 UTC, noeliaSD approved these changes

2022-11-06 10:49 UTC, closed without merging