fix(ProfilePopup): Process declined incoming verification request
status-im/status-desktop pull request #7894
Opened 2022-10-13 18:49 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7377

### What does the PR do

There's no design for what to do when verification was declined.
I've notified @John-44 about this 🙂 

As for now, I implemented own quick solution:
If incoming verification was declined (refused), then we hide "Verify identity pending..." button and show "Verify Identity" instead. Also we automatically close the `ProfilePopup` when the verification was refused.

This is definitely a strange solution, but at least it gives user some response.

### Affected areas

Profile popup

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/25482501/195680232-cd834291-aec7-42eb-9b0c-3d67b0854fc9.mov

2022-10-13 18:55 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 517b57fb | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7894/1/) | 2022-10-13 18:55:22 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7894/1//consoleText) |

2022-10-17 20:28 UTC, osmaczko approved these changes
> This is definitely a strange solution, but at least it gives user some response.

It is indeed :sweat_smile:  I would wait for @John-44 input

2022-10-17 22:33 UTC, caybro requested changes
@igor-sirotin ProfilePopup is dead, long live ProfileDialog ;)

2022-10-18 03:49 UTC, elina2015 commented
@igor-sirotin hey, but the option 'Respond to ID request...' is still shown in menu for the contact that I refused:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/14942081/196330816-bbb3ee53-1142-4b57-8656-7ceea04b6aeb.png">
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/14942081/196331010-a810c60f-85f8-468b-a1a5-c175baab9e16.png">
I believe we should hide this option from the menu as well. Could you kindly check?

2022-10-18 03:50 UTC, elina2015 requested changes
@igor-sirotin hey, but the option 'Respond to ID request...' is still shown in the menu for the contact that I refused:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/14942081/196330816-bbb3ee53-1142-4b57-8656-7ceea04b6aeb.png">
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/14942081/196331010-a810c60f-85f8-468b-a1a5-c175baab9e16.png">
I believe we should hide this option from the menu as well. Could you kindly check?

2022-11-21 13:45 UTC, caybro requested changes

2022-11-21 14:30 UTC, caybro commented on ui/imports/shared/popups/ContactVerificationRequestPopup.qml
> +        StatusFlatButton {
Ah, I couldn't find that one! Good catch :)

2022-11-21 14:30 UTC, caybro approved these changes

2023-04-11 18:11 UTC, iurimatias commented
@igor-sirotin closing as per your comment

2023-04-11 18:11 UTC, closed without merging

2026-10-06 18:29 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | f954ad86 | [2793](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2793/) | 2026-10-06 18:29:49 | ~5 min | `unknown` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2793/consoleText) |
| :heavy_check_mark: | f954ad86 | [1163](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/1163/) | 2026-10-06 18:34:30 | ~10 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261006-182350-f954ad-pr7894-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-261006-182350-f954ad-pr7894-arm64.apk&size=400x400&errorCorrectionLevel=L)|