chore(@storybook): add about view to storybook, refactor about view to use calls from store instead of global
status-im/status-desktop pull request #7895
Opened 2022-10-13 19:09 UTC by iurimatias

### What does the PR do

![Screen Shot 2022-10-13 at 2 46 24 PM](https://user-images.githubusercontent.com/176720/195687281-30b840a3-8a63-4cc8-b26d-da99c8c34506.png)

### Affected areas

AboutView.qml

2022-10-13 19:14 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | bbc82907 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7895/1/) | 2022-10-13 19:14:28 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7895/1//consoleText) |

2022-10-14 08:04 UTC, caybro approved these changes
Looks good but isn't the view center-aligned in status-desktop?

2022-10-14 08:19 UTC, caybro commented
@micieslak we could also "fake" the `Qt.application.displayName/version` :)

2022-10-15 19:39 UTC, micieslak requested changes

2022-10-17 07:23 UTC, caybro commented on ui/app/AppLayouts/Profile/views/AboutView.qml
> +                    root.store.openLink("https://github.com/status-im/status-desktop")
In general I agree with the proposed solution; however we should strive for making AppMain smaller, not bigger :)

2022-10-17 07:37 UTC, micieslak commented on ui/app/AppLayouts/Profile/views/AboutView.qml
> +                    root.store.openLink("https://github.com/status-im/status-desktop")
Yeah, point 6 is about that, the same can be done with e.g. popups that currently live in AppMain

2022-10-17 07:49 UTC, caybro commented on ui/app/AppLayouts/Profile/views/AboutView.qml
> +                    root.store.openLink("https://github.com/status-im/status-desktop")
Yup, I hate e.g. the way we drag the emoji popup around everywhere

2022-10-17 14:02 UTC, micieslak approved these changes
I'm happy to see storybook used!

2022-10-17 14:02 UTC, micieslak commented on ui/app/AppLayouts/Profile/views/AboutView.qml
> +                    root.store.openLink("https://github.com/status-im/status-desktop")
Ok, so for now we have the component adjusted to run in storybook, it works. For further changes there is a separate ticket: https://github.com/status-im/status-desktop/issues/7933

2022-10-17 14:03 UTC, merged

2022-10-18 14:15 UTC, noeliaSD commented on ui/app/AppLayouts/Profile/views/AboutView.qml
> +                    root.store.openLink("https://github.com/status-im/status-desktop")
I do agree with your solution. Great proposal!

2026-10-06 19:06 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | f954ad86 | [2794](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2794/) | 2026-10-06 19:06:23 | ~5 min | `unknown` | [:page_facing_up:`log`](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/2794/consoleText) |
| :heavy_check_mark: | f954ad86 | [1164](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/1164/) | 2026-10-06 19:09:53 | ~8 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261006-190030-f954ad-pr7895-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-261006-190030-f954ad-pr7895-arm64.apk&size=400x400&errorCorrectionLevel=L)|