refactor(@ui/settings): add device syncing section to storybug; fix enable device bug
status-im/status-desktop pull request #7937
Opened 2022-10-17 21:16 UTC by iurimatias

### What does the PR do

Add the device settings section to storybug. also fixes a bug with enable device, found while using storybook.

2022-10-17 21:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 8d0b802f | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7937/1/) | 2022-10-17 21:21:19 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7937/1//consoleText) |

2022-10-18 05:24 UTC, borismelnik approved these changes
LGTM :)

2022-10-18 09:18 UTC, caybro approved these changes

2022-10-18 09:18 UTC, caybro commented on storybook/pages/DevicesSectionPage.qml
> +                            }
LGTM but what is it with the Flow around every CheckBox? :)

2022-10-18 13:53 UTC, noeliaSD requested changes
Something looking strange here ;) : 

![Screenshot 2022-10-18 at 15 49 48](https://user-images.githubusercontent.com/97019400/196449293-0c6bafa3-8704-43a1-a275-b31b1986fba9.png)

2022-10-18 14:00 UTC, noeliaSD commented on ui/app/AppLayouts/Profile/views/DevicesView.qml
> +    property var devicesList
Not sure about the need of this property. Why not use directly the `store.deviceModel`?

2022-10-24 19:13 UTC, merged