fix(CommunitiesGridView): don't display header labels when section empty
status-im/status-desktop pull request #7970
Opened 2022-10-20 06:51 UTC by caybro

Do not display the Featured/Popular labels when the corresponding section is emtpy

Fixes: #7946

### What does the PR do

Fixes wrong section labels

### Affected areas

CommunitiesGridView

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

![Snímek obrazovky z 2022-10-20 08-46-35](https://user-images.githubusercontent.com/5377645/196876712-9a31b285-b1bc-4f10-9723-9b42203c1385.png)

![Snímek obrazovky z 2022-10-20 08-46-30](https://user-images.githubusercontent.com/5377645/196876718-3bfffe45-cb73-4716-874a-835c85b16ca6.png)

2022-10-20 06:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 55de3db8 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7970/1/) | 2022-10-20 06:57:11 | ~5 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-7970/1//consoleText) |

2022-10-20 07:29 UTC, noeliaSD reviewed
Code LGTM but I'm wondering if we should display, as well, the text message if there are no communities. Now the text is only shown when using the searcher but the first time you land on the portal, if there are no communites, there is no info.

![Screenshot 2022-10-20 at 09 27 46](https://user-images.githubusercontent.com/97019400/196884194-01b60eb0-e8b6-491b-9b63-07ce4cd1db5a.png)

2022-10-20 07:31 UTC, caybro commented
> Code LGTM but I'm wondering if we should display, as well, the text message if there are no communities. Now the text is only shown when using the searcher but the first time you land on the portal, if there are no communites, there is no info.
> 
> ![Screenshot 2022-10-20 at 09 27 46](https://user-images.githubusercontent.com/97019400/196884194-01b60eb0-e8b6-491b-9b63-07ce4cd1db5a.png)

Yeah that's a good point; I believe there's no figma design for this usecase. I can definitely adjust the message to be shown in this case too (not just when the search is empty)

2022-10-20 12:29 UTC, micieslak requested changes
One minor thing:
When there is no popular communities, corresponding grid view should be hidden as well. Otherwise we end up with slightly inconsistent spacing:

[Kazam_screencast_00069.webm](https://user-images.githubusercontent.com/20650004/196948679-692bfac6-4e4c-4eee-b487-14bcbfade2ec.webm)

2022-10-20 14:55 UTC, alexandraB99 commented
> > Code LGTM but I'm wondering if we should display, as well, the text message if there are no communities. Now the text is only shown when using the searcher but the first time you land on the portal, if there are no communites, there is no info.
> > ![Screenshot 2022-10-20 at 09 27 46](https://user-images.githubusercontent.com/97019400/196884194-01b60eb0-e8b6-491b-9b63-07ce4cd1db5a.png)
> 
> Yeah that's a good point; I believe there's no figma design for this usecase. I can definitely adjust the message to be shown in this case too (not just when the search is empty)

You can use the same text for now, but please ask @John-44 as design might want to show a different text/component in this case.

2022-10-20 14:56 UTC, alexandraB99 approved these changes

2022-10-20 16:05 UTC, caybro commented
> 

Fixed

2022-10-20 16:06 UTC, caybro commented
> > > Code LGTM but I'm wondering if we should display, as well, the text message if there are no communities. Now the text is only shown when using the searcher but the first time you land on the portal, if there are no communites, there is no info.
> > > ![Screenshot 2022-10-20 at 09 27 46](https://user-images.githubusercontent.com/97019400/196884194-01b60eb0-e8b6-491b-9b63-07ce4cd1db5a.png)
> > 
> > 
> > Yeah that's a good point; I believe there's no figma design for this usecase. I can definitely adjust the message to be shown in this case too (not just when the search is empty)
> 
> You can use the same text for now, but please ask @John-44 as design might want to show a different text/component in this case.

@alexandraB99 @noeliaSD Fixed

2022-10-21 07:00 UTC, noeliaSD approved these changes

2022-10-21 09:02 UTC, micieslak approved these changes
lgtm!

2022-10-21 09:40 UTC, merged