feat(storybook): add browser settings in the storybook
status-im/status-desktop pull request #8010
Opened 2022-10-21 14:06 UTC by jrainville

Adds browser settings to the storybook.

Branched off of https://github.com/status-im/status-desktop/pull/7944 so I could inspire myself

![image](https://user-images.githubusercontent.com/11926403/197215146-ec6b28f0-3afb-4d55-be2c-ee0ab872ba81.png)

2022-10-21 14:11 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | fc26c983 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8010/1/) | 2022-10-21 14:11:38 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8010/1//consoleText) |

2022-10-21 14:45 UTC, caybro reviewed
Looks good! Some minor stuff only

2022-10-21 19:44 UTC, jrainville commented
Great suggestions @caybro

2022-10-23 19:50 UTC, borismelnik commented on ui/app/AppLayouts/Profile/views/BrowserView.qml
> +                        onToggled: { accountSettings.shouldShowFavoritesBar = checked }
I'm not sure if `checked` property was changed before `toggled` signal, so basically, its equal to `accountSettings.shouldShowFavoritesBar = accountSettings.shouldShowFavoritesBar`

2022-10-24 08:14 UTC, micieslak requested changes
Hey, I'm really glad to see storybook in use! :)

It's nice work however I have some doubts.
The page should run without any errors/warnings, but in this case I see many many of them:
```
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
file:///home/michalc/workspace/status-desktop/ui/StatusQ/src/StatusQ/Components/StatusListItem.qml:165:9: QML QQuickItem*: Binding loop detected for property "height"
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml:50:21: Unable to assign [undefined] to int
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/views/wallet/PermissionsListView.qml:50:21: Unable to assign [undefined] to int
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:78: TypeError: Cannot read property 'communitiesModule' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:77: TypeError: Cannot read property 'model' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:76: ReferenceError: communitiesModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:74: ReferenceError: localAccountSensitiveSettings is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:73: ReferenceError: localAccountSensitiveSettings is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Chat/stores/StickersStore.qml:9: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:68: ReferenceError: stickersModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:65: TypeError: Cannot read property 'keycardModule' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:57: ReferenceError: dappPermissionsModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:43: ReferenceError: walletSectionCurrent is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:26: ReferenceError: walletSectionAllTokens is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:25: ReferenceError: walletSectionAllTokens is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:24: ReferenceError: walletSectionAllTokens is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:23: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:22: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:21: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:20: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:14: ReferenceError: networksModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:13: ReferenceError: networksModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:12: ReferenceError: networksModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:11: ReferenceError: networksModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/WalletStore.qml:9: ReferenceError: localAccountSensitiveSettings is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml:17: ReferenceError: walletSectionAccounts is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml:15: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml:13: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml:12: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/EnsUsernamesStore.qml:11: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:58: TypeError: Cannot read property 'ensUsernamesModule' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/PrivacyStore.qml:10: TypeError: Cannot read property 'mnemonicBackedUp' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:54: TypeError: Cannot read property 'privacyModule' of undefined
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:548: ReferenceError: mainModule is not defined
file:///home/michalc/workspace/status-desktop/ui/imports/utils/Utils.qml:10: ReferenceError: globalUtils is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:23: TypeError: Cannot read property 'socialLinksDirty' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:22: TypeError: Cannot read property 'temporarySocialLinksModel' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:21: TypeError: Cannot read property 'socialLinksModel' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:20: TypeError: Cannot read property 'socialLinksJson' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:19: TypeError: Cannot read property 'bio' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:17: ReferenceError: profileSectionModule is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:16: ReferenceError: localAccountSensitiveSettings is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:15: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:14: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:13: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:12: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:11: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:10: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileStore.qml:9: ReferenceError: userProfile is not defined
file:///home/michalc/workspace/status-desktop/ui/app/AppLayouts/Profile/stores/ProfileSectionStore.qml:50: TypeError: Cannot read property 'profileModule' of undefined
file:///home/michalc/workspace/status-desktop/ui/app/App [...]

2022-10-24 10:30 UTC, borismelnik approved these changes

2022-10-24 16:38 UTC, jrainville commented on storybook/pages/BrowserSettingsPage.qml
> +                                dappsModel.remove(0)
No :see_no_evil:

2022-10-24 16:45 UTC, jrainville commented on storybook/pages/BrowserSettingsPage.qml
> +            // TODO find a way to imbricate another ListModel for the accounts
That was fixed in a later version. I just forgot to remove the comment sorry.

2022-10-24 18:32 UTC, jrainville commented
@micieslak thanks for the review. I updated accordingly

2022-10-25 11:16 UTC, micieslak requested changes
Thanks for fixes, really good job! Some other smaller issues found, but now it's in a much better shape.

At the startup, there is a warning:
```
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
```
We need to add `WebEngine` to `CMakeLists.txt` and call `QtWebEngine::initialize();` in main to fix it.

2022-10-25 14:45 UTC, jrainville commented on storybook/pages/BrowserSettingsPage.qml
> +            property string browserHomepage: "https://status.im/"
We use QtProperties for Settings, so technically, in the backend of the real data, it does use a setter. Changing all settings to use the setters directly and also adding those setters to the mock data sounds very painful for the little gain it adds a far as I see it.
What do you think?

2022-10-25 14:45 UTC, jrainville commented
@micieslak updated!

2022-10-25 15:15 UTC, micieslak commented on storybook/pages/BrowserSettingsPage.qml
> +            property string browserHomepage: "https://status.im/"
for now I would leave it as it is, but for the future we should aim modifying state of backend via methods exposed from stores. And expose state of backed via readonly properties from stores. It's really beneficial from the code design perspective.

2022-10-25 15:16 UTC, micieslak approved these changes
cool!

2022-10-25 18:27 UTC, merged

2026-10-28 16:44 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d925b312 | [1765](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/1765/) | 2026-10-28 16:44:08 | ~10 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-163227-d925b3-pr8010-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-261028-163227-d925b3-pr8010-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | d925b312 | [3371](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/3371/) | 2026-10-28 16:50:21 | ~17 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-163227-d925b3-pr8010-x86_64.tar.gz) |
| :heavy_check_mark: | d925b312 | [1767](https://ci.status.im/job/status-app/job/systems/job/android/job/arm64/job/package/1767/) | 2026-10-28 17:14:17 | ~10 min | `android/arm64` | [:robot:`apk`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-170030-d925b3-pr8010-arm64.apk) [:calling:](https://quickchart.io/qr?text=https%3A%2F%2Fstatus-app-builds.hel1.your-objectstorage.com%2FStatusIm-Desktop-261028-170030-d925b3-pr8010-arm64.apk&size=400x400&errorCorrectionLevel=L)|
| :heavy_check_mark: | d925b312 | [3373](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/package/3373/) | 2026-10-28 17:27:00 | ~16 min | `linux/x86_64` | [:package:`tgz`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-170030-d925b3-pr8010-x86_64.tar.gz) |
| :heavy_check_mark: | d925b312 | [3356](https://ci.status.im/job/status-app/job/systems/job/macos/job/aarch64/job/package/3356/) | 2026-10-28 17:43:00 | ~20 min | `unknown` | [:apple:`dmg`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-170030-d925b3-pr8010-aarch64.dmg) |
| :heavy_check_mark: | d925b312 | [1379](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/1379/) | 2026-10-28 17:43:31 | ~16 min | `tests/e2e` | [:bar_chart:`rpt`](https://ci.status.im/job/status-app/job/systems/job/linux/job/x86_64/job/tests-e2e/1379/allure/) |
| :heavy_check_mark: | d925b312 | [3172](https://ci.status.im/job/status-app/job/systems/job/windows/job/x86_64/job/package/3172/) | 2026-10-28 18:48:16 | ~23 min | `windows/x86_64` | [:cd:`exe`](https://status-app-builds.hel1.your-objectstorage.com/StatusIm-Desktop-261028-170030-d925b3-pr8010-x86_64.exe) |