chore(StatusQ): fix Sandbox release build
status-im/status-desktop pull request #8060
Opened 2022-10-26 18:36 UTC by osmaczko

- regenerated qrc files
- added qrc files as CMake's Sandbox target dependency

2022-10-26 18:41 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 52b60598 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8060/1/) | 2022-10-26 18:41:16 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8060/1//consoleText) |

2022-10-27 07:58 UTC, micieslak approved these changes
LGTM!

2022-10-27 07:59 UTC, caybro approved these changes

2022-10-27 08:21 UTC, micieslak requested changes
StatusQ Release build fails:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:66:5: Type StatusMainLayout unavailable
qrc:/StatusQ/Layout/StatusMainLayout.qml: No such file or directory
```

2022-10-27 08:29 UTC, micieslak commented
> StatusQ Release build fails:
> 
> ```
> QQmlApplicationEngine failed to load component
> qrc:/main.qml:66:5: Type StatusMainLayout unavailable
> qrc:/StatusQ/Layout/StatusMainLayout.qml: No such file or directory
> ```

Ok, I was wrong. It builds but changes in main.qml are not reflected without total rebuild.

2022-10-27 08:58 UTC, micieslak approved these changes

2022-10-27 09:40 UTC, merged