fix(invitation-bubble): Add maximum line count to description and elide
status-im/status-desktop pull request #8207
Opened 2022-11-11 12:43 UTC by borismelnik

Closes: #8120

### What does the PR do

Fix description sizes

### Affected areas

InvitationBubbleView

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

<img width="585" alt="Снимок экрана 2022-11-11 в 15 39 11" src="https://user-images.githubusercontent.com/82511785/201342796-3273efec-5012-449e-98ba-0ffefcb98b07.png">

2022-11-11 12:47 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f71a416a | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8207/1/) | 2022-11-11 12:47:42 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8207/1//consoleText) |

2022-11-11 12:56 UTC, PascalPrecht approved these changes

2022-11-11 12:57 UTC, caybro approved these changes

2022-11-11 18:40 UTC, osmaczko approved these changes

2022-11-14 09:26 UTC, endulab requested changes
This is a duplication of https://github.com/status-im/status-desktop/pull/8198.
Also the solution is not sufficient. For separated lines it works ok, but not for a very long line:

![image](https://user-images.githubusercontent.com/61889657/201623328-eeeed2d5-8064-414c-a9f0-f426967bcdd7.png)

In my pr I added tooltips for cut text. 
Also I noticed that for a long text & maximumLineCount there is some problem with computing height correctly and there is the error:

```qrc:/imports/shared/views/chat/InvitationBubbleView.qml:81:26: QML Rectangle: Binding loop detected for property "height"```

For one line is ok.

2022-11-14 11:53 UTC, borismelnik commented
Closed bc of [#8198](https://github.com/status-im/status-desktop/pull/8198)

2022-11-14 11:53 UTC, closed without merging