feat(Storybook): Foldable sections in pages list
status-im/status-desktop pull request #8286
Opened 2022-11-16 13:52 UTC by micieslak

### What does the PR do

Provides 2-level foldable sections for storybook's pages list. Model is implemented in c++, thanks to that qml code stays simple and modular.

Note: current implementation is suboptimal (internal model reset on source model filtering), but sufficient for that case. In the future similar approach can be used in other parts of the application for speed, clean code and separation of concerns.

Basic unit tests has been added for the c++ module. It can be run conveniently from QtCreator or via cmake/ctest.

### Affected areas
Storybook's pages list

### Screenshot of functionality (including design for comparison)

[Kazam_screencast_00083.webm](https://user-images.githubusercontent.com/20650004/202198121-bd9bcf6e-0d14-45fb-9b57-586107c3e188.webm)

2022-11-16 13:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | cae026ab | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8286/1/) | 2022-11-16 13:57:03 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8286/1//consoleText) |

2022-11-16 14:15 UTC, caybro requested changes
Overall looks good, I like the approach, just some minor impl details

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +    if(!index.isValid()) return {};
Use `QAbstractItemModel::checkIndex(const QModelIndex &index, QAbstractItemModel::CheckIndexOptions options = CheckIndexOption::NoOption)` instead

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +    roles.insert(IsSectionRole, QStringLiteral("isSection").toUtf8());
```suggestion
    roles.insert(IsSectionRole, QByteArrayLiteral("isSection"));
```
and so on

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +    roles.insert(SubitemsCountRole, QStringLiteral("subitemsCount").toUtf8());
Make the whole `roles` static and initialize it using `std::initializer_list` CTOR

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +            m_rowsMetadata.push_back({true, section});
`emplace_back`

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +        m_rowsMetadata.push_back({false});
`emplace_back`

2022-11-16 14:15 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +    QHash<int, QByteArray> roleNames = m_sourceModel->roleNames();
`const auto roleNames`

2022-11-16 14:15 UTC, caybro commented on storybook/src/Storybook/PagesList.qml
>          width: parent.width
should be `ListView.view.width`

2022-11-16 15:29 UTC, caybro approved these changes
Looks good!

2022-11-16 16:19 UTC, caybro commented on storybook/sectionsdecoratormodel.cpp
> +    roles.insert(SubitemsCountRole, QStringLiteral("subitemsCount").toUtf8());
I see, yeah it doesn't make much sense since you're extending the role names

2022-11-17 10:23 UTC, noeliaSD approved these changes
Very good job! Thanks for adding as well unit tests!

2022-11-18 10:01 UTC, alexjba commented on storybook/sectionsdecoratormodel.cpp
> +    auto &row = m_rowsMetadata[index];
Check vector boundaries

2022-11-18 10:27 UTC, alexjba commented on storybook/sectionsdecoratormodel.cpp
> +        qWarning("Changing source model is not supported!");
::initialize and :: findSectionRole assume m_sourceModel != nullptr. Calling setSourceModel(nullptr) would crash the app.

2022-11-18 10:35 UTC, alexjba reviewed
Nice approach! 👍 
Some small comments

2022-11-21 11:51 UTC, merged