feat(tst_chatsNavigation): Restored chats navigation tests
status-im/status-desktop pull request #8331
Opened 2022-11-18 15:27 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/7916

Opened an issue as a continuation of this PR:
- https://github.com/status-im/status-desktop/issues/8379

### Affected areas

automation tests

2022-11-18 15:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | c82f592e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8331/1/) | 2022-11-18 15:33:00 | ~5 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8331/1/consoleText) |

2022-11-18 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.py
> +collectStepDefinitions('./steps', '../shared/steps/', '../../global_shared/steps/', '../../suite_onboarding/shared/steps/')
I think you can remove the dependence to `suite_onboarding` here bc you are not using any step from there in your feature file. You are adding the onboarding steps into the `hooks` file.

2022-11-18 15:46 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/bdd_hooks.py
> +    # Detach current app.
leftover??

2022-11-22 15:54 UTC, jrainville approved these changes

2022-11-23 10:40 UTC, noeliaSD requested changes
It needs a rebase! 

Added minor comments!

2022-11-23 10:40 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/steps.py
> +    StartupSteps.waitFor(lambda: StartupSteps.currentApplicationContext().detach(), 500)
I think neither `waitFor` not `currentApplicationContext()` are part of `StartupSteps`. Just discard this changes!

2022-11-23 10:40 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/steps.py
> +    StartupSteps.startApplication(context.userData["aut_name"])
Same here, not part of `StartupSteps` so discard this changes!

2022-11-23 10:40 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/steps.py
> +    StartupSteps.the_user_clicks_on_the_following_ui_component(obj)
I think it should be like this: 
 
```suggestion
    init_steps.the_user_clicks_on_the_following_ui_component(obj)
```

2022-11-24 15:43 UTC, noeliaSD reviewed
Here some comments!!

2022-11-24 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +    @merge
Remove this tag since you've already added the `onFeatureStart` steps, it can be enabled in the ci bc the time-consuming steps have been reduced.

2022-11-24 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +
It would be good to add as a comment, the steps that are done in `onFeatureStart`. See `tst_chatFlow` feature file as a reference.

2022-11-24 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/steps.py
> +    init_steps.waitFor(lambda: init_steps.currentApplicationContext().detach(), 500)
I think these two methods are not part of the `init_steps` file.
```suggestion
   waitFor(lambda:currentApplicationContext().detach(), 500)
```

2022-11-24 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/steps.py
> +    init_steps.startApplication(context.userData["aut_name"])
I think it is not part of the `init_steps` file:
```suggestion
   startApplication(context.userData["aut_name"])
```

2022-11-24 15:43 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +Feature: Status Desktop Chat Navigation
@glitchminer could you review these new BDD scenarios?

2022-11-24 15:56 UTC, jrainville approved these changes

2022-11-24 17:02 UTC, glitchminer reviewed
chatsNavigation feature reviewed.

2022-11-24 17:02 UTC, glitchminer commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +    Scenario: The user sees chats sorted by most recent activity
Would prefer it if these had a Given step and if they were split into 2 scenarios, but they're probably specific enough that it's not an issue.

Suggesting a minor revision:

```
When the user joins the chat named "first-chat"
And the user joins the chat named "second-chat"
And the user joins the chat named "third-chat"
Then the chat navigation is sorted by most recent first
| third-chat      |
| second-chat  |
| first-chat        |

When the user switches to "second-chat" chat
And the user sends a random chat message
Then the random chat message is displayed
Then the chat navigation is sorted by most recent first
| second-chat |
| third-chat      |
| first-chat       |
```

If it's useful for other scenarios, the step could also be configured to accept all the required chats in one go:
```
When the user joins chats
| first-chat       |
| second-chat  |
| third-chat       |
Then the user chats are sorted by most recent first
| third-chat      |
| second-chat  |
| first-chat        |

2022-11-24 17:02 UTC, glitchminer commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +        When the user switches to "second-chat" chat
Is switches to and joins different behaviour, or different name for same thing?

2022-11-25 08:17 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +    Scenario: The user joins a room and marks it as read
Although the verification is not done, we can still enable the actions since if there is a regression, it could fail and also help.

2022-11-25 08:23 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +	** when the user opens the chat section
Is it correct??? I cannot see this action in the `bdd_hooks`!

2022-11-30 15:39 UTC, noeliaSD commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +	** when the user opens the chat section
Oh! That's true! I don't know how I read it! :)
Forget my previous comment!

2022-11-30 15:40 UTC, noeliaSD approved these changes

2022-12-06 20:01 UTC, glitchminer approved these changes
Features/Comments only reviewed

2022-12-06 20:01 UTC, glitchminer commented on test/ui-test/testSuites/suite_messaging/tst_chatsNavigation/test.feature
> +        When the user switches to "second-chat" chat
OK, fine to leave this as it is then. Ideally we can find some terminology to make this distinction clearer in future.

2022-12-06 20:42 UTC, merged