fix(Settings): better error handling for toggling archive protocol
status-im/status-desktop pull request #8354
Opened 2022-11-21 12:54 UTC by PascalPrecht

Enabling the community archive protocol could fail when another app is using the same port that is specified as torrent client port.

This would cause the app to crash.

With these changes we:

1. No longer crash the app but output an error in the logs
2. We popup a dialog telling the user that the specified pord is in use

Closes #7328

2022-11-21 12:54 UTC, PascalPrecht commented
![Screenshot from 2022-11-21 13-50-09](https://user-images.githubusercontent.com/445106/203060504-1f0043f1-bce4-4de9-94f2-b5299adca015.png)

2022-11-21 14:02 UTC, caybro approved these changes
Looks good!

2022-11-21 16:00 UTC, osmaczko requested changes
Looks ok :+1:  one small improvement to apply

2022-11-21 16:00 UTC, osmaczko commented on ui/app/AppLayouts/Profile/views/AdvancedView.qml
> +            target: advancedStore.advancedModule
(You can ignore this comment) I know this approach is repeated all over the place in our codebase but Views shouldn't know anything about module instances.

Possible solution, AdvancedStore.qml:
```
signal enableCommunityHistoryArchiveSupportFailed
Connections {
    target: advancedModule
    function onEnableCommunityHistoryArchiveSupportFailed() {
        root.enableCommunityHistoryArchiveSupportFailed()
    }
}
```

2022-11-21 16:00 UTC, osmaczko commented on ui/app/AppLayouts/Profile/views/AdvancedView.qml
> +                }
```suggestion
                standardButtons: Dialog.Ok
                onAccepted: errorMessageDialog.close()
```

2022-11-23 08:56 UTC, osmaczko approved these changes

2022-11-23 13:56 UTC, merged