fix(Contacts): Add self id for identity verification requests
status-im/status-desktop pull request #8380
Opened 2022-11-22 10:38 UTC by MishkaRogachev

Close #8277

### What does the PR do

Fix accepting and declining identity verification requests

### Affected areas

Contacts

### Screenshot of functionality (including design for comparison)

..in progress

2022-11-22 10:44 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d569dfe0 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8380/1/) | 2022-11-22 10:44:06 | ~4 min | `linux-cpp` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8380/1//consoleText) |

2022-11-22 10:46 UTC, MishkaRogachev commented
@jrainville @PascalPrecht accept/decline identity verification request were not working because we used public key instead of request.Id.  Where are two ways:
1) Switch on request.id everywhere, including QML. That's more solid but needs more time.
2) Use request.id only on service and status-go layers. That's the way how contact requests works nowadays. This solution is much faster but it "smells"

2022-11-22 15:51 UTC, jrainville commented
@MishkaRogachev IMO, solution 2 sounds fine. The front-end doesn't necessarily need to know about request id for now. As long as the backend can do the operation easily, it's ok.
If you want, you can add a ticket to refactor that in the future, but it might never get done :sweat_smile:

2022-11-23 07:29 UTC, PascalPrecht commented
I agree with @jrainville and think this is a pragmatic solution to get the non-working feature functional.
Great find @MishkaRogachev !

2022-11-24 15:23 UTC, jrainville approved these changes

2022-11-25 08:35 UTC, endulab requested changes

2022-11-25 08:35 UTC, endulab commented on src/app_service/service/contacts/service.nim
> +      var response = status_contacts.getVerificationRequestSentTo(publicKey)
this may return error

2022-11-25 08:35 UTC, endulab commented on src/app_service/service/contacts/service.nim
> +      self.events.emit(SIGNAL_CONTACT_TRUSTED,
signals should be sent in "if" clause ?

2022-11-25 08:35 UTC, endulab commented on src/app_service/service/contacts/service.nim
> +      var response = status_contacts.getVerificationRequestSentTo(publicKey)
this may return error

2022-11-25 08:35 UTC, endulab commented on src/app_service/service/contacts/service.nim
> +      self.events.emit(SIGNAL_CONTACT_UNTRUSTWORTHY,
signals should be sent in if clause

2022-11-25 15:24 UTC, jrainville approved these changes

2022-11-28 10:03 UTC, endulab approved these changes

2022-11-28 10:14 UTC, merged