hotfix(ActivityCenter): Fix binding loop for previousMessageIndex
status-im/status-desktop pull request #8412
Opened 2022-11-23 14:56 UTC by MishkaRogachev

### What does the PR do

Should help with binding loop with Qt 5.15

### Affected areas

ActivityCenter

### Screenshot of functionality (including design for comparison)

...todo

2022-11-23 15:02 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 48b4bc12 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8412/1/) | 2022-11-23 15:01:59 | ~4 min | `imports` | [:package:`pkg`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8412/1//consoleText) |

2022-11-23 15:14 UTC, caybro requested changes

2022-11-23 15:14 UTC, caybro commented on ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml
> +        if (previousMessageTimestamp === "" || messageTimestamp === "")
Comparing `double` to `string`

2022-11-23 15:14 UTC, caybro commented on ui/imports/shared/views/chat/MessageView.qml
> +                previousMessageTimestamp: root.prevMessageIndex === -1 ? "" : root.prevMsgTimestamp
Assigning `string` to a `double` property

2022-11-23 16:15 UTC, MishkaRogachev commented on src/app/modules/main/activity_center/model.nim
> +      let topLeft = self.createIndex(0, 0, nil)
TODO: that should be optimised

2022-11-24 11:30 UTC, MishkaRogachev commented on ui/app/mainui/activitycenter/views/ActivityNotificationBase.qml
> +        previousMessageTimestamp: filteredIndex === 0 || !notification.previousTimestamp ? 0 : notification.previousTimestamp
And this is needed because we always want to render timestamp label for the first item even when we have filter enabled

2022-11-29 10:42 UTC, caybro approved these changes
The repeated items likely come from DelegateChooser and will be dealt with separately

2022-11-29 12:49 UTC, merged

2022-11-29 12:55 UTC, MishkaRogachev commented
> The binding loop warning is gone but I'm still getting duplicated and misordered items:
> 
> ![image](https://user-images.githubusercontent.com/5377645/204501905-efca75f1-43f5-4c73-9efc-258edbd5ecb5.png)
> 
> Notice the contact request from Benji (Yesterday) being correctly placed at the top where it belongs, but then again repeated at the bottom

Opened issue for that: https://github.com/status-im/status-desktop/issues/8499