feat(activity-center): Add details view dialog for contact requests
status-im/status-desktop pull request #8639
Opened 2022-12-05 15:46 UTC by borismelnik

Fixes: #8461

### What does the PR do

Details view popup for Contact Requests

### Affected areas

Activity Center

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

https://user-images.githubusercontent.com/82511785/205679961-8ec2c404-be76-42db-88cc-cf466e1b3b05.mov

2022-12-05 15:51 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | fbee30b3 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8639/1/) | 2022-12-05 15:51:19 | ~5 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-8639/1//consoleText) |

2022-12-05 18:39 UTC, jrainville reviewed
Good job. I just have small questions and suggestions

2022-12-05 18:39 UTC, jrainville commented on ui/app/mainui/activitycenter/popups/ReviewContactRequestPopup.qml
> +    property StatusMessageDetails messageDetails: StatusMessageDetails {
Is it necessary to construct this component here? Do we reuse those properties a lot or we could just set the values directly in the right places below?

2022-12-05 19:44 UTC, caybro commented
Can you pls fix what's already obvious from the video you posted? :) The text overflowing into the accept/reject buttons

2022-12-05 20:59 UTC, jrainville commented
> Can you pls fix what's already obvious from the video you posted? :) The text overflowing into the accept/reject buttons

@MishkaRogachev might already be fixing that. The reason I assigned this to Boris even though Mishka is the one on all the AC tasks is because of the low chance of conflict.

2022-12-05 21:14 UTC, caybro requested changes

2022-12-05 21:14 UTC, caybro commented on ui/app/mainui/activitycenter/popups/ReviewContactRequestPopup.qml
> +StatusModal {
StatusDialog? StatusModal is deprecated

2022-12-05 21:14 UTC, caybro commented on ui/app/mainui/activitycenter/popups/ReviewContactRequestPopup.qml
> +            text: "Accept Contact Request"
qsTr()

2022-12-05 21:14 UTC, caybro commented on ui/app/mainui/activitycenter/popups/ReviewContactRequestPopup.qml
> +            text: "Reject Contact Request"
qsTr()

2022-12-05 21:14 UTC, caybro commented on ui/app/mainui/activitycenter/views/ActivityNotificationContactRequest.qml
> +    ReviewContactRequestPopup {
I'd say yes; we might want to (re)use it from the Profile Dialog at some point

2022-12-06 07:49 UTC, MishkaRogachev requested changes
<img width="669" alt="Screenshot 2022-12-06 at 11 24 58" src="https://user-images.githubusercontent.com/2522130/205847607-07b3fb2d-cb27-4b3e-94fd-4bb9c67ec9dd.png">

The text here is cropped with CTA component

2022-12-06 11:34 UTC, borismelnik commented
Thank you guys, will fix it asap

2022-12-06 18:32 UTC, borismelnik commented
<img width="591" alt="Снимок экрана 2022-12-06 в 21 30 39" src="https://user-images.githubusercontent.com/82511785/205993026-d8629906-1ef9-4c16-80d6-64f58082ed92.png">

I also fixed it cos it one line fix.

2022-12-06 19:00 UTC, MishkaRogachev approved these changes

2022-12-06 19:08 UTC, jrainville approved these changes

2022-12-07 09:03 UTC, merged