feat(CommunityPermissions): search for collectibles dropdown
status-im/status-desktop pull request #8669
Opened 2022-12-06 16:02 UTC by micieslak

### What does the PR do

- `HoldingsDropdown` added to the Storybook
- some routines not related to backend excluded from `CommunitiesStore` to `CommunityPermissionsHelpers`
- search for collectibles dropdown 

Closes: https://github.com/status-im/status-desktop/issues/7158

### Affected areas

`Storybook`, `ExtendedDropdownContent`

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2022-12-06 16:07 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 25468bb4 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8669/1/) | 2022-12-06 16:07:43 | ~4 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8669/1//consoleText) |

2022-12-07 10:26 UTC, caybro approved these changes
Looks nice!

2022-12-07 10:59 UTC, noeliaSD requested changes
Code LGTM, just minor suggestions and added some coments here:

1. `Search` text seems higher than in design and also the icon (I guess it is an issue of the component so it can be addressed in a separate task):
 
![Screenshot 2022-12-07 at 11 52 41](https://user-images.githubusercontent.com/97019400/206160450-e7a16e7d-eed4-43c2-a4f7-1bdfa86fcc08.png)

2. Something is wrong with the visualization of this data:

![Screenshot 2022-12-07 at 11 53 56](https://user-images.githubusercontent.com/97019400/206160779-500f87ec-3bf5-4d06-8c05-69eda35d8e16.png)

3. I'm not sure about the flow of the searcher, i.e. if I search for an item that has subitems, but then when I click to the item to navigate to the subitems, should the search filter be reset? If not we can have situations like this:

https://user-images.githubusercontent.com/97019400/206161770-caaadd93-bdb9-4e6e-b201-070b16299b47.mov

2022-12-08 12:17 UTC, micieslak commented on storybook/pages/HoldingsDropdownPage.qml
> +            readonly property ListModel tokensModel: ListModel {
I'll update it on occasion. At the moment it is not merged yet.

2022-12-08 12:21 UTC, micieslak commented
Thanks @noeliaSD for your comments! Very good points. I fixed points 2 and 3 and left question in figma file about point 1 (bc search boxes in the design are inconsistent, look slightly different in various places). Earlier I also asked about expected behavior in some cases bc it's not fully specified right now. For now there is no other option that treating it as a some kind of first version for further improvements when details are specified and backend ready.

2022-12-08 13:31 UTC, alexjba approved these changes
Looks good! Also tested with latest version and it looks good to me

2022-12-09 08:58 UTC, noeliaSD approved these changes
LGTM! Thanks for the updates! :)

Just as a reminder, since it is a new feature, it should be also tested by the QA team!

2022-12-13 16:41 UTC, glitchminer approved these changes
Tested, approved with caveats:

No written acceptance criteria were provided for the implemented components. The following observations were made in comparison to Figma that could be addressed when the expected behaviour for MVP is finalised.

1. Magnifying glass icon is smaller in Figma 12x12 compared to app 17x17
2. Distance between magnifying glass and "Search" smaller in Figma
3. Search field not in focus when opening the search
4. Search field not in focus when using "Back" to return to the search
5. Icons for collectibles are larger in Figma 32x32 compared to app 25x25

Summary:
It was possible to navigate to the collectibles search
Search using a full or partial term regardless of case
View relevant results
Navigate into a group and use back to return to results
Checks performed in both app and storybook

2022-12-14 07:45 UTC, noeliaSD commented on storybook/pages/HoldingsDropdownPage.qml
> +            readonly property ListModel tokensModel: ListModel {
Now it is already merged!

2022-12-15 23:52 UTC, merged