Use binaries from qt installation when building
status-im/status-desktop pull request #8788
Opened 2022-12-14 12:25 UTC by arnetheduck

Since there may be multiple QT versions installed, the compilation process should use the binaries from the given QTDIR, same as the rest of it.

In particular, this allows compiling on Fedora with the right devel packages installed (of which there are many).

### What does the PR do

### Affected areas

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

- [ ] I've checked the design and this PR matches it

### Cool Spaceship Picture

<!-- optional but cool ->

2022-12-14 12:29 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :interrobang: | 3d0051aa | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8788/1/) | 2022-12-14 12:29:45 | ~4 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-8788/1/consoleText) |

2022-12-14 12:58 UTC, caybro approved these changes
LGTM

2022-12-14 12:59 UTC, caybro requested changes
Actually, pls retarget the PR against master

2022-12-14 13:06 UTC, arnetheduck commented
ok, just retargeting in github doesn't work - it should be easy to cherry-pick - I'll see when I have time to do so

2023-02-21 16:33 UTC, arnetheduck commented
obsoleted by new `qmake` way of building

2023-02-21 16:33 UTC, closed without merging