feat(ActivityCenter): Update ActivityNotificationMessage's text maximum width
status-im/status-desktop pull request #9003
Opened 2023-01-09 11:14 UTC by MishkaRogachev

Close #8915, close #8950

### What does the PR do

Limit ActivityNotificationMessage's text to 350 chars (That should be fixed value  tom make all notifications look similar)

### Affected areas

ActivityCenter

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

<img width="565" alt="Screenshot 2023-01-09 at 15 02 00" src="https://user-images.githubusercontent.com/2522130/211295720-d1b67938-6d28-4a0c-9845-b04f716c3b1c.png">

2023-01-09 11:19 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | ca56bd83 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9003/1/) | 2023-01-09 11:19:42 | ~5 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9003/1//consoleText) |

2023-01-09 11:31 UTC, endulab approved these changes

2023-01-09 19:24 UTC, caybro reviewed
You see how brittle these hardcoded values are ;)

Remind me next time when we have to change this again :)

2023-01-09 19:28 UTC, jrainville reviewed
The most common AC message is a mention or reply, which just has a check mark button, so wouldn't that create a big gap on the right?

I think we need to be smarter with that width and adapt to what's on the right (using a Row or something)

2023-01-10 03:29 UTC, elina2015 requested changes
@MishkaRogachev the bug is still reproduced and the date became incorrect. Could you kindly check? 
<img width="501" alt="image" src="https://user-images.githubusercontent.com/14942081/211455113-57abaed8-3e6d-405f-9a39-1bc6b3cd9a92.png">
Also, after changing the answer, the button is overlapped with the text:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/14942081/211455301-e46bd0f9-025b-4883-ba03-b27719cabc80.png">

2023-01-10 16:34 UTC, elina2015 approved these changes

2023-01-10 16:39 UTC, merged