Fix/issue 8947
status-im/status-desktop pull request #9027
Opened 2023-01-10 12:34 UTC by alexandraB99

### What does the PR do
Fixes Community left column banners where overlapping

### Affected areas
Community left column

### Screenshot of functionality (including design for comparison)
<img width="1004" alt="comm" src="https://user-images.githubusercontent.com/31625338/211552689-e7c1d82a-a9f0-41d3-96b3-4ab73b2f5453.png">

2023-01-10 12:35 UTC, caybro requested changes

2023-01-10 12:35 UTC, caybro commented on ui/imports/shared/status/StatusChatInput.qml
> +            } else if (QClipboardProxy.hasText) {
Needs a rebase :)

2023-01-10 12:37 UTC, alexandraB99 commented on ui/imports/shared/status/StatusChatInput.qml
> +            } else if (QClipboardProxy.hasText) {
yeah I know, just noticed

2023-01-10 12:40 UTC, caybro approved these changes
LGTM!

2023-01-10 12:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 1847122a | [#2](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-9027/2/) | 2023-01-10 12:42:49 | ~3 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-9027/2//consoleText) |

2023-01-10 18:23 UTC, alexjba approved these changes

2023-01-11 09:01 UTC, noeliaSD approved these changes

2023-01-11 14:46 UTC, merged