fix(MessageView): Fix calculating `isExpired` value
status-im/status-desktop pull request #9067
Opened 2023-01-11 15:05 UTC by igor-sirotin

Fixes https://github.com/status-im/status-desktop/issues/9066

1. Fixed arguments order in "Resend" button was never shown, because of a typo in arguments order
2. Also restored `now` variable for in `StatusDateGroupLabel` (there was a warning about it in log)

<img width="210" alt="image" src="https://user-images.githubusercontent.com/25482501/211839426-18ea9701-6165-4072-b2d4-4a3bbb4fcd68.png">

2023-01-11 15:08 UTC, caybro requested changes
Otherwise looks good :)

2023-01-11 15:08 UTC, caybro commented on ui/StatusQ/src/StatusQ/Components/StatusDateGroupLabel.qml
> +        const now = new Date()
Already fixed in https://github.com/status-im/status-desktop/pull/9026, rebase?

2023-01-11 15:08 UTC, caybro commented on ui/imports/shared/views/chat/MessageView.qml
> +            console.log(`<<< getIsExpired ${messageTimeStamp} ${Date.now()} ${timeout}`)
Remove

2023-01-13 07:45 UTC, alexjba approved these changes

2023-01-13 16:57 UTC, merged