fix(ContactVerificationRequestPopup): Fix overlapping messages
status-im/status-desktop pull request #9080
Opened 2023-01-12 12:39 UTC by MishkaRogachev

Close #9002 and #8950

### What does the PR do

Fix overlapping messages in ContactVerificationRequestPopup

### Affected areas

Profile, ActivityCenter

### Screenshot of functionality (including design for comparison)

<img width="600" alt="Screenshot 2023-01-16 at 15 08 23" src="https://user-images.githubusercontent.com/2522130/212664378-53d38cb2-da4f-49f0-893a-e2c5e1c03c6f.png">
<img width="530" alt="Screenshot 2023-01-16 at 14 59 32" src="https://user-images.githubusercontent.com/2522130/212664390-a5e36f44-4e18-4528-a56b-e2d5109f65d3.png">
<img width="518" alt="Screenshot 2023-01-16 at 14 58 31" src="https://user-images.githubusercontent.com/2522130/212664407-555e315b-6109-42a3-95f3-851835858c50.png">

2023-01-12 12:45 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 599e85a9 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9080/1/) | 2023-01-12 12:45:19 | ~5 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9080/1//consoleText) |

2023-01-16 10:15 UTC, igor-sirotin approved these changes
Nothing criminal detected 🙂

2023-01-16 10:15 UTC, igor-sirotin commented on ui/imports/shared/popups/ContactVerificationRequestPopup.qml
> +                leftPadding: 0
Are you sure about these zero-paddings?
Looks strange in your screenshot

2023-01-16 10:15 UTC, igor-sirotin commented on ui/imports/shared/views/chat/SimplifiedMessageView.qml
> +                anchors.fill: parent
`anchors.fill: parent` to the top? As per QML styling guidelines 🙂

2023-01-16 10:19 UTC, caybro requested changes

2023-01-16 11:13 UTC, caybro approved these changes

2023-01-17 05:51 UTC, elina2015 approved these changes
Tested and approved

2023-01-17 08:21 UTC, merged