fix(CommunityEdit): content width should have fixed size
status-im/status-desktop pull request #9109
Opened 2023-01-13 13:13 UTC by alexandraB99

Closes #9051

### What does the PR do
Fixes Community edit panel should have fixed width

### Affected areas
Community edit panel

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/31625338/212327821-0769e9af-753e-4d2f-8173-a7dd694a4619.mov

2023-01-13 13:25 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | f8d89afc | [#1](https://ci.status.im/job/status-desktop/job/branches/job/macos/job/PR-9109/1/) | 2023-01-13 13:25:45 | ~12 min | `macos` | [:apple:`dmg`](https://status-im-desktop-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Desktop-230113-131342-f8d89a-pr9109.dmg) |

2023-01-16 10:34 UTC, caybro approved these changes
LGTM

2023-01-16 10:40 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/panels/communities/CommunityEditSettingsPanel.qml
> +        width: 640
Should it be 608px following the design?

2023-01-16 10:41 UTC, noeliaSD approved these changes
LGTM! Also tested!

Just a small comment added!

2023-01-16 10:45 UTC, micieslak requested changes
Looks ok, one minor doubt here.

2023-01-16 10:48 UTC, micieslak commented on ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml
> +    implicitWidth: parent.width
From what I see `CommunityBannerPicker` is used in layout with `Layout.fillWidth: true` so this implicit width will be ignored in this case.

2023-01-16 11:02 UTC, alexandraB99 commented
> LGTM! Also tested!
> 
> Just a small comment added!

correct, I overlooked at the margins, fixed!

2023-01-16 13:42 UTC, alexandraB99 commented on ui/app/AppLayouts/Chat/controls/community/CommunityBannerPicker.qml
> +    implicitWidth: parent.width
removed!

2023-01-16 14:50 UTC, micieslak approved these changes
lgtm!

2023-01-16 15:00 UTC, merged