chore(CommunityPermissions): ENS tab simplified according to updated design
status-im/status-desktop pull request #9163
Opened 2023-01-17 23:16 UTC by micieslak

### What does the PR do

- Fixed ENS icon in "Who holds"
- Fixed locale handling in `AmountInput` (warning was generated, locale was set improperly)
- ENS tab simplified according to updated design

Closes #8818 

### Affected areas
`EnsPanel`, `HoldingsDropdown`, `CommunityNewPermissionsView`

### Screenshot of functionality (including design for comparison)

- [x] I've checked the design and this PR matches it

![Screenshot from 2023-01-18 00-14-47](https://user-images.githubusercontent.com/20650004/213033061-ec400f1a-10a0-4a82-a2ea-d5c5e00f8399.png)

2023-01-17 23:21 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b8335c11 | [#2](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9163/2/) | 2023-01-17 23:21:23 | ~2 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9163/2//consoleText) |

2023-01-17 23:27 UTC, caybro requested changes
Looks good in general, 2 minor things though

2023-01-17 23:27 UTC, caybro commented on ui/app/AppLayouts/Chat/controls/community/HoldingsDropdown.qml
> +                    PropertyChanges {target: holdingsTabs; sourceComponent: ensLayout; addOrUpdateButtonEnabled: d.ensReady/*; implicitHeight: 263*/}
leftover?

2023-01-17 23:27 UTC, caybro commented on ui/imports/shared/controls/AmountInput.qml
> +        locale: root.locale.toString()
Almost :)

2023-01-17 23:27 UTC, caybro commented on ui/imports/shared/controls/AmountInput.qml
> +        locale: root.locale.toString()
```suggestion
        locale: root.locale.name
```

2023-01-17 23:27 UTC, caybro commented on ui/imports/shared/controls/AmountInput.qml
> +        locale: root.locale.toString()
https://doc.qt.io/qt-5/qml-qtqml-locale.html#name-prop

2023-01-18 08:52 UTC, micieslak commented on ui/imports/shared/controls/AmountInput.qml
> +        locale: root.locale.toString()
haha :man_facepalming:, fixed :)

2023-01-18 08:56 UTC, caybro approved these changes

2023-01-18 09:01 UTC, noeliaSD approved these changes
LGTM! Tested!

2023-01-19 15:51 UTC, glitchminer reviewed
Issues found

Input is flagged as invalid with every second character.

https://user-images.githubusercontent.com/50769329/213485266-2ccd09d9-6691-4d6c-802f-e02ae438c623.mp4

2023-01-20 11:49 UTC, glitchminer approved these changes
Tested, approved with caveat:

Requirement for input validation and regex to be further refined and tested. Currently it's possible to add items that are not on the .eth domain. Character limits would also need reviewed.
![image](https://user-images.githubusercontent.com/50769329/213688066-1cc8eca4-8337-4025-94ef-52644010fcaa.png)

Other entries appear OK: 
![image](https://user-images.githubusercontent.com/50769329/213688253-6b013025-9ab4-4ca4-86e1-1050bade3127.png)

2023-01-20 13:00 UTC, merged