Cherry pick/fix/issue 6232 to 0.9.x
status-im/status-desktop pull request #9196
Opened 2023-01-19 15:50 UTC by MishkaRogachev

### What does the PR do

Cherry pick for https://github.com/status-im/status-desktop/pull/9172

2023-01-19 15:52 UTC, jrainville requested changes
This is missing the commit to remove the old popup

2023-01-19 15:55 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | dc32c169 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9196/1/) | 2023-01-19 15:55:17 | ~4 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9196/1//consoleText) |

2023-01-19 15:55 UTC, MishkaRogachev commented
> This is missing the commit to remove the old popup

my bad, just a moment

2023-01-19 16:00 UTC, jrainville approved these changes

2023-01-20 13:49 UTC, alaibe approved these changes

2023-01-20 14:10 UTC, merged