refactor(chat): make getChats async to speed up start time
status-im/status-desktop pull request #9363
Opened 2023-01-30 21:56 UTC by jrainville

Fixes #9340

Makes the getChats call async, so opening the app will be faster. You might see a (placeholder) loader when opening the app until chats and communities appear.

For QAs testing this, make sure the community section, chat section, stickers, activity center, ad-hoc chat thingy all still work as before

2023-01-30 21:59 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 6a812c46 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9363/1/) | 2023-01-30 21:59:24 | ~3 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9363/1/consoleText) |

2023-01-31 08:22 UTC, caybro commented on src/app_service/service/chat/service.nim
> +const SIGNAL_CHATS_LOADING_FAILED* = "chatsLoadindFailed"
typo, `chatsLoadingFailed`

2023-01-31 09:39 UTC, 0x-r4bbit commented
The PR seems to work, but as already expected, the perf improvement is barely noticeable because there are too many other things going with regards to RPC calls and work being done after login.

Because of that

>  You might see a (placeholder) loader when opening the app until chats and communities appear.

^ this will not really apply in practice with any database that has many messages.

Nonetheless, I think it's an improvement we should land. But to solve the bootstrap stalling, I fear a bigger refactoring is needed that I don't think is feasible atm.

2023-01-31 15:53 UTC, jrainville commented on src/app_service/service/chat/service.nim
> -    activityCenterNotifications*: seq[ActivityCenterNotificationDto]
Yes. That property was never used and it doesn't make sense in this service anyway. I was doing some clean up since I was working here.

2023-01-31 21:51 UTC, jrainville commented
@caybro fixed the typo plus I added an error/failure state in case of problem getting chat. It never happened until now and should never appear, but better safe than sorry

2023-01-31 22:00 UTC, caybro approved these changes
LGTM

2023-02-01 18:37 UTC, mprakhov approved these changes
LGTM 🏅

2023-02-02 09:08 UTC, 0x-r4bbit commented
Restarted CI on this one.

2023-02-02 10:35 UTC, endulab approved these changes

2023-02-06 01:11 UTC, elina2015 commented
@jrainville hey, I found a few things:
1. When I accept a contact request with some message, this message is not shown in the chat
2. In the Activity Center, the name and the default two letter are not shown for the contact request
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/14942081/216859637-d6d58c06-0bc8-4597-948a-51500dd3e56a.png">

2023-02-06 01:12 UTC, elina2015 requested changes
Found some issues

2023-02-06 07:25 UTC, 0x-r4bbit commented
@elina2015 I believe what you're reporting is not related to the changes here.
But just to let you know, I've reported something similar a few days ago https://github.com/status-im/status-desktop/issues/9424

2023-02-06 19:24 UTC, jrainville commented
@0x-r4bbit is probably right. My code doesn't affect contact requests or the AC. I think I saw those issue in master instead.

2023-02-06 23:37 UTC, elina2015 approved these changes
Tested and approved

2023-02-08 21:18 UTC, jrainville commented
Tests worked locally. Merging

2023-02-08 21:18 UTC, merged