QR code scanner (QML component)
status-im/status-desktop pull request #9464
Opened 2023-02-06 15:27 UTC by igor-sirotin

Required for https://github.com/status-im/status-desktop/issues/5837

### What does the PR do

This is a QR code scanner. Based on [QZXing](https://github.com/ftylitak/qzxing).

NOTE:
This overrides these 2 PRs:
- https://github.com/status-im/status-desktop/pull/5756
- https://github.com/status-im/dotherside/pull/65

I will also create a PR with changes made for QZXing library.
Currently pointing to status-im fork.

### Affected areas

StatusQ

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [x] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [x] test changes in both light and dark theme?

### Screenshot of functionality (including design for comparison)

https://user-images.githubusercontent.com/25482501/217012392-c56fd974-0f9e-4407-8c8b-1ff6ce2d4946.mov

2023-02-06 15:28 UTC, igor-sirotin commented
@0x-r4bbit, could you please test this un Windows?
@osmaczko , could you please test this un Linux?

2023-02-06 15:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 4865d33f | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9464/1/) | 2023-02-06 15:33:31 | ~5 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9464/1/consoleText) |

2023-02-06 15:36 UTC, 0x-r4bbit commented
@igor-sirotin unfortunately, I don't have a window machine

2023-02-06 15:49 UTC, caybro requested changes
Awesome amount of work, some minor things inline

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/controls/SyncDeviceDelegate.qml
> +        readonly property var daysOfWeek: [
https://doc.qt.io/qt-5/qml-qtqml-locale.html#dayName-method

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/controls/SyncDeviceDelegate.qml
> +            return qsTr("Online %1 minutes ago").arg(d.minutesFromSync);
Plural:
```suggestion
            return qsTr("Online %n minute(s) ago", "", d.minutesFromSync);
```

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/controls/SyncDeviceDelegate.qml
> +        return qsTr("Last online %1").arg(d.lastSyncDate.toLocaleDateString(Qt.locale()))
StatusQCore.LocaleUtils.formatFoo()

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/controls/SyncDeviceDelegate.qml
> +    // label: qsTr("Next back up in %1 hours")
commented out code? (if enabled, needs plural too as above :)

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml
> +    DSM.StateMachine {
Nice :)

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml
> +//        }
commented out code?

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/SetupSyncingPopup.qml
> +                if (displaySyncCodeState.active)    // TODO: This is temporary, remove
Still TODO?

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/SyncDeviceCustomizationPopup.qml
> +//            scrollView.channelName.input.asset.emoji = emojiText
commented out code?

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/SyncDeviceCustomizationPopup.qml
> +            text: "Done"
qsTr()

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/setupsyncing/EnterSyncCode.qml
> +//                                        : qsTr("Double check to make sure the code isn’t expired.")
commented out code?

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/setupsyncing/ScanSyncCode.qml
> +            const link = '<a href="https://github.com/status-im/status-desktop/pull/5756">#5756 Scan QR code</a>';
"Scan QR code" needs qsTr()

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/popups/setupsyncing/Syncing.qml
> +
empty line

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/views/SyncingView.qml
> +                console.log("<<< user ath", keyUid, pin, password)
Nope, don't show password to console :)

2023-02-06 15:49 UTC, caybro commented on ui/app/AppLayouts/Profile/views/SyncingView.qml
> +            // contentHeight: contentItem.childrenRect.height
commented out code

2023-02-06 15:49 UTC, caybro commented on ui/nim-status-client.pro
> +    app/AppLayouts/Profile/popups/setupsyncing/ErrorMessage.qml
Not needed

2023-02-06 15:49 UTC, caybro commented on src/app_service/service/devices/service.nim
> +    echo "<<< inputConnectionStringForBootstrapping result " & $result
debug leftovers?

2023-02-06 16:18 UTC, igor-sirotin commented
@caybro, it seems that I pushed my changes from other branch to this PR.
I'm really sorry for this, I've removed redundant commits.
But I will use your comments and fix them in my code anyway 🙂

2023-02-06 16:22 UTC, caybro reviewed
Looks better :)

2023-02-06 16:22 UTC, caybro commented on ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml
> +            console.log("<<< deviceId =", deviceId)
debug?

2023-02-06 16:22 UTC, caybro commented on ui/StatusQ/src/StatusQ/Components/StatusQrCodeScanner.qml
> +        text: qsTr("Camera unavailable: ") + camera.errorString
```suggestion
        text: qsTr("Camera unavailable: %1").arg(camera.errorString)
```

2023-02-06 16:33 UTC, igor-sirotin commented
@caybro, thanks for comments, fixed that!

2023-02-06 16:35 UTC, caybro approved these changes
Cool!

2023-02-07 08:21 UTC, osmaczko commented
@osmaczko , could you please test this un Linux?

It works! Although, it took a while to find the right angle :sweat_smile: 

https://user-images.githubusercontent.com/33099791/217190291-29b125e4-db8f-44fc-a707-a0e3696ddaf4.mp4

2023-02-07 08:27 UTC, osmaczko reviewed
The import check is broken because StatusQ knows nothing about DoOtherSide. This needs to be addressed, following https://github.com/status-im/status-desktop/issues/9125 rationale.

2023-02-08 19:41 UTC, alaibe approved these changes

2023-02-10 15:57 UTC, caybro reviewed
A big question: do we need this in DOtherSide? A better place would imho be `status-desktop/ui/StatusQ/src`, now that we decoupled those

cc @micieslak

2023-02-20 13:50 UTC, richard-ramos commented
Very cool PR! can confirm it works on linux!
Something that we should think in adding in the future is a webcam selector, as it currently does not have a way to choose which cam to use for scanning the QR code.

2023-02-21 08:39 UTC, micieslak commented
Great job! It works for me from Sandbox, but unfortunately there are still problems to run the main app:
```

/usr/bin/ld: vendor/DOtherSide/build/lib/libDOtherSideStatic.a(DOtherSide.cpp.o): in function `dos_qguiapplication_create':
DOtherSide.cpp:(.text+0x7cc9): undefined reference to `QZXing::registerQMLTypes()'
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'g++  @nim_status_client_linkerArgs.txt'
make: *** [Makefile:375: bin/nim_status_client] Error 1
01:00:04: The process "/usr/bin/make" exited with code 2.
```
I was playing a bit to solve that but so far no results. Some nim experts are needed here, I suppose...

2023-02-21 08:41 UTC, micieslak commented
> A big question: do we need this in DOtherSide? A better place would imho be `status-desktop/ui/StatusQ/src`, now that we decoupled those
> 
> cc @micieslak

If we want to use it in the main app (and we do, I suppose), we need to compile it via DOtherSide for the main app. At least I can't see any better solution for now.

2023-02-21 12:33 UTC, caybro commented
Definitely needs a rebase

2023-03-06 13:49 UTC, richard-ramos commented
This should build in Linux now!

2023-03-06 14:08 UTC, caybro commented
> This should build in Linux now!

Nope...
```
[2023-03-06T13:59:07.606Z] ERROR: ldd outputLine: "libodbc.so.2 => not found"

[2023-03-06T13:59:07.606Z] ERROR: for binary: "/opt/qt/5.15.2/gcc_64/plugins/sqldrivers/libqsqlodbc.so"

[2023-03-06T13:59:07.606Z] ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```

I don't know what on earth needs a Qt ODBC driver but it's not found

2023-03-06 15:06 UTC, richard-ramos commented
Interestingly enough, if I execute `ldd` in `./bin/nim_status_client`, I get the following list of libraries:
```
        linux-vdso.so.1 (0x00007ffdb69eb000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb91ec54000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fb91ebb0000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb91eb3a000)
        libQt5QuickControls2.so.5 => not found
        libQt5Quick.so.5 => /lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007fb91e5c0000)
        libQt5Qml.so.5 => /lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007fb91e134000)
        libQt5Multimedia.so.5 => not found
        libQt5Network.so.5 => /lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fb91df83000)
        libQt5Gui.so.5 => /lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fb91d8a5000)
        libQt5Core.so.5 => /lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fb91d346000)
        libstatus.so.0 => not found
        libkeycard.so => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb91d25d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb91d033000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb91d013000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb91cdeb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb9208a3000)
        libQt5QmlModels.so.5 => /lib/x86_64-linux-gnu/libQt5QmlModels.so.5 (0x00007fb91cd60000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb91cd42000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fb91ccee000)
        libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007fb91cc67000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fb91cc2c000)
        libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fb91cb5d000)
        libmd4c.so.0 => /lib/x86_64-linux-gnu/libmd4c.so.0 (0x00007fb91cb4b000)
        libdouble-conversion.so.3 => /lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007fb91cb34000)
        libicui18n.so.70 => /lib/x86_64-linux-gnu/libicui18n.so.70 (0x00007fb91c805000)
        libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007fb91c60a000)
        libpcre2-16.so.0 => /lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007fb91c580000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fb91c4b1000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb91c377000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fb91c2aa000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fb91c27b000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fb91c275000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fb91c267000)
        libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fb91c1af000)
        libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fb91c179000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fb91c0b1000)
        libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fb91c08a000)
        libicudata.so.70 => /lib/x86_64-linux-gnu/libicudata.so.70 (0x00007fb91a46c000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fb91a465000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb91a44f000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb91a30f000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fb91a301000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb91a2d7000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fb91a2b4000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb91a2ac000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb91a2a4000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb91a28c000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007fb91a27f000)
```

and no mention of libodbc.so

2023-03-06 15:22 UTC, caybro commented
> libqsqlodbc.so

But this is not the issue; you want to look at the runtime dependencies of the `libqsqlodbc.so` plugin, and here on my system:

```
ltinkl@zephyrus14:/usr/lib64/qt5/plugins/sqldrivers$ ldd libqsqlodbc.so  | grep -i odbc
	libodbc.so.2 => /lib64/libodbc.so.2 (0x00007f85ec5a4000)
```

2023-03-06 15:23 UTC, caybro commented
In other words, this seems more like a packaging problem, where we ship _all_ Qt plugins but some of them (namely the libqsqlodbc.so plugin which we don't even need in our app) have unsatisfied runtime deps

2023-03-06 16:30 UTC, richard-ramos commented
Interesting! i tried to build the app without using the lib and i'm running into the same error!
https://github.com/status-im/status-desktop/pull/9753

2023-03-06 16:44 UTC, caybro commented
> Interesting! i tried to build the app without using the lib and i'm running into the same error! #9753

Interesting... my fresh new PR builds just fine here: https://github.com/status-im/status-desktop/pull/9666; others don't seem to be having this problem either

2023-03-07 16:08 UTC, merged