chore(CommunityPermissions): Use enum for token category, keep string labels in UI only
status-im/status-desktop pull request #9560
Opened 2023-02-15 22:26 UTC by micieslak

### What does the PR do

Currently community permissions UI uses mocked store. Tokens models (assets, collectibles) had "category" name containing string presented in UI. It's changed to provide from backend only enum representing some predefined categories. UI is responsible for displaying proper textual representation to the user.

Closes: #9556

### Affected areas
`Community Permissions` components: `ExtendedDropdownContent`, `ListDropdownContent`

### Screenshot of functionality (including design for comparison)

UI hasn't changed.

2023-02-15 22:30 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d83f269b | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9560/1/) | 2023-02-15 22:30:37 | ~4 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9560/1//consoleText) |

2023-02-16 08:47 UTC, caybro approved these changes
LGTM

2023-02-16 11:11 UTC, alexjba approved these changes

2023-02-16 12:18 UTC, noeliaSD requested changes
LGTM! Much more better to have it as an enum! Nice!!

Just a super small detail that needs to be fixed!

2023-02-16 12:18 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/stores/CommunitiesStore.qml
> +                           conSource: "qrc:imports/assets/png/tokens/SOCKS.png",
It's causing warnings and this element cannot be selected! :)

```suggestion
                           iconSource: "qrc:imports/assets/png/tokens/SOCKS.png",
```

2023-02-16 12:34 UTC, noeliaSD approved these changes

2023-02-16 12:39 UTC, merged