chore(CommunityPermissions): Dissect real and mocked CommunitiesStore, adapt Storybook's pages
status-im/status-desktop pull request #9620
Opened 2023-02-22 23:04 UTC by micieslak

### What does the PR do

So far single implementation of `CommunitiesStore`, serving mocked data was used in both the app and storybook. In order to integrate the backend, the mock version is separated and moved to storybook. The app still serves mocks but replacing by integrating with backend won't affect storybook's pages.

Moreover:
- usages of `CommunitiesStore` are refactored to be strongly typed
- `CommunityTokenPermissionsPopup` and corresponding storybook's page fixed (displaying tokens)

Closes: #9612

### Affected areas
Community Permission components

2023-02-22 23:08 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | feac1400 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9620/1/) | 2023-02-22 23:08:56 | ~4 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9620/1//consoleText) |

2023-02-23 07:55 UTC, alexjba approved these changes
Nice work! Tested and looks good to me

2023-02-23 08:22 UTC, 0x-r4bbit approved these changes

2023-02-23 08:45 UTC, noeliaSD requested changes
LGTM!

Just minor issue on `storybook` ;) :
`file:///status-desktop/storybook/pages/HoldingsDropdownPage.qml:42:9: Cannot assign to non-existent property "store"`

2023-02-23 09:53 UTC, micieslak commented
> LGTM!
> 
> Just minor issue on `storybook` ;) : `file:///status-desktop/storybook/pages/HoldingsDropdownPage.qml:42:9: Cannot assign to non-existent property "store"`

Fixed! Thank you for detecting that!

2023-02-23 10:51 UTC, merged