test(community): Verify community permissions setting is available
status-im/status-desktop pull request #9622
Opened 2023-02-23 09:41 UTC by glitchminer

### What does the PR do

Adds scenarios for verifying that the advanced settings toggle for community permissions makes the option available under community managment.

### Affected areas

Tests for settings screens and community management

2023-02-23 09:45 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | ab68b4f9 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-9622/1/) | 2023-02-23 09:45:05 | ~2 min | `linux-cpp` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/linux-cpp/job/PR-9622/1/consoleText) |

2023-02-28 11:48 UTC, noeliaSD reviewed
Just minor comments added!

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/SettingsScreen.py
> +
empty line

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/SettingsScreen.py
> +
empty line

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/SettingsScreen.py
> +    #def click_on_community(community_name:str):
Leftover

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/SettingsScreen.py
> +        verify(False, "Community ")
```suggestion
        verify(False, "Community not found")
```

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/StatusCommunityScreen.py
> +        if community_sidebar_option=="Manage Community":
```suggestion
        if community_sidebar_option == "Manage Community":
```

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/StatusCommunityScreen.py
> +        if community_sidebar_option=="Manage Community":
Maybe we can create an enum for the sidebar options instead of direclty compare to a string

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/StatusCommunityScreen.py
> +        if option=="Permissions":
```suggestion
        if option == "Permissions":
```

Same comment than before, maybe we can create an enum with the possible options instead.

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/src/screens/StatusWelcomeScreen.py
> +#         common.clear_input_text(SignUpComponents.USERNAME_INPUT.value)
This should not be commented out!

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/testSuites/global_shared/steps/settingsSteps.py
> +
Empty line

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/testSuites/suite_communities/shared/scripts/names.py
> +
Empty lines

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/testSuites/suite_communities/shared/steps/communitySteps.py
> +# @Given("\"Test-Community\" community exists")
leftover

2023-02-28 11:48 UTC, noeliaSD commented on test/ui-test/testSuites/suite_communities/tst_communityPermissions/test.feature
> +# This is a sample .feature file
We can remove this intro text!

2023-02-28 11:52 UTC, noeliaSD requested changes
The commented out line in `StatusWelcomeScreen`: `common.clear_input_text(SignUpComponents.USERNAME_INPUT.value)` is causing the e2e tests failures in onboarding suite!

2023-02-28 11:53 UTC, noeliaSD commented
Another additional comment.. If we've modified the BDD statements, ensure to update the user story accordingly in `Notion`!

2023-03-16 08:16 UTC, noeliaSD approved these changes

2023-03-16 08:18 UTC, anastasiyaig commented
that one was tough! :D Thanks @glitchminer and @noeliaSD !

2023-03-16 08:18 UTC, anastasiyaig approved these changes

2023-03-16 08:20 UTC, merged