chore: add unixodbc-dev to list of dependencies
status-im/status-desktop pull request #9759
Opened 2023-03-06 22:39 UTC by richard-ramos

2023-03-06 22:45 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 20c1544e | [#1](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-9759/1/) | 2023-03-06 22:45:17 | ~5 min | `tests-nim` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/tests-nim/job/PR-9759/1//consoleText) |

2023-03-06 23:11 UTC, jakubgs requested changes
I will need to build this and push it. It doesn't build by itself because it's too slow and big.

2023-03-06 23:11 UTC, jakubgs commented on ci/Dockerfile
> +    unixodbc-dev \
Move them to where the rest of dev packages are:
![image](https://user-images.githubusercontent.com/2212681/223277624-849377b0-712d-44d7-b8d7-5d31b1527567.png)

2023-03-06 23:19 UTC, jakubgs commented
Could you also fix this typo? It should be `s3cmd` and `file`:
https://github.com/status-im/status-desktop/blob/20c1544ec4e786bd3bf4cffbf9f3d65469978274/ci/Dockerfile#L43

2023-03-06 23:29 UTC, jakubgs commented
I've pushed the image as `statusteam/nim-status-client-build:1.2.1-qt5.15.2`. Try it out.

2023-03-06 23:29 UTC, richard-ramos commented
Done!

2023-03-06 23:32 UTC, jakubgs requested changes
Also, please don't change JUST `Dockerfile`, `scripts/ubuntu_build_setup.sh` also needs love.

2023-03-07 02:17 UTC, richard-ramos commented
WTF. It's asking for libpq.so now

2023-03-07 03:26 UTC, richard-ramos commented
Alright, fixed! @jakubgs if you have some time tomorrow, please publish statusteam/nim-status-client-build:1.2.2-qt5.15.2

2023-03-07 08:28 UTC, jakubgs commented
New image pushed.

2023-03-07 13:19 UTC, merged

2023-03-07 13:20 UTC, caybro reviewed
Looks good!