feat(Community Mint Token): Add select wallet account option
status-im/status-desktop pull request #9961
Opened 2023-03-21 09:58 UTC by noeliaSD

Closes #9842

### What does the PR do
- It adds accounts selector in `Create new token` page.
- It adds account name box in `Preview` page.
- It updates `storybook` with new account data.
- It adds variant to `StatusComboBox`

### Affected areas
Community Settings / Mint token
StatusQ / StatusComboBox

### Screenshot of functionality
https://user-images.githubusercontent.com/97019400/226570243-3448af51-75f2-4730-a252-f31f99330836.mov

2023-03-21 10:08 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6d850cc6 | [#2](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9961/2/) | 2023-03-21 10:08:04 | ~6 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9961/2//consoleText) |

2023-03-21 11:47 UTC, caybro reviewed
Code LGTM, however I'm missing one component :)

2023-03-21 11:58 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
> +            CustomPreviewBox {
In `line 111` there is the inline definition for this component and in `line 35` the alias to set the value!

2023-03-21 12:01 UTC, caybro commented on ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
> +            CustomPreviewBox {
:coffee:

2023-03-21 12:02 UTC, caybro approved these changes
LGTM

2023-03-21 15:08 UTC, micieslak requested changes
Nice work in general, only minor comments and suggestions.

2023-03-21 15:08 UTC, micieslak commented on ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
> +        StatusComboBox {
Probably it's problem of `StatusComboBox` itself but clicking in the upper part of the component doesn't open the popup. Imo the whole component should react on click.

2023-03-22 07:44 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/views/communities/CommunityCollectibleView.qml
> +    property string accountAddress
Ok. No need to add a new signal, will create a d property in the panel and once the `mintCollectible`signal is triggered by `CommunityCollectibleView`, propagate the needed information to the next layer.

2023-03-22 07:57 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
> +                errorMessage: Utils.getErrorMessage(root.errors,
Ups! `customInput` insted!

2023-03-22 08:32 UTC, noeliaSD commented on ui/app/AppLayouts/Chat/views/communities/CommunityNewCollectibleView.qml
> +        StatusComboBox {
Yes, it is an issue with the `StatusComboBox` but I think that with then new variant. We can check it in a different task:  https://github.com/status-im/status-desktop/issues/9977

2023-03-22 10:10 UTC, noeliaSD commented
Pushed updates according to comments. @micieslak please review them again!

2023-03-22 11:20 UTC, micieslak requested changes
Looks good but
```CommunityCollectibleViewPage```
fails for me:
```
file:///home/michalc/workspace/status-desktop/storybook/pages/CommunityCollectibleViewPage.qml:41:17: Cannot assign to non-existent property "accountAddress"
```

2023-03-22 11:23 UTC, micieslak reviewed
Combo box now is clickable only in the area of the indicator :)

2023-03-22 13:40 UTC, noeliaSD commented
> Looks nice in general but `CommunityCollectibleViewPage` fails for me:
> 
> ```
> file:///home/michalc/workspace/status-desktop/storybook/pages/CommunityCollectibleViewPage.qml:41:17: Cannot assign to non-existent property "accountAddress"
> ```

Solved!

2023-03-22 13:41 UTC, noeliaSD commented
> Combo box now is clickable only in the area of the indicator :)

It will be reviewed here: https://github.com/status-im/status-desktop/issues/9977

2023-03-22 13:44 UTC, micieslak approved these changes
Nice :+1:

2023-03-23 07:24 UTC, merged