chore(CommunitySettings): Remove old legacy community popup
status-im/status-desktop pull request #9964
Opened 2023-03-21 12:43 UTC by borismelnik

Fixes: #9913

### What does the PR do

Remove legacy community popup call from settings.

PS: Don't know the popup should be removed as well cos it used in another place.  

### Affected areas

Community Settings

### StatusQ checklist

- [ ] add documentation if necessary (new component, new feature)
- [ ] update sandbox app
  - in case of new component, add new component page
  - in case of new features, add variation to existing component page
  - nice to have: add it to the demo application as well
- [ ] test changes in both light and dark theme?

2023-03-21 12:51 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4521eb81 | [#1](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9964/1/) | 2023-03-21 12:51:12 | ~7 min | `imports` | [:page_facing_up:`log`](https://ci.status.im/job/status-desktop/job/branches/job/imports/job/PR-9964/1//consoleText) |

2023-03-21 13:13 UTC, caybro requested changes
How do we transfer ownership now or share the link? This probably needs some design clarification first. It is still accessible via a context menu in the primary nav but this is not optimal (should be also accessible somewhere from the community settings)

talking about this:
![image](https://user-images.githubusercontent.com/5377645/226616436-bd78141b-07d2-4c1e-98a8-27d2a1d1f78a.png)

2023-04-12 15:30 UTC, jrainville commented
@caybro it's still accessible from the right click menu on the main nav (View community)

![image](https://user-images.githubusercontent.com/11926403/231506995-579c1dfe-b21c-4abb-a764-faaa44a3f32a.png)

We need some UX improvements in a couple places, but at least it's still available :smile:

2023-04-12 15:34 UTC, caybro requested changes
Fine then but still needs fixes, if it's meant to stay available via the primary nav

2023-04-12 15:34 UTC, caybro commented on ui/app/mainui/Popups.qml
> -        Global.openCommunityProfilePopupRequested.connect(openCommunityProfilePopup)
This must stay too

2023-05-02 11:45 UTC, borismelnik commented on ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
> +            text: "<- " + qsTr("Back to community")
@caybro could you pls show me an example? where I can find it?

2023-05-02 13:53 UTC, caybro commented
Also missing some kind of screenshot/video here, demonstrating the feature still works as expected

2023-05-02 14:17 UTC, caybro commented on ui/app/AppLayouts/Chat/ChatLayout.qml
> -            onOpenLegacyPopupClicked: Global.openCommunityProfilePopupRequested(root.rootStore, community, chatCommunitySectionModule)
Yeah, the popup is invoked from the primary nav directly via (from AppMain.qml):
```qml
StatusAction {
  text: qsTr("View Community")
  icon.name: "group-chat"
  onTriggered: popups.openCommunityProfilePopup(appMain.rootStore, model, communityContextMenu.chatCommunitySectionModule)
}
```

However, the popup must stay as it gives access to the "transfer" feature:
![image](https://user-images.githubusercontent.com/5377645/235693637-054c6f43-7e6f-4b81-b708-e33eafe8a2b9.png)

Or do we plan to put this somewhere else?

2023-05-02 14:19 UTC, borismelnik commented
@caybro @jrainville guys I totally missed the context... @jrainville asking about removing `openCommunityProfilePopupRequested`, @caybro asking about to leave it... so let's try to setting up the requirements:
1. Popup should be deleted?
2. Every signal and method as well?
3. What should be displayed when we click on `View Community` from context menu?

2023-05-02 14:26 UTC, jrainville commented on ui/app/AppLayouts/Chat/ChatLayout.qml
> -            onOpenLegacyPopupClicked: Global.openCommunityProfilePopupRequested(root.rootStore, community, chatCommunitySectionModule)
Oh, my bad, I didn't realize it was the same popup/function.
I thought it's what called the opening of the legacy edit popup.

So, does that mean that the old legacy popup is already removed? I checked quickly and it seems so.

Alright then, resolving this comment

2023-05-02 14:27 UTC, jrainville approved these changes

2023-05-02 14:27 UTC, jrainville commented on ui/app/AppLayouts/Chat/views/CommunitySettingsView.qml
> +            MouseArea {
This one is still used to go back to the community when in Edit mode

2023-05-02 14:27 UTC, caybro commented
The context is clear imho: remove the access to the (old/deprecated) community profile popup:
![image](https://user-images.githubusercontent.com/5377645/235695689-b8a6d3f8-ca7e-43f3-849a-f5d189361b34.png)

This is the popup (still accessible via context/RMB menu on the primary nav):

![image](https://user-images.githubusercontent.com/5377645/235696640-75def61f-5a52-43f4-892b-7b0ce8a9c65d.png)


![image](https://user-images.githubusercontent.com/5377645/235696456-ff9821bb-e6f9-4625-8f49-515850646acf.png)

However, we can't simply remove the popup itself too, as we don't have any other way to access the "Transfer ownership" feature, or am I missing something @jrainville ? :)

2023-05-04 15:15 UTC, borismelnik commented
@caybro Pls check Jo answer :) lets merge it!

2023-05-04 16:14 UTC, merged